### PR TITLE
ROX-23397: Set the default telemetry endpoint to RH proxy

### PR DESCRIPTION
**Pull request by 0x656b694d**
## Description

The endpoint value is propagated to the UI, and the manifests.

UI doesn't make use of this value though, will be fixed separately.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

* I set the variable, and checked the arrival of the events from my installation on Segment.
* I set an incorrect variable value, and confirmed the appearance of communication errors in the central logs.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by dhaus67** [comment]
@0x656b694d as discussed offline, here's some sample YAML you could use for testing things with a proxy:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: egress-proxy-config
  namespace: stackrox
  labels:
    app.kubernetes.io/component: egress-proxy
data:
  squid.conf: |
    # Squid proxy configuration

    # Domains to block if you want to put the segment one there.
    acl to_block dstdomain .segment.io

    # Disallow
    #http_access deny to_block
    #http_access deny CONNECT to_block

    # Catch-all rule for everything
    http_access allow all

    # Serve on standard port 3128
    http_port 3128

    # Disable caching and most logging
    cache deny all
    cache_log /dev/null
    debug_options ALL,5
    pid_filename none
    shutdown_lifetime 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-proxy
  namespace: stackrox
  labels:
    app.kubernetes.io/component: egress-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: egress-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: egress-proxy
    spec:
      containers:
      - name: egress-proxy
        image: "ubuntu/squid:5.2-22.04_beta"
        command:
        - "squid"
        - "-N"
        - "-f"
        - "/etc/squid/squid.conf"
        ports:
        - containerPort: 3128
          protocol: TCP
          name: egress-proxy
        volumeMounts:
        - name: config-volume
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: egress-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: egress-proxy
  namespace: stackrox
  labels:
    app.kubernetes.io/component: egress-proxy
spec:
  selector:
    app.kubernetes.io/component: egress-proxy
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  type: ClusterIP
```
```bash
kubectl create -f proxy.yaml --namespace stackrox

kubectl set env -n stackrox deploy/central HTTP_PROXY=http://egress-proxy.stackrox.svc:3128/
kubectl set env -n stackrox deploy/central HTTPS_PROXY=http://egress-proxy.stackrox.svc:3128/
kubectl set env -n stackrox deploy/central NO_PROXY=.stackrox.svc
```

**Comment by 0x656b694d** [comment]
UI part:
* #10758

**Review by stehessel — APPROVED** [review]

**Review by stehessel — COMMENTED** [review]
Sorry approved prematurely. What is the behavior when a Central proxy is configured?

**Comment by 0x656b694d** [comment]
Tested with in-cluster squid proxy.
With proxy failing:
```
pkg/telemetry/phonehome/segment: 2024/04/26 08:36:13.963643 segment.go:46: Error: Failure with message 'track': Post "https://console.redhat.com/connections/api/v1/batch": proxyconnect tcp: dial tcp 172.30.34.77:3128: connect: connection refused
```
With proxy running, the events pass, and proxy logs the requests:
```
CONNECT console.redhat.com:443 HTTP/1.1
Host: console.redhat.com:443
2024/04/26 11:50:32.421| 85,2| client_side_request.cc(714) clientAccessCheckDone: The request CONNECT console.redhat.com:443 is ALLOWED; last ACL checked: all
```

**Pull request merged**
