### PR TITLE
Bump  Scanner to 2.26.4

### PR DESCRIPTION
**Pull request by jvdm**
## Description

Bump  Scanner to 2.26.4

We are skipping `2.26.3` because that was cut in Dec. and did not have the latest vulnerabilities fixed.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

None of the above seems required for a Scanner bump for this release.

## Testing Performed

CI

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Review by RTann — APPROVED** [review]

**Comment by janisz** [comment]
@jvdm Would you like to prepare similar PR for 3.73?

**Comment by janisz** [comment]
Looks like failures should be fixed by https://github.com/stackrox/stackrox/pull/4943

**Pull request merged**
