### PR TITLE
chore(deps): use datadog instead of replace

### PR DESCRIPTION
**Pull request by janisz**
## Description

We were pinned to https://github.com/DataDog/gorocksdb/commit/f0fad39f321 as before with replace.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI should be enough and no changes to `go.sum`

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by janisz** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10390?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#10390** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10390?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#10373** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10373?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @janisz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by md2119 — COMMENTED** [review]
This won't be needed since we are removing rocksdb

**Comment by dashrews78** [comment]
> This won't be needed since we are removing rocksdb

+1, let's just leave this one be and let it eliminate itself as remove rocksdb.

**Comment by janisz** [comment]
Closing as this code will be removed.
@dashrews78 @md2119 Any estimated deletion time?

**Comment by dashrews78** [comment]
> Closing as this code will be removed. @dashrews78 @md2119 Any estimated deletion time?

@janisz No firm timeline.  Though work has started.  I intend to merge PR that deletes a bunch of migrations on Monday.  I'm going to intermingle it with my other work but try to spend some time on it each week.

**Pull request closed without merging**
