### PR TITLE
ROX-8301: Add force option to the detection service

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

Previously, only the `roxctl image scan` command had the ability to force a refetch within the image enricher. This is specifically useful when testing images within a pipeline continuously.

The PR added the following:
- force option for every request within the detection service.
- force flag to the commands `roxctl image check, roxctl deployment check`, allowing both to force a re-scan of the referenced images.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- see added unit tests + CI passing.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5277** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/5277" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/5277?utm_source=stack-comment).

**Comment by connorgorman** [comment]
@srcporter had created https://github.com/stackrox/stackrox/pull/4766, looks like this PR covers more

**Comment by dhaus67** [comment]
> @srcporter had created #4766, looks like this PR covers more

Oh, I didn't know that PR from @srcporter existed, my bad otherwise I would have left comments on that one.
I'll take a look to check whether they are covering the same.

**Comment by dhaus67** [comment]
Closing in favor of #4766 .

**Pull request closed without merging**
