### PR TITLE
Improve integration tests that initially failed on OpenShift

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

Baseline run to reproduce expected failures.

## Checklist
- [ ] Investigated and inspected CI test results
- [x] Unit test and regression tests added

## Testing Performed

### CODE REVIEW

**Comment by pedrottimark** [comment]
/test ocp-ui-e2e-tests

What do you think if we merge this batch, and then continue to investigate solutions to Vulnerability Managment?

**Review by vjwilson — APPROVED** [review]

**Review by gavin-stackrox — APPROVED** [review]

**Comment by pedrottimark** [comment]
22 Vulnerability Management tests are failing consistently. Still investigating how best to deal with them.

**Pull request merged**
