### PR TITLE
ROX-25292: Increase the timeout

### PR DESCRIPTION
**Pull request by lvalerom**
### Description

`Verify process visualization on default: #depName` fails due to some missing processes but those processes are later found in `Verify process paths, UIDs, and GIDs on #depName` and `Verify process arguments on #depName`. This suggest that the failures are due to timing issues. Increasing the waiting time for the processes to appear should fix the issue.

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing

- [x] inspected CI results

#### Automated testing

- ~[ ] added unit tests~
- ~[ ] added e2e tests~
- ~[ ] added regression tests~
- ~[ ] added compatibility tests~
- [x] modified existing tests

#### How I validated my change

This is particularly flaky in aro. Running CI multiple times to verify the solution:
- Four green runs
- [1818232412014907392](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12175/pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests/1818232412014907392) failed to create the cluster
- [1818237913410834432](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_stackrox/12175/pull-ci-stackrox-stackrox-master-aro-qa-e2e-tests/1818237913410834432) other test failed but `Verify process visualization on default: #depName` passed

### CODE REVIEW

**Review by Maddosaurus — APPROVED** [review]
LGTM! 
Nit: The loop where the  `MAX_SLEEP_TIME` is used could be replaced by a `withRetry`, but that's completely optional

**Comment by lvalerom** [comment]
> The loop where the MAX_SLEEP_TIME is used could be replaced by a withRetry, but that's completely optional

You are right. I think I'll do that in a follow-up PR though. I'll also change it in the rest of the test in this class.

**Pull request merged**
