### PR TITLE
chore: Bump COLLECTOR_VERSION to 3.19.0

### PR DESCRIPTION
**Pull request by Stringy**
### Description

Bumps COLLECTOR_VERSION to 3.19.0 for release

### User-facing documentation

- [x] CHANGELOG update is not needed
- [x] Documentation is not needed

### Testing

- [ ] inspected CI results

#### Automated testing

- [x] contributed **no automated tests**
  

#### How I validated my change

CI should be sufficient. Previous version has been under test for some time, and 3.19.0 has few code changes since then.

### CODE REVIEW

**Review by Molter73 — APPROVED** [review]

**Comment by Stringy** [comment]
GKE e2e failures are known flakes and unrelated to Collector:
- https://issues.redhat.com/browse/ROX-25042
- https://issues.redhat.com/browse/ROX-25043

**Comment by Stringy** [comment]
Merging now, based on the failures being known flakes, and unrelated to Collector.

**Pull request merged**
