### PR TITLE
ROX-17499: Remove qa e2e test auto retry

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

Per title. This feature relies on global state and would need significant refactoring to work with test parallelization. And if I recall correctly, this has generally been considered an undesirable feature that supports poorly written and flaky tests. [citation needed: I *know* we discussed this somewhere].

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

- [x] Many qa-e2e of typical PR flavors (GKE, OCP).
- [x] One run all-qa run for sanity

There are test failures that might have passed on a retry but there are no systemic test failures. i.e. ones that require  retry to pass.

### CODE REVIEW

**Review by porridge — APPROVED** [review]
+1000!

**Review by janisz — APPROVED** [review]

**Pull request merged**
