### PR TITLE
ROX-8051: make eBPF the default collection method

### PR DESCRIPTION
**Pull request by Stringy**
## Description

Makes eBPF the default collection method, following from eBPF performance improvements in collector. This touches defaults in the helm charts, operator, deploy scripts, and the UI. 

I _think_ I've caught everything but it'd be useful to know if there's other parts that need changing.  

## Checklist
- [x] Investigated and inspected CI test results
~- [ ] Unit test and regression tests added~
- [x] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Deployed locally on docker-desktop and on openshift 4 using infra.

### CODE REVIEW

**Comment by Stringy** [comment]
FYI @stackrox/collector-team

**Review by mtesseract — APPROVED** [review]
looking good to me

**Review by vjwilson — APPROVED** [review]
UI looks good.

Just one request, be sure to sanity-test it by "creating" one cluster with the form.

**Comment by Stringy** [comment]
As requested - some screenshots showing the default change when creating a new cluster:

before-default-change

after-default-change

**Pull request merged**
