### PR TITLE
ROX-19344: Add e2e tests for vuln deferral configuration

### PR DESCRIPTION
**Pull request by dvail**
## Description

As titled.

Note: we may want to hold off merging this until the API stabilizes, as tests may fail once the "Indefinite" option is added to the API.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Comment by dvail** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7816** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7816" target="_blank">Graphite</a> 
    * **PR #7825** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7825" target="_blank">Graphite</a> 
      * **PR #7836** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7836" target="_blank">Graphite</a> 
        * **PR #7837** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7837" target="_blank">Graphite</a> 
          * **PR #7838** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7838" target="_blank">Graphite</a> 
            * **PR #7841** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7841" target="_blank">Graphite</a> 
              * **PR #7862** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7862" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7862?utm_source=stack-comment).

**Comment by sachaudh** [comment]
@dvail should I hold off on reviewing this until the API stabilizes then?

**Comment by dvail** [comment]
@sachaudh The last option has been added to the config, so this PR now enables the `indefinite` option as well as adding the e2e tests.

**Review by sachaudh — APPROVED** [review]

**Comment by dvail** [comment]
The failing e2e test is a known, unrelated issue.

**Pull request merged**
