### PR TITLE
ROX-16899: fix the error type test

### PR DESCRIPTION
**Pull request by parametalol**
## Description

e2e test fix after go version bump to 1.20.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

CI e2e.

### CODE REVIEW

**Comment by 0x656b694d** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5932** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/5932" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/5932?utm_source=stack-comment).

**Review by vikin91 — APPROVED** [review]

**Pull request merged**
