### PR TITLE
Remove goveralls, as we no longer use it

### PR DESCRIPTION
**Pull request by misberner**
## Description

Title says it all.

## Checklist
- [ ] Investigated and inspected CI test results
- [x] ~Unit test and regression tests added~
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

- CI

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Comment by janisz** [comment]
Maybe we should restart using it?

**Comment by misberner** [comment]
> Maybe we should restart using it?

I think that's a discussion to be had independently. Maybe we should restart doing some coverage metrics collection. Maybe we should use goveralls for that. But we should not do either just because the dependency happens to lie around unused in the `Makefile`. Therefore I would proceed with this PR.

**Comment by misberner** [comment]
Postgres test failure is not related.

**Pull request merged**
