### PR TITLE
remove GetNodeRescanInterval(), as it is no longer needed

### PR DESCRIPTION
**Pull request by RTann**
## Description

Duration environment variables are now validated upon registration and retrieval. See https://github.com/stackrox/stackrox/blob/master/pkg/env/durationsetting.go#L46 for more information

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI

### CODE REVIEW

**Comment by vikin91** [comment]
@RTann, we added this function, because providing 0 or negative rescan interval causes a panic. The user is an actor who  configures this, so the input validation is something that may make sense.

**Comment by RTann** [comment]
> @RTann, we added this function, because providing 0 or negative rescan interval causes a panic. The user is an actor who configures this, so the input validation is something that may make sense.

I probably should have added this to the description, but this is already validated as-is. I'll do it now: https://github.com/stackrox/stackrox/blob/master/pkg/env/durationsetting.go#L46

**Comment by vikin91** [comment]
Could you give it a quick test with 
`kubectl -n stackrox set env daemonsets/collector --containers="compliance" ROX_NODE_RESCAN_INTERVAL="0s"` 
or
`kubectl -n stackrox set env daemonsets/collector --containers="compliance" ROX_NODE_RESCAN_INTERVAL="-5s"`

**Comment by vikin91** [comment]
> > @RTann, we added this function, because providing 0 or negative rescan interval causes a panic. The user is an actor who configures this, so the input validation is something that may make sense.
> 
> I probably should have added this to the description, but this is already validated as-is. I'll do it now: https://github.com/stackrox/stackrox/blob/master/pkg/env/durationsetting.go#L46

Oh, I see now, this looks good!

**Review by vikin91 — APPROVED** [review]
Cool, thanks for optimizing-out the redundant code :)

**Pull request merged**
