### PR TITLE
Update Scanner lib to latest master

### PR DESCRIPTION
**Pull request by Maddosaurus**
## Description

Quick PR to update the Scanner `go.mod` to latest `scanner@master`.
Additionally, as one field in the Proto was renamed in Scanner PR 1004, I have updated the getter function in StackRox accordingly.

## Testing Performed

Ensured `make image` succeeds, deployed locally on Colima

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]
LGTM!

Do we also want to update the `SCANNER_VERSION` file with the current scanner-master?

**Review by RTann — APPROVED** [review]

**Comment by Maddosaurus** [comment]
> Do we also want to update the SCANNER_VERSION file with the current scanner-master?

@vikin91 I didn't touch the scanner version file just yet. IIRC, it will likely be updated in the release process that will start within the next days, correct?

**Comment by vikin91** [comment]
> > Do we also want to update the SCANNER_VERSION file with the current scanner-master?
> 
> @vikin91 I didn't touch the scanner version file just yet. IIRC, it will likely be updated in the release process that will start within the next days, correct?

That is correct, but:
- this update is usually done by the Scanner team, not by the release engineers,
- I do not see a reason to postpone it - I think we should update it asap, so that we have enough time to discover potential bugs early before the release

**Comment by Maddosaurus** [comment]
@vikin91 While rebasing this PR to latest master, I just discovered that roxbot updated the SCANNER_VERSION 2 hours ago.
Therefore, I'll skip the update, which I had originally done after your comment :) 
https://github.com/stackrox/stackrox/commit/e3d7f04e7fb72a371c9456c369a5bec4a9f1e95f

**Pull request merged**
