### PR TITLE
ROX-24119: Configure node-inventory container to be privileged

### PR DESCRIPTION
**Pull request by mclasmeier**
## Description

This should prevent the node-inventory container triggering SELinux violations on OpenShift with SELinux enabled.

This has already been tested [with an overlay](https://github.com/stackrox/acs-fleet-manager/pull/1799) in ACSCS in the integration environment.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Testing in ACSCS integration environment.
The [Grafana dashboard](https://grafana-route-rhacs-observability.apps.acs-int-us-01.isbr.p1.openshiftapps.com/d/4032f3c17643119901e107a0a1786d5b9e4c9565/rhacs-dataplane-cluster-metrics?orgId=1) shows no SELinux violations.

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]
The change looks great! 
@Maddosaurus was more involved in the work with you, so he can review also the testing procedure for this

**Review by Maddosaurus — APPROVED** [review]

**Comment by Maddosaurus** [comment]
I've been involved in the whole process and have seen the Grafana Dashboards before the change.
Looks great, thank you for the PR!

**Comment by mclasmeier** [comment]
Please merge if the failing test are flakes.

**Comment by vikin91** [comment]
I didn't do in depth analysis of the tests failing here, but they look unrelated. Do you maybe want to merge this @mclasmeier ?

**Pull request merged**
