### PR TITLE
Set new Operator icon

### PR DESCRIPTION
**Pull request by msugakov**
## Description

See https://redhat-internal.slack.com/archives/C3W47R5LP/p1682014497303189

## Checklist
- [x] Investigated and inspected CI test results
- ~~[ ] Evaluated and added CHANGELOG entry if required~~ - probably we don't need one since the change is cosmetic. I only hope customers will still be able to easily find the product in the catalog.

Won't do these:
- [ ] Unit test and regression tests added
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

- [x] Screenshot of the modified entry in the operator hub posted in this PR.

### CODE REVIEW

**Comment by msugakov** [comment]
image

image

**Review by porridge — APPROVED** [review]
A bit too small for my taste, but I'm not the artist here :-P

**Comment by msugakov** [comment]
+1 on too small but the [guidelines](https://www.redhat.com/en/about/brand/standards/icons/product-icons) tell we shouldn't modify icons.

image

**Comment by msugakov** [comment]
image
image

**Pull request merged**
