### PR TITLE
ROX-23528: Add integration name + insecure flag to logs/errors

### PR DESCRIPTION
**Pull request by dcaravel**
## Description

To assist with future troubleshooting, this PR enhances the delegated scanning logs and errors:

1. Changes the word `registry` to `integration` to match what a user would understand
   - `registry` was only meaningful when looking at the code.
2. Adds the integration name to the messages associated with each metadata pull failure
   - This enables confirming if image <-> registry matching is expected.
4. Adds value of the 'insecure' flag to the metadata pull failure msg as well.
   - For integrations built from pull secrets this flag is determined at runtime by performing a [TLS Check](https://github.com/stackrox/stackrox/blob/be722f22ae1f9e38cdcd53e28ed1b2aef05b7e01/sensor/common/registry/registry_store.go#L199)
   - Knowing the value of the flag may help troubleshooting connectivity failures.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [x] Evaluated and added CHANGELOG entry if required
- [x] Determined and documented upgrade steps
- [x] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

Deployed to infra clusters and delegated scans for images that do not exist:

_Outputs edited for clarity_

### Before
```
$ rctl image scan --image=quay.io/dcaravel/no:exist --cluster=remote
ERROR:	Scanning image failed: could not scan image: "quay.io/dcaravel/no:exist": rpc error: code = Internal desc = error delegating scan to cluster "9b2ba00d-f4b3-4bcf-bc72-9971ea97917c" for "quay.io/dcaravel/no:exist": image enrichment errors: [

failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=404 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body="")]. 

Retrying after 3 seconds...
```
Notice 4 duplicate errors occurred, unclear why.   Similarly in sensor logs:

```
delegated_registry_handler.go:131: Error: Scan failed for req "c0f1125d-3ece-418e-8d8d-b4627e8f717e" image "quay.io/dcaravel/no:exist": image enrichment errors: [

failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=404 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body="")]
```

### After
```
$ rctl image scan --image=quay.io/dcaravel/no:exist --cluster=remote
ERROR:	Scanning image failed: could not scan image: "quay.io/dcaravel/no:exist": rpc error: code = Internal desc = error delegating scan to cluster "9b2ba00d-f4b3-4bcf-bc72-9971ea97917c" for "quay.io/dcaravel/no:exist": image enrichment errors: [

with integration "Quay Dave Global Pull" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
with integration "Quay Dave Personal" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=404 body=""), 
with integration "Public Quay.io" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
with integration "Global/reg:quay.io" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body="")]. 

Retrying after 3 seconds...
```

```
delegated_registry_handler.go:131: Error: Scan failed for req "95f622b1-6428-40e8-8cc4-20d73ebbc3f2" image "quay.io/dcaravel/no:exist": image enrichment errors: [

with integration "Quay Dave Global Pull" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
with integration "Quay Dave Personal" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=404 body=""), 
with integration "Public Quay.io" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body=""), 
with integration "Global/reg:quay.io" (insecure: false): failed to get the manifest digest: Head "https://quay.io/v2/dcaravel/no/manifests/exist": http: non-successful response (status=401 body="")]

```

### CODE REVIEW

**Comment by dcaravel** [comment]
Moving back to draft while addressing unit test failures.

**Comment by RTann** [comment]
> Changes the word registry to integration to match what a user would understand
registry was only meaningful when looking at the code.

what about `registry integration`? That way we still know it's a registry

**Review by RTann — APPROVED** [review]

**Pull request merged**
