### PR TITLE
Upgrade to pgx and pgxpool v5

### PR DESCRIPTION
**Pull request by connorgorman**
## Description

Pick up the latest changes to the pgx library

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Comment by md2119** [comment]
I literally did it in one of my PRs because I need this for my search framework enhancements.

**Review by c-du — APPROVED** [review]

**Comment by md2119** [comment]
Do we want to upgrade v5 now? Seems like the performance of v5 are inferior to v4. Ref: https://github.com/jackc/pgx/issues/1481

**Comment by connorgorman** [comment]
@md2119 
```
Do we want to upgrade v5 now? Seems like the performance of v5 are inferior to v4. Ref: https://github.com/jackc/pgx/issues/1481
```

This was on a windows machine. There is an issue resolving arrays which we need to fix. Haven't figured it out yet

**Comment by connorgorman** [comment]
I'm also tempted to just hide this underneath a struct so it's not a 405 line change

**Comment by janisz** [comment]
Refs:

- #6915

**Pull request closed without merging**
