### PR TITLE
fix(test): Fix the way the statics pods are counted in TopNav

### PR DESCRIPTION
**Pull request by lvalerom**
### Description

`getSTaticPodCount` already filters the static pods the way sensor does it. Filtering for pod names that start with `static` is no always right as sensor only adds that prefix to kube-proxy pods that have a non-tracked owner.

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [x] modified existing tests

#### How I validated my change

- [ ] TopNav deployment count should pass

### CODE REVIEW

**Review by jschnath — APPROVED** [review]
LGTM

**Comment by vikin91** [comment]
Cool that this PR has happened :) How did it improve our situation in CI?

**Comment by lvalerom** [comment]
> How did it improve our situation in CI?

For what I've seen lately, most of the active failures of the summary tests are Compatibility tests that use a Central version that does not have the deduper fix #12591. Additionally, I noticed that the way TopNav was gathering the static pods from the cluster was outdated. Hopefully we will see less flakiness after this change 🤞.

**Pull request merged**
