### PR TITLE
Bump collector version

### PR DESCRIPTION
**Pull request by Molter73**
## Description

The version being used holds the latest changes from the upstream Falco libraries.

## Checklist
- [x] Investigated and inspected CI test results
~- [ ] Unit test and regression tests added~
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI should be enough.

### CODE REVIEW

**Review by Stringy — APPROVED** [review]

**Comment by Molter73** [comment]
Looking into the failures from CI:
- Some are from registry and scanner tests that should be unrelated to collector.
- There are some more errors that are also showing up on other PRs, so I believe they are also unrelated to this change.

**Pull request merged**
