### PR TITLE
ROX-26042: check for duplicate authprovider name in creation flow

### PR DESCRIPTION
**Pull request by rhybrillou**
### Description

The OpenShift AuthProvider leaks backend loop registrations in case an AuthProvider creation request re-uses the name of an existing AuthProvider.

This change is part of a PR stack to refactor the OpenShift AuthProvider backend registration loop, and to introduce an early constraint violation check early in the provider creation process.
- #12958
  - #12959

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [x] added unit tests
- [ ] added e2e tests
- [x] added regression tests
- [ ] added compatibility tests
- [x] modified existing tests

#### How I validated my change

Reproducer case unit/integration test.

### CODE REVIEW

**Review by mtodor — APPROVED** [review]

**Review by dashrews78 — COMMENTED** [review]
Do auth providers get reprocessed and re-inserted on startup?  If not this WILL require a migration to populate the column.

If it does need a migration be aware that I have one I'm going to merge in the next day.
https://github.com/stackrox/stackrox/pull/12987

**Comment by rhybrillou** [comment]
> Do auth providers get reprocessed and re-inserted on startup? If not this WILL require a migration to populate the column.
> 
> If it does need a migration be aware that I have one I'm going to merge in the next day. #12987

A very good point that I missed. Thank you very much @dashrews78 . I'll push the migration (simple read and write back) in a follow-up PR.

**Review by dashrews78 — APPROVED** [review]

**Comment by rhybrillou** [comment]
> > Do auth providers get reprocessed and re-inserted on startup? If not this WILL require a migration to populate the column.
> > If it does need a migration be aware that I have one I'm going to merge in the next day. #12987
> 
> A very good point that I missed. Thank you very much @dashrews78 . I'll push the migration (simple read and write back) in a follow-up PR.

A further check suggests the search column already exists from the beginning to enforce the name unicity constraint. There is therefore no change to the data model, nor need to migrate any data.

**Comment by dashrews78** [comment]
> > > Do auth providers get reprocessed and re-inserted on startup? If not this WILL require a migration to populate the column.
> > > If it does need a migration be aware that I have one I'm going to merge in the next day. #12987
> > 
> > 
> > A very good point that I missed. Thank you very much @dashrews78 . I'll push the migration (simple read and write back) in a follow-up PR.
> 
> A further check suggests the search column already exists from the beginning to enforce the name unicity constraint. There is therefore no change to the data model, nor need to migrate any data.

Ah yes.  I was just triggered on the change to the proto and didn't notice that the schema didn't change (at least the structure didn't).

**Pull request merged**
