### PR TITLE
Groovy test changes to add multi-arch support

### PR DESCRIPTION
**Pull request by pratham-m**
## Description

This PR intends to add multi-arch support for the groovy tests.
Test images used in respective test are changed to use alternate multi-arch images which support 3 platforms viz. `x86_64`, `ppc64le` and `s390x`.

Changes are verified manually using `./gradlew test --tests=TestName`

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
Hi @pratham-m, Once this PR runs the default CI ok can you:
- Add the label `ci-all-qa-tests`
- And then get more coverage with: `/test openshift-newest-qa-e2e-tests` and `/test gke-qa-e2e-tests` comments
Thanks,
-Gavin

**Comment by pratham-m** [comment]
Hi @gavin-stackrox  cc @robbycochran test execution is complete. kindly let me know if you have any review comments.

**Review by gavin-stackrox — APPROVED** [review]
LGTM!

**Pull request merged**
