### PR TITLE
[ROX-13525] : Change getCollectionCount endpoint and updateCollection request type

### PR DESCRIPTION
**Pull request by charmik-redhat**
## Description

GetCollectionCount endpoint changed to `/v1/collectionscount`
UpdateCollection request type changed to `PATCH`

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

Did manual testing of create, update, get, list, getCount and delete endpoints

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by keyallis — APPROVED** [review]

**Comment by keyallis** [comment]
Lets make sure we manually verify that the endpoints can be invoked as expected and we have a green CI before merging

**Review by md2119 — APPROVED** [review]

**Pull request merged**
