### PR TITLE
Disable auto code generator for postgres migrations

### PR DESCRIPTION
**Pull request by c-du**
## Description

Disable auto code generator for postgres migrations. 
This one will be after the schema freeze PR and for 3.74 https://github.com/stackrox/stackrox/pull/3769
## Checklist
- [ ] Investigated and inspected CI test results~
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps`
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by md2119 — COMMENTED** [review]
Can we add a check in the generator code to errors out if a migration flag is encountered? It will ensure that nobody mistakenly adds a migration.

**Comment by dashrews78** [comment]
Do we need to update the comment in the generated files or is that OK to leave?
`// Code generated by pg-bindings generator. DO NOT EDIT.`

Or do we just deal with that if we need to update something in one of those files?

**Comment by c-du** [comment]
> 

Let's leave it as is. Most likely and ideally we don't need to update them anymore. They would be obsoleted in a few releases.

**Comment by c-du** [comment]
> Can we add a check in the generator code to errors out if a migration flag is encountered? It will ensure that nobody mistakenly adds a migration.
In that case, it would be better to remove the migration flags in the generator.

**Review by md2119 — APPROVED** [review]

**Review by dashrews78 — APPROVED** [review]

**Pull request merged**
