### PR TITLE
ROX-25621: Add multi-arch Konflux builds to main image

### PR DESCRIPTION
**Pull request by msugakov**
### Description

Per title, replaces <https://github.com/stackrox/stackrox/pull/12054>.

Tracking build issues in:

- https://issues.redhat.com/browse/KFLUXBUGS-1523
- https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1723056835366329

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [x] CI results are inspected

#### Automated testing

No changes to automated tests.

#### How I validated my change

Only Konflux CI.

### CODE REVIEW

**Review by Stringy — APPROVED** [review]
LGTM! thanks for finishing this off @msugakov

**Comment by msugakov** [comment]
Quay flakes in https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-tv86k

**Comment by msugakov** [comment]
Except for quay upload of clamav-scan results everything succeeded in https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-9cl8k
It's really a pity that I need to rerun and wait for it again.

**Comment by msugakov** [comment]
Quay flakes in https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-g9892

**Pull request merged**
