### PR TITLE
Jv rox 16533 changelog for processes listening on ports release

### PR DESCRIPTION
**Pull request by JoukoVirtanen**
## Checklist
- [ ] Investigated and inspected CI test results

## Testing Performed

CI is sufficient

### CODE REVIEW

**Comment by robbycochran** [comment]
This PR isn't necessary. You can close it -- all that is needed is a PR on master tagged with the rc milestone.

**Comment by dashrews78** [comment]
> This PR isn't necessary. You can close it -- all that is needed is a PR on master tagged with the rc milestone.

Seems like we could just put this directly in release as opposed to going through all the RC process which will spawn a bunch of environments, etc.  Not exactly sure what the normal process for these would be, but seems like cutting an RC for this would be overkill.

**Comment by robbycochran** [comment]
I agree, we don't need to create an RC just for a changelog.

> Seems like we could just put this directly in release as opposed to going through all the RC process which will spawn a bunch of environments, etc. Not exactly sure what the normal process for these would be, but seems like cutting an RC for this would be overkill.

**Review by dashrews78 — APPROVED** [review]

**Review by dashrews78 — CHANGES_REQUESTED** [review]
We can close this now.  I had to cut rc-5 for other reasons.  so I was able to pull this from the push to master.

**Pull request closed without merging**
