### PR TITLE
Restructure migrations to better version postgres schemas

### PR DESCRIPTION
**Pull request by rhybrillou**
## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Comment by c-du** [comment]
Migration 169 to 172 are introduced in 74. Why moving related schema and store to v75?

**Comment by rhybrillou** [comment]
> Migration 169 to 172 are introduced in 74. Why moving related schema and store to v75?

My idea here is to decorrelate the datamodel versions from the product release versions. The starting point is v73, then each datamodel change (column addition, removal, new table) is a new datamodel version.
It might be a good idea here to also keep track of the last datamodel version in which each schema was last modified, as it would help figure out where to search for the store in case of data manipulation only migrations.

**Comment by rhybrillou** [comment]
In the current state of things, the philosophy is that each migration (data manipulation or data model definition) should embed the files it needs.

**Pull request closed without merging**
