### PR TITLE
Bump openshift/api dependency for #6050

### PR DESCRIPTION
**Pull request by vikin91**
## Description

Isolating a change form #6050 to test it using e2e tests (for some reasons e2e tests do not start for PRs open by external contributors).

## Checklist
- [x] Investigated and inspected CI test results - see [comment](https://github.com/stackrox/stackrox/pull/6108#issuecomment-1558829935)

### N/A
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

- CI

### CODE REVIEW

**Comment by vikin91** [comment]
This PR is mainly about the OpenShift API dependency and all OS tests are passing. I looked into Go and GKE tests failures and they seem unrelated.

**Review by jschnath — APPROVED** [review]

**Pull request merged**
