### PR TITLE
ROX-20788: optimize transport for concurrent reads

### PR DESCRIPTION
**Pull request by stehessel**
## Description

This is a performance improvement for the "read path" - i.e. when the token is valid and simply read and applied in the transport. We want this to happen concurrently without multiple requests blocking each other. What we pay is that we may refresh the token multiple times, and that we cannot guarantee that the token is the same when it is checked and when it is used (TOC-TOU).

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

tested on test cluster

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by stehessel** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9117?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #9002** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9002?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #8949** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/8949?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #9031** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9031?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #9117** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9117?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/9117?utm_source=stack-comment).

**Review by dhaus67 — APPROVED** [review]
Guess this renders some of my comments on the original PR answered, LGTM.

**Review by vikin91 — APPROVED** [review]

**Review by RTann — COMMENTED** [review]
I fear it could be possible for the transport's fields to change mid-use because of this. Can we just use a copy of the transport? We know the copy won't be messed with when in-use

**Comment by stehessel** [comment]
> I fear it could be possible for the transport's fields to change mid-use because of this. Can we just use a copy of the transport? We know the copy won't be messed with when in-use

I don't think I can follow. Can you give an example under which the data race would happen? As far as I understand, `t.refreshNoLock` and `t.Transport` are protected by the same mutex, and `t.Transport.RoundTrip` itself should be concurrency-safe. What can happen is the TOC-TOU as pointed out the comment, but that should not mutate the transport while in use.

**Review by RTann — APPROVED** [review]

**Pull request merged**
