### PR TITLE
Build release images on main branch merge

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

This PR was instigated by [this discussion](https://redhat-internal.slack.com/archives/CELUQKESC/p1682100466023219) which settled on a release image built for each merge to the main branch tagged `-prerelease`. Along the way I 'tidied up' some CI labels and ultimately ran through the following behavior expectations and tests.

### When a PR is merged to the main branch

A `-prerelease` tagged image is created built with `GOTAGS=release`.

#### Tested with

- Temporarily change the workflow branch name to the implementing PR branch
  name, remove pull triggers and force `is_in_PR_context()=1`. The github action
  for the commit push will simulate a merge to master.
  Expect:
  - [x] - Default images are development builds, creates `-prerelease`, creates `-rcd`. [build](https://github.com/stackrox/stackrox/actions/runs/4898417787)
  - [x] - Install and verify default images is_release = false.
  - [x] - Install `-prerelease` and verify is_release = true.

### When a tag is pushed

All images are built with `GOTAGS=release` and no `-prerelease` image is
needed. A `-rcd` image is created as required for
`gke-race-condition-qa-e2e-tests`.

#### Tested with

- Push a tag for the PR branch 0.0.1-rc1
  Expect:
  - [x] - Default images are release builds, skips `-prerelease`, creates a `-rcd`. [build](https://github.com/stackrox/stackrox/actions/runs/4898650352)
  - [x] - Install and verify default images is_release = true.

### Labels effect on pushes to PRs

New label: `ci-build-race-condition-debug` - builds a main image with `-race` and gives it a `-rcd` tag suffix. Currently these images are built for all PRs in order to be available for the unlikely run of a `/test gke-race-condition-qa-e2e-tests` on a PR.

Existing seldom used label: `ci-race-tests` - all images on a PR are built as race-condition-debug images (`-race`) and so all E2E tests run against `-race` images. (Was the behavior in Circle CI and before OSCI to GHA build migration).

New label: `ci-build-prerelease` - builds a main image with `GOTAGS=release` and gives it a `-prerelease` tag suffix.

Existing sometimes used label: `ci-release-build` - all images on a PR are built as release images (`GOTAGS=release`) and so all E2E tests run against release images. (This is the current behavior for this label).

#### Tested with

- Build PR with no labels. [build](https://github.com/stackrox/stackrox/actions/runs/4866539671)
  Expect:
  - [x] - Default images are development builds, skips `-prerelease`, skips `-rcd`.
  - [x] - Install and verify [is_release = false](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5805/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1653550867892146176).
  - [x] - `/test gke-race-condition-qa-e2e-tests` - fails clearly declaring a
    [label is required](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5805/pull-ci-stackrox-stackrox-master-gke-race-condition-qa-e2e-tests/1653550867917312000).
- Build PR with `ci-build-prerelease`. [build](https://github.com/stackrox/stackrox/actions/runs/4867771400)
  Expect:
  - [x] - Default images are development builds, creates a `-prerelease`, skips `-rcd`. [push](https://github.com/stackrox/stackrox/actions/runs/4867771400/jobs/8680731612#step:24:88)
  - [x] - Deploy `-prerelease` and verify is_release = true.
- Build PR with `ci-release-build`. [build](https://github.com/stackrox/stackrox/actions/runs/4888392172)
  Expect:
  - [x] - Default images are release builds, skips `-prerelease`, skips `-rcd`.
  - [x] - Deploy and verify is_release = true.
- Build PR with `ci-build-race-condition-debug` & create a race condition. [force RACE](https://github.com/stackrox/stackrox/pull/2416/commits/cbac51700b56656efc3b136381b0d7de1ddc40a8)
  Expect:
  - [x] - Default images are development builds, skips `-prerelease`, creates a `-rcd`. [build](https://github.com/stackrox/stackrox/actions/runs/4888601961)
  - [x] - Install and verify is_release = false.
  - [x] - `/test gke-race-condition-qa-e2e-tests` - should find the image and
    the test should fail due to RACE in logs. Other tests should be fine despite
    the benign race condition. [-race failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5805/pull-ci-stackrox-stackrox-master-gke-race-condition-qa-e2e-tests/1654281006561103872)
- Build PR with `ci-race-tests` & create a race condition.
  Expect:
  - [x] - Default images are development builds, skips `-prerelease`, skips `-rcd`.
  - [x] - Install and verify is_release = false.
  - [x] - Default qa e2e tests fail due to being race builds & race condition. [test failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5805/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1654546502082629632)

### CODE REVIEW

**Review by porridge — APPROVED** [review]
Question:

> ci-race-tests - all images on a PR are built as race-condition-debug images (-race) and so all E2E tests run against release images.

I don't see the connection between the two parts of the sentence?

Request:
- please document the labels mentioned in the description, what images are built and what names they have, and which ones are used to run which tests

**Comment by gavin-stackrox** [comment]
> Question:
> 
> > ci-race-tests - all images on a PR are built as race-condition-debug images (-race) and so all E2E tests run against release images.
> 
> I don't see the connection between the two parts of the sentence?

Yeah. that last bit should be `-race` images. Updated the text.

> Request:
> 
> * please document the labels mentioned in the description, what images are built and what names they have, and which ones are used to run which tests

Will do.

**Comment by gavin-stackrox** [comment]
@janisz I'd appreciate your review on this change if you get a chance. Thanks.

**Pull request merged**
