### PR TITLE
Unskip some e2e SAC Tests on postres

### PR DESCRIPTION
**Pull request by janisz**
## Description

Some SAC functionality should work on postgres. The remaining tests are

- [ ] Verify that only namespace #sacResource is visible when using SAC
- [ ] Verify GetSummaryCounts using a token without access receives no results
- [ ] Verify GetSummaryCounts using a token with partial access receives partial results
- [ ] Verify Search on #category resources using the #tokenName token returns #numResults results
- [ ] Verify Autocomplete on #category resources using the #tokenName token returns #numResults results
- [ ] Verify using the #tokenName token with the #service service returns #numReturned results
- [ ] Verify search with SAC and token #tokenName yields the same number of results as restricted search
- [ ] Verify that SAC has the same effect as query restriction for network flows
- [ ] test role aggregation should not combine permissions sets

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2181** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2181" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/2181?utm_source=stack-comment).

**Review by rhybrillou — APPROVED** [review]

**Pull request merged**
