### PR TITLE
chore(deps): update junit2jira to v0.0.20

### PR DESCRIPTION
**Pull request by dcaravel**
## Description

Updates version of `junit2jira` to match latest: https://github.com/stackrox/junit2jira/releases/tag/v0.0.20

## Checklist
- [x] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
I added the j`ci-test-unit-processing` label. Assuming a test fails ;) then the failure should appear in [#acs-slack-ci-integration-testing](https://redhat.enterprise.slack.com/archives/C068WMY4SEQ) and a JIRA should be created/updated in the `RS-` project.
/retest

**Review by gavin-stackrox — APPROVED** [review]
Pre-approved. But I'd let the CI progress for a sanity check on the new `junit2jira` version.

**Review by janisz — APPROVED** [review]

**Comment by dcaravel** [comment]
/test gke-scanner-v4-tests
/test ocp-4-12-scanner-v4-tests

Perhaps one these will break.

**Comment by dcaravel** [comment]
Failed tests succeeded in generating the changed log line ([job](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/10770/pull-ci-stackrox-stackrox-master-ocp-4-12-qa-e2e-tests/1780741058695532544)):

```
time="2024-04-18T02:03:20Z" level=info msg="Found issue. Creating a comment..." ID=RS-647 summary="DefaultPoliciesTest / Verify policy Secure Spork  ssh  Port Exposed is triggered FAILED"
```
`ID=RS-647`

**Pull request merged**
