### PR TITLE
chore: remove unused migration store

### PR DESCRIPTION
**Pull request by janisz**
## Description

This migration was skipped we can remove unused code.
- #8621 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

Build is enough
 
### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by dhaus67 — APPROVED** [review]
LGTM, but let's also make sure someone from core-workflows approves.

**Review by theencee — APPROVED** [review]

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* **#9972** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/9972?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#10177** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10177?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#10169** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10169?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/10169?utm_source=stack-comment).

**Pull request merged**
