### PR TITLE
feat(helm): add priorityClassName settings in charts

### PR DESCRIPTION
**Pull request by ebisso**
## Description

This PR adds the option to configure a `priorityClassName` for pods in stackrox charts.
The main motivation is to be able to set the priority for `collector` because it is deployed as a DaemonSet.
This is important for DaemonSets as to provide a way for its pods to have higher priority over other pods, when scheduling on nodes that already reached capacity (to preempt and evict pods with lower priority).

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Added and ran helmtests

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by kurlov — APPROVED** [review]
Looks great!

**Comment by Maddosaurus** [comment]
Prow CI can be a bit temperamental at times, especially with regards to image availability. Please do check for any failing runs, though :smile:

**Comment by ebisso** [comment]
Hi @Maddosaurus,
thanks for the review!

I'm not sure if the tests are failing due to image availability like you pointed, or if it's an issue with my changes. Any help would be appreciated 😄 

I will open a PR in the docs repository for the parameter description. But here is what I had in mind: 

| Parameter | Description |
|---|---|
| collector.priorityClassName | Use this parameter to assign a Priority to Collector Pods. This is used to indicate the importance of the Collector Pods relative to other Pods. Set the value of this parameter to the name of an existing PriorityClass object in the cluster. |


Assuming a PriorityClass with the name `high-priority` is created in the cluster as in the example given in the following page:
[Pod Priority and Preemption](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/)

You can then install Secured Cluster Services using helm with parameter `--set collector.priorityClassName=high-priority`

**Comment by Maddosaurus** [comment]
Hi @ebisso,
thanks for staying on this! 
We're reworking bigger parts of our automation and CI, and it's rather hard to always ensure that it works for everyone.

To eliminate the question of image availability, I've created PR #9422 with your changes, to see if CI is happy.
The CI problems mainly relate to the ones prefixed `ci/prow`.
For example, the Style issues ([example run](https://github.com/stackrox/stackrox/actions/runs/7513388514/job/20569762910?pr=8566)) are something that fails because changes in the PR are needed. 
In this case, it looks like the YAML files have line ending `CRLF`, where we require `LF`. I do see that this linter error is not very intuitive, as it took me some digging to find that out 😅 Also, a single trailing whitespace was hiding in your yaml ([see this commit in the test PR](https://github.com/stackrox/stackrox/pull/9422/commits/b07864ec892a6b0c7fd23c6b877996f878b4f310#diff-e41761df0a8c77638559102105678f72759d493bc941a5a17e98478617f0a6c0L23)).
IIRC, prow tests will automatically exit early when other required checks (like Style) fail, so this might also already fix it.

**Comment by Maddosaurus** [comment]
Looks like all checks have passed in my PR test (#9422). I took the liberty of pushing the single commit to this PR that fixes the line endings in the test yamls.
Hope that's okay with you!

**Comment by Maddosaurus** [comment]
@ebisso Heads up: I've just pushed an empty commit to your fork to retrigger CI. I'm aiming for the required tests to pass so we can merge this PR :smile:

**Pull request merged**
