### PR TITLE
fix(gke-latest): Use private IP range for GKE service ips

### PR DESCRIPTION
**Pull request by robbycochran**
### Description
On [May 10, 2024](https://cloud.google.com/kubernetes-engine/docs/release-notes#May_10_2024), GKE versions 1.29 and later, began to use a GKE managed IP range 34.118.224.0/20 for services by default -- this eliminates the need for a secondary services [subnet](https://cloud.google.com/kubernetes-engine/docs/concepts/alias-ips#cluster_sizing_secondary_range_svcs). If only a range size is given to the `--services-ipv4-cidr` flag, GKE still uses the GKE-managed range to obtain the sub-range of addresses.

This PR specifies the subnet IP range so that ACS networking doesn't consider 34.118.224.X ips as external.

### User-facing documentation

- [ ] CHANGELOG is updated
- [ ] CHANGELOG update is not needed
- [ ] Documentation PR is created and linked above
- [ ] Documentation is not needed

### Testing

- [ ] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests
- [ ] contributed **no automated tests**
  

#### How I validated my change

/pragma: gke_cluster_version:latest

### CODE REVIEW

**Review by JoukoVirtanen — APPROVED** [review]
LGTM!

**Comment by robbycochran** [comment]
@vikin91 It was addressed here: https://github.com/stackrox/stackrox/pull/11934

**Pull request closed without merging**
