### PR TITLE
ROX-20554: Removing a CVE when updating a request

### PR DESCRIPTION
**Pull request by sachaudh**
## Description

This PR enables a user to remove CVEs from a vuln request using the modal

## Screen recording and Screenshots

https://github.com/stackrox/stackrox/assets/4805485/5e213e6c-3abd-4c75-b9b5-a3287b456ffa

Screenshot 2024-02-01 at 11 30 33 AM

### CODE REVIEW

**Comment by dvail** [comment]
@sachaudh @mansursyed 

When I was testing this out, the "Add/Remove" buttons were slightly confusing. I almost expected "Remove" to remove the item from the list, but it didn't, and was replaced with an "Add" button. Part of my brain thought "Why would we need to add the CVE if it is already in the list?"

What do you think about making it more explicit that the CVE is marked for removal/exclusion? I tried a handful of visuals that came to mind:
- Add a "disabled" background style to removed CVEs
- Change the text on the button (would "Include CVE"/"Exclude CVE" be better?)
- Add an inline, plain alert describing what removal means

image

We could also update the header to reflect the new CVE count, but that would definitely require moving some state around in the code.

**Comment by dvail** [comment]
Is the ability to update a request, remove a CVE, and approve intended to be part of this PR or a follow up? It looks like the initial update request correctly removes a CVE, but then once approved that CVE returns.

image
image
image
image
image

**Comment by sachaudh** [comment]
@dvail Good questions. I'll wait on @mansursyed about the UX suggestions you made. The only thing is I didn't want to do too much visually because it might be a bit overwhelming to the user. But making it clear, like you mentioned, is definitely what we want. The terms `Add` and `Remove` might also be confusing. I think using the term `Exclude` or `Include` might seem more correct when talking about selections. Disabling/fading things out might help too.

**Comment by sachaudh** [comment]
For the issue you're seeing with updating and approving, I'll look into that a bit more. Maybe we're not passing the correct CVEs in the API call 🤔

**Comment by sachaudh** [comment]
@charmik-redhat can you take a look at this issue @dvail mentioned? Looks like it might be a backend issue. Basically, if you create an exception request with 2 CVEs (A and B), approve the request, update the request (Remove A), and then approve the request again, it still shows both A and B.

**Comment by charmik-redhat** [comment]
> @charmik-redhat can you take a look at this issue @dvail mentioned? Looks like it might be a backend issue. Basically, if you create an exception request with 2 CVEs (A and B), approve the request, update the request (Remove A), and then approve the request again, it still shows both A and B.

This is a bug. You can create a ticket.

**Comment by sachaudh** [comment]
Thanks @charmik-redhat. Added it here https://issues.redhat.com/browse/ROX-22411.

**Comment by sachaudh** [comment]
@dvail @mansursyed Updated with suggestions. Decided to add an alert at the top instead of for each line item because it might look cluttered. Let me know what you think

 
Screenshot 2024-02-08 at 11 58 16 AM

**Review by dvail — APPROVED** [review]
The changes look good to me, I think having a single alert at the top is definitely better than having an alert per excluded CVE.

If all is good with @mansursyed , :shipit:

**Comment by alanonthegit** [comment]
@sachaudh @dvail I expressed some concerns with confusion still to @mansursyed with how colors present information at a glance that is counter to the state of a row and could be misinterpreted. He was going to explore an alternative I suggested but maybe he ran out of time. It's something we can improve upon and enhance as a general pattern in the UI maybe in 4.5, and it would do away with needing to have a callout banner to describe what is happening on the page, as the selection state per row would be more immediately obvious.

Also should the text on the banner say "You have 1 CVE included in your selection. Review and update your selections below"?

**Comment by dvail** [comment]
Thanks @alanonthegit , since this isn't shipping in 4.4 I think having a refinement for 4.5 would be a great idea. I added a ticket to the VM 2.0 GA Epic so we don't lose track of if. https://issues.redhat.com/browse/ROX-22482

**Pull request merged**
