### PR TITLE
tests(qa): enable retry on grpc

### PR DESCRIPTION
**Pull request by janisz**
## Description

This PR enables retrying in grpc as described in https://stackoverflow.com/a/76784188/1387612

- #4921
- https://github.com/stackrox/stackrox/pull/7636

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

```diff
index 818499cd31..3356470f92 100644
--- a/qa-tests-backend/src/main/groovy/services/BaseService.groovy
+++ b/qa-tests-backend/src/main/groovy/services/BaseService.groovy
@@ -28,8 +28,8 @@ import util.Keys
 @Slf4j
 class BaseService {
 
-    static final String BASIC_AUTH_USERNAME = Env.mustGetUsername()
-    static final String BASIC_AUTH_PASSWORD = Env.mustGetPassword()
+    static final String BASIC_AUTH_USERNAME = "admin"
+    static final String BASIC_AUTH_PASSWORD = "pass"
 
     static final EMPTY = EmptyOuterClass.Empty.newBuilder().build()
 
@@ -130,7 +130,7 @@ class BaseService {
             def sslContext = sslContextBuilder.build()
 
             transportChannel = NettyChannelBuilder
-                    .forAddress(Env.mustGetHostname(), Env.mustGetPort())
+                    .forAddress("localhost", 8000)
                     .defaultServiceConfig(getServiceConfig())
                     .maxRetryAttempts(3)
                     .enableRetry()
@@ -153,14 +153,14 @@ class BaseService {
         return ["methodConfig": [
                 [
                         "name"       : [
-                                ["service": "$AuthProviderServiceGrpc.SERVICE_NAME"],
+                                ["service": "$AuthProviderServiceGrpc.SERVICE_NAME".toString()],
                         ],
                         "timeout"    : "30.0s",
                         "retryPolicy": [
                                 "maxAttempts"         : "3",
                                 "initialBackoff"      : "1s",
                                 "maxBackoff"          : "10s",
-                                "backoffMultiplier"   : 2,
+                                "backoffMultiplier"   : "1",
                                 "retryableStatusCodes": ["UNAVAILABLE", "UNKNOWN"]
                         ]
                 ]
diff --git a/qa-tests-backend/src/main/groovy/util/Env.groovy b/qa-tests-backend/src/main/groovy/util/Env.groovy
index a04a71cf6b..0016cf1543 100644
--- a/qa-tests-backend/src/main/groovy/util/Env.groovy
+++ b/qa-tests-backend/src/main/groovy/util/Env.groovy
@@ -35,7 +35,7 @@ class Env {
     // only has secured-cluster deployed and connects to a remote central
     static final ONLY_SECURED_CLUSTER = System.getenv("ONLY_SECURED_CLUSTER") ?: "false"
 
-    private static final Env INSTANCE = new Env()
+    private static final Env INSTANCE = null
 
     static String get(String key, String defVal = null) {
         return INSTANCE.getInternal(key, defVal)
diff --git a/qa-tests-backend/src/test/groovy/GrpcRetryTest.groovy b/qa-tests-backend/src/test/groovy/GrpcRetryTest.groovy
index a09b9650aa..1dd702c5b7 100644
--- a/qa-tests-backend/src/test/groovy/GrpcRetryTest.groovy
+++ b/qa-tests-backend/src/test/groovy/GrpcRetryTest.groovy
@@ -1,2 +1,15 @@
-class GrpcRetryTest {
+import io.stackrox.proto.api.v1.AuthProviderServiceGrpc
+import io.stackrox.proto.storage.AuthProviderOuterClass
+
+import services.AuthProviderService
+
+import spock.lang.Specification
+
+class GrpcRetryTest extends Specification {
+    def "will it retry"() {
+        when:
+        def provider = AuthProviderService.getAuthProvider("admin")
+        then:
+        provider
+    
```

I used above code to hit 
```
python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [24/Jun/2024 19:24:59] code 400, message Bad request syntax ('\x16\x03\x03\x01\x89\x01\x00\x01\x85\x03\x03jG¡oqÎÝ\x08\x04özÂ\x9f9\rø:0Ò`ÙµYFKì^¯8;}Ñ j\x9eÛ¿\x9b®\x8b½\x04\x0b\x9b¨\x08i\x88=÷ãvs8n\x88ÎB¹Ë')
127.0.0.1 - - [24/Jun/2024 19:24:59] "
ø:0Ò`ÙµYFKì^¯8;}Ñ jÛ¿®½
                           i=÷ãvs8nÎB¹Ë" 400 -
127.0.0.1 - - [24/Jun/2024 19:25:00] code 400, message Bad request version ('Ó@A\x97\x129\x82Í\x9c\x03ò\x88T£¸gf©!dÂä×Þ\x93ôº\x07a]¯\x86\x00\x12À+À/À,À0Ì©Ì¨\x13\x01\x13\x02\x13\x03\x01\x00\x01*\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00')
127.0.0.1 - - [24/Jun/2024 19:25:00] "
=YÔ,&FwýZKìstÜÕÝ({)çJÙÛØ Ó@A9ÍòT£¸gf©!dÂä×Þôºa]¯À+À/À,À0Ì©Ì¨*" 400 -
^[[?62;c^C
Keyboard interrupt received, exiting.
```
Without config it looks like this an takes
```
python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [24/Jun/2024 19:27:11] code 400, message Bad request syntax ('\x16\x03\x03\x01\x89\x01\x00\x01\x85\x03\x03¦µ)\\ul\x9fD£Ù\x07¢xî2Å\x0e\x93´s\x9cDIf«âR"Þ`\x1c\x9d ge\x0b\x9dózO\x90Ù»èÒþó~³Ó\x11\x9b¶_uw¶mµ\x0cÎ¬\x89M\x7f\x00\x12À+À/À,À0Ì©Ì¨\x13\x01\x13\x02\x13\x03\x01\x00\x01*\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00')
127.0.0.1 - - [24/Jun/2024 19:27:11] "
¦µ)\ulD£Ù¢xî2Å´sDIf«âR"Þ` ge
                                   ózOÙ»èÒþó~³Ó¶_uw¶mµ
                                                          Î¬MÀ+À/À,À0Ì©Ì¨*" 400 -
^C

```

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by stehessel** [comment]
See https://github.com/stackrox/stackrox/pull/7636 for some of my previous hacking on this issue.

**Comment by gavin-stackrox** [comment]
Could this be tested with a response delay (or some such) on the central side?

**Comment by stehessel** [comment]
I'm not sure I understand your test. I'd would suggest to test the gRPC retry in the following way:
* Make Central always return `UNAVAILABLE` gRPC error code on something like `ScanImage`.
* Run a test with `ScanImage`.
* Log the client attempts and verify that they retry on `UNAVAILABLE`.

I also think that we should make the retry behavior opt-out in case a service method is not safe to retry.

**Pull request closed without merging**
