### PR TITLE
ROX-21620: publish opensource instead of stackrox.io helm charts

### PR DESCRIPTION
**Pull request by GrimmiMeloni**
## Description

Stops generating and publishing stackrox.io based helmcharts.
Going forward, the opensource flavor is published to stackrox/helmcharts.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] <strike>Unit test and regression tests added</strike>
- [X] Evaluated and added CHANGELOG entry if required
- [ ] <strike>Determined and documented upgrade steps</strike>
- [ ] <strike>Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))</strike>

If any of these don't apply, please comment below.

### Here I tell how I validated my change

Used a "dry run" of a release (curtesy of @tommartensen) to produce an [example release-artifacts PR](https://github.com/stackrox/release-artifacts/pull/122).
 
The interesting artifact is the [helm repo archive](https://github.com/stackrox/release-artifacts/blob/4276a90f8c55a0b07a7112fe0e46b957b5ab8f41/helm-charts/opensource/stackrox-central-services-400.3.0-817-g1588c87071.tgz
) produced. I verified this contains the opensource charts, by looking at the `internal/defaults.yaml`'s image repository and confirming it now points to quay.io.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by mclasmeier — APPROVED** [review]
Looks like the correct fix to me!

Question: There are still several references to `stackrox.io` in the codebase -- shall we get rid of them within this ticket as well?

Just looking at the Helm charts, for example:

```
stackrox-secured-cluster/README.md.htpl
253:|`collector.slimMode`| Specify `true` if you want to use a slim Collector image for deploying Collector. Using slim Collector images and EBPF collection method requires Central to provide the matching eBPF probe. If you are running the StackRox Kubernetes Security Platform in offline mode and use EBPF collection method, you must download a kernel support package from [stackrox.io](https://install.stackrox.io/collector/support-packages/index.html) and upload it to Central for slim Collectors to function. Otherwise, you must ensure that Central can access the online probe repository hosted at https://collector-modules.stackrox.io/.|`false` |

stackrox-secured-cluster/values-public.yaml.example
310:#  # method, you must download a kernel support package from [stackrox.io](https://install.stackrox.io/collector/support-packages/index.html)

stackrox-central/values-public.yaml.example.htpl
48:#   # This can be just a registry hostname such as `stackrox.io`, or a registry hostname with

stackrox-secured-cluster/internal/defaults/50-images.yaml.htpl
35:    registry: {{ if or (eq ._rox.image.registry "stackrox.io") (eq ._rox.image.registry "registry.connect.redhat.com") }}collector.stackrox.io{{ else }}{{ ._rox.image.registry }}{{ end }}

```

And this is from the top-level README:
```
48:For alternative ways, stop by our Community Hub [stackrox.io](https://www.stackrox.io/).
50:For event updates, blogs and other resources follow the StackRox community site at [stackrox.io](https://www.stackrox.io/).
52:For the StackRox [Code of Conduct](https://www.stackrox.io/code-conduct/).
558:docker run -i --rm stackrox.io/main:<tag> interactive > k8s.zip
588:docker run -i --rm stackrox.io/main:<tag> interactive > openshift.zip
```

Probably there are even more, I didn't look carefully.

**Comment by GrimmiMeloni** [comment]
> Question: There are still several references to `stackrox.io` in the codebase -- shall we get rid of them within this ticket as well?

I had a quicklook. My IDE gave me 900++ matches for stackrox.io in the codebase. At least my knowledge is too limited for a targeted cleanup.

**Comment by mclasmeier** [comment]
> > Question: There are still several references to `stackrox.io` in the codebase -- shall we get rid of them within this ticket as well?
> 
> I had a quicklook. My IDE gave me 900++ matches for stackrox.io in the codebase. At least my knowledge is too limited for a targeted cleanup.

Then I would suggest to merge this as is and either keep the original ticket open (with updated scope) or create a follow-up ticket for the doc changes.

**Comment by GrimmiMeloni** [comment]
@mclasmeier merged here, and created https://issues.redhat.com/browse/ROX-21937

**Pull request merged**
