### PR TITLE
ROX-11058: fix: remove deprecated flag license

### PR DESCRIPTION
**Pull request by Zulbukharov**
## Description

Fixes: #3059
Removed deprecated flag `license` with references to it.

## Checklist
- [x] Removed [roxctl/central/license](https://github.com/stackrox/stackrox/tree/master/roxctl/central/license) folder
- [x] Removed all references of the command (such as [roxctl/central/central.go](https://github.com/stackrox/stackrox/blob/master/roxctl/central/central.go) and [roxctl/help/help.properties](https://github.com/stackrox/stackrox/blob/master/roxctl/help/help.properties))

## Testing Performed

Executed `go test ./...` under `roxctl` directory. All tests are pased

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Review by Maddosaurus — APPROVED** [review]
That looks good to me! Thanks for the PR!
QQ: I don't see any tests failing, but did we take a look whether there are any tests left that rely on/test this functionality?

**Review by dhaus67 — APPROVED** [review]

**Comment by Zulbukharov** [comment]
> That looks good to me! Thanks for the PR!
> QQ: I don't see any tests failing, but did we take a look whether there are any tests left that rely on/test this functionality?

hey, I launched tests under `roxctl` directory, all I found is some `deprecated` flags files at https://github.com/stackrox/stackrox/blob/0903481b62709d0f5c1a5e0df7fba54a4061cf4d/roxctl/common/flags/license.go#L5 which is not covered by tests. Should I remove them?

**Comment by Maddosaurus** [comment]
@Zulbukharov well spotted!
Please do remove this mention of license as well, yes!

**Comment by Zulbukharov** [comment]
hi, @Maddosaurus can you help me figuring out the place where the ci build fails?

Tracing the message: `Certificate validation error: x509: certificate signed by unknown authority` brings me to https://github.com/stackrox/stackrox/blob/56bd157e48824474fdf8b2f8b5e0e58c66f863fe/roxctl/common/tls.go#L33 file.

**Comment by Maddosaurus** [comment]
@Zulbukharov Thanks for following the trail! We're also investigating this CI failure. ATM, this looks like a flake, so I'll go ahead an merge your PR :)

**Pull request merged**
