### PR TITLE
Handle null namespace in Kubernetes client

### PR DESCRIPTION
**Pull request by janisz**
## Description

In next version of fabric8 the `inNamespace(null)` will cause NPE.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3047** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3047" target="_blank">Graphite</a> 
    * **PR #3048** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3048" target="_blank">Graphite</a>  👈
      * **PR #3049** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3049" target="_blank">Graphite</a> 
        * **PR #3050** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3050" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3048?utm_source=stack-comment).

**Review by gavin-stackrox — APPROVED** [review]
LGTM assuming CI passes

**Comment by janisz** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3048?utm_source=stack-comment).


Job Reference: EWf7JXZwBVjaRD9hhYFV

**Pull request merged**
