### PR TITLE
ROX-9993 fix test case

### PR DESCRIPTION
**Pull request by sbostick**
## Description

https://issues.redhat.com/browse/ROX-9993 — Test case failure in _LocalQaTestProps_

* Updated the expected value to the actual value observed empirically in nightly testing (correctness)
* Disabled the case the case since it isn't actually useful

## Testing Performed

* Default CircleCI PR tests

### CODE REVIEW

**Review by gavin-stackrox — COMMENTED** [review]
What about a
`@IgnoreIf({ Env.IN_CI })`
at the class level? This is only meant to run to verify qa-test-settings.properties files which should only be local runs.

**Comment by sbostick** [comment]
> What about a `@IgnoreIf({ Env.IN_CI })` at the class level? This is only meant to run to verify qa-test-settings.properties files which should only be local runs.

Thanks, much better that way. I didn't find an example use of the decorator at class level in our source, but https://spockframework.org/spock/docs/1.0/extensions.html seems to indicate that these method decorators apply to method and class level, at least the unconditional variant `@Ignore`. Trying it now.

**Comment by sbostick** [comment]
Confirmed working at class level:
```
cd qa-tests-backend
export CI=true
gradle test --tests='LocalQaPropsTest'
```

> * What went wrong:
> Execution failed for task ':test'.
> > No tests found for given includes: [LocalQaPropsTest](--tests filter)

**Review by gavin-stackrox — APPROVED** [review]
LGTM

**Pull request merged**
