### PR TITLE
ROX-26151: Pin related images in operator bundle

### PR DESCRIPTION
**Pull request by mclasmeier**
### Description

Pin all the related images.

This is purely a CI change.

### User-facing documentation

- [x] CHANGELOG update is not needed
- [x] documentation PR is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [x] CI results are inspected

#### Automated testing

Just a CI change.

### CODE REVIEW

**Comment by mclasmeier** [comment]
FYI, looking at the Konflux UI for the operator-bundle-build PipelineRun one can conveniently obtain an overview of the structure of the task graph.

image

**Review by porridge — APPROVED** [review]
My only worry is: how do we remember to mention an image here once we add a new component in the future? 🤔

**Comment by mclasmeier** [comment]
> My only worry is: how do we remember to mention an image here once we add a new component in the future? 🤔

Hoping that we could catch that using some installation e2e tests.

**Comment by tommartensen** [comment]
> My only worry is: how do we remember to mention an image here once we add a new component in the future? 🤔

@mclasmeier @porridge I quickly added a new section to our docs explaining how to add a new component, including adding the things ™ to the operator bundle pipeline:

https://spaces.redhat.com/pages/viewpage.action?pageId=407312060#HowtoeverythingKonflux/RHTAPforRHACS-Howtoaddanewcomponent

**Pull request merged**
