### PR TITLE
:rotating_light: G110 gosec rule enabled

### PR DESCRIPTION
**Pull request by bgalek**
## Description

G110 check enabled in gosec config

### CODE REVIEW

**Comment by janisz** [comment]
{pkg/tar/tar.go:107:16: G110: Potential DoS vulnerability via decompression bomb  : G110: Potential DoS vulnerability via decompression bomb

**Review by janisz — CHANGES_REQUESTED** [review]
CI is failing

**Comment by bgalek** [comment]
Yeah, I'll check it out

**Comment by porridge** [comment]
Any updates @bgalek ?

**Pull request closed without merging**
