### PR TITLE
[ROX-12294] : Disable debug dump and diagnostic bundle endpoints when ROX_MANAGED_CENTRAL env var is set to true

### PR DESCRIPTION
**Pull request by charmik-redhat**
## Description

Disabled debug dump and diagnostic bundle for Managed services preview

## Checklist
- [ ] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

Get debug dump and diagnostic bundle with ROX_MANAGED_CENTRAL env set and verify that they fail.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by misberner — CHANGES_REQUESTED** [review]
This will certainly get the job done, but I am very honestly not a fan of having managed services check logic pop up in fairly random places. If we have to change behavior, I would much rather expose disabling debug info as a more general-purpose knob rather than making this behavior depend on managed services setting.

We can set arbitrary env vars differently for managed centrals, so we can just introduce a boolean setting `ROX_DISABLE_DEBUG_LOGS`. WDYT?

**Comment by misberner** [comment]
See https://github.com/stackrox/stackrox/pull/3024#discussion_r967130719 for related thoughts.

Also, is there a plan to remove RBAC bindings in a follow-up?

**Comment by charmik-redhat** [comment]
Closing this PR for now since we'll be releasing MS service preview with v3.72. For limited availability, I will figure out how to keep parts of diagnostics and exclude just the managed central's cluster specific info.

**Pull request closed without merging**
