### PR TITLE
ROX-14974: Tune waitForEdgeUpdate time

### PR DESCRIPTION
**Pull request by Maddosaurus**
## Description

Tuning for test flake in `Verify cluster updates can block flow connections from showing` (`NetworkFlowTest.groovy`)

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Comment by Maddosaurus** [comment]
[This test run](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/4802/pull-ci-stackrox-stackrox-master-gke-kernel-qa-e2e-tests/1630858897881305088) failed for the syslog notifier, not for Network Flow

**Review by vikin91 — APPROVED** [review]
I see that this changes the assertion wait time from 20 to 30s. The changes are of course perfectly fine, but I am curious why adding 10s is enough here (e.g., why not adding 20 or 30s?)

**Comment by Maddosaurus** [comment]
@vikin91 As far as I have understood the test, `waitForEdgeUpdate` used to have a 20 second buffer, but our NetworkGraphUtil would only update results every `NETWORK_FLOW_UPDATE_CADENCE_IN_SECONDS`.
My guess is that this produced flakes when the update wasn't done in time. 

I increased the time only by 10 seconds  to strike a balance between test execution time and flakyness.
We could err on the safe side and increase it, for example even to 2*update cadence, but I was hesitant to do this without further discussion or feedback.

**Pull request merged**
