### PR TITLE
wip(helm): support pod priority

### PR DESCRIPTION
**Pull request by RyuS3ki**
## Description

- Central
  - Add optional priorityClass resource
  - Add podPriority support for deployment
- Secured cluster
  - Add optional priorityClass resource
  - Add podPriority support for all three deployments

@Maddosaurus 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user-facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Central services:
```
$ cd pkg/helm/charts/tests/centralservices
$ go test -v
[...]
PASS
ok  	github.com/stackrox/rox/pkg/helm/charts/tests/centralservices	38.875s
```

Secured cluster:
```
$ cd pkg/helm/charts/tests/securedclusterservices
$ go test -v
[...]
PASS
ok  	github.com/stackrox/rox/pkg/helm/charts/tests/securedclusterservices	13.373s
```

### CODE REVIEW

**Comment by Maddosaurus** [comment]
That you for tagging me on the draft PR!
Looking at this, I'm happy to see that the tests are passing, but I also would like to verify the changes manually.
Hence the question: 
How can these changes best be tested? What combination of values should I provide and how can I observe that the priorityClass is working as intended?

**Comment by RyuS3ki** [comment]
Sorry for the late reply @Maddosaurus , added a few more changes as I forgot to add the ability to specify a priority class name.

Here's an example of the values that could be used to test:

- Central
```yaml
priorityClass:
  enabled: true
  name: stackrox-test
  value: 10000 #something big for high priority
  globalDefault: false
  preemptionPolicy: Never # priority for stackrox pods over other queued pods, but not preempting any to get resources
central:
  podPriority:
    enabled: true
    className: stackrox-test
``` 

- Secured cluster
```yaml
priorityClass:
  enabled: true
  name: stackrox-test
  value: 10000 #something big for high priority
  globalDefault: false
  preemptionPolicy: Never # priority for stackrox pods over other queued pods, but not preempting any to get resources
sensor:
  podPriority:
    enabled: true
    className: stackrox-test
admissionControl:
    enabled: true
    className: stackrox-test
collector:
    enabled: true
    className: stackrox-test
```

**Comment by Maddosaurus** [comment]
We've had a little hiccup with our CI some days ago, so let's see if we can get more tests to pass now :) 
If I cannot trigger the CI re-run, please feel free to comment with `/retest`, that should do the trick
([like I did here](https://github.com/stackrox/stackrox/pull/4885#issuecomment-1455812889))

**Comment by Maddosaurus** [comment]
@RyuS3ki Hey, we've had multiple people over in the CNCF Slack ask about Pod Priorities. Any updates on your side?
Could you do a rebase and kick of a new round of CI tests with a push?

**Comment by Maddosaurus** [comment]
@RyuS3ki Checking in: Are you still interested in going forward with this PR?

**Comment by RyuS3ki** [comment]
Hi @Maddosaurus yeah, sorry I've been offline for some time. What should be the next steps?

**Comment by RyuS3ki** [comment]
Just read your previous comment, I'll rebase

**Comment by Maddosaurus** [comment]
@RyuS3ki Would you mind having a look at the rebase? 5000+ changed files seems a bit excessive. 
The branch has been older, but by rebasing against the latest master, I would have expected the PR to still be rather small.

**Comment by Maddosaurus** [comment]
As this PR has been dormant a really long time, I'll be closing it for now.
If you'd like to continue work on this, please do let us know here, we can reopen or start a new one at any time :)

**Pull request closed without merging**
