### PR TITLE
chore(deps): bump google.golang.org/grpc to 1.66.3

### PR DESCRIPTION
**Pull request by rhybrillou**
### Description

change me!

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

change me!

### CODE REVIEW

**Review by mtodor — APPROVED** [review]
Let's just check if UI e2e tests are working before merging.

**Comment by rhybrillou** [comment]
grpc is already bumped to a higher version.

**Pull request closed without merging**
