### PR TITLE
chore: add a reminder for the unconventional flag behavior

### PR DESCRIPTION
**Pull request by parametalol**
### Description

Commented a region of feature flags definitions.

### User-facing documentation

(*must be* 2 items and both *must be* checked)

- [x] CHANGELOG update is not needed
- [x] Documentation is not needed

### Testing

- [x] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [x] contributed **no automated tests**
  
Only added comments in the code.

#### How I validated my change

Peer review.

### CODE REVIEW

**Comment by connorgorman** [comment]
Not sure, if I'm being added automatically or manually, but since I no longer work on the project, if I could be removed from the reviewers list that would be great.

**Review by janisz — APPROVED** [review]
We can go even further and move them to a separated file `unconventional_list.go` and prevent changes to this file with a misc check

**Review by rhybrillou — APPROVED** [review]

**Pull request closed without merging**
