### PR TITLE
ROX-11670 Delete orphaned dashboard code and dependencies

### PR DESCRIPTION
**Pull request by dvail**
## Description

Deletes app-level code from the old dashboard, as well as other dead code paths referenced by this code.

This also deletes the only usages of the following dependencies:
- react-slick
- recharts

### Follow ups
- Move the new dashboard code from `./Dashboard/PatternFly` to
  `./Dashboard`. (Not included in this PR to maintain a better git history.)
- Close dependabot PRs for the removed dependencies

## Checklist
- [ ] Investigated and inspected CI test results

## Testing Performed

Starting from `Containers/Dashboard/DashboardPage.js`, recursively view usages of each import, and delete all files that are only imported in the target.

For dependencies `recharts` and `react-slick`, also do a project wide search for those terms, returning zero results.

Spot test checking of the new dashboard, as well as older dashboards on other pages ("Compliance", "Config Mgmt", "Vuln Mgmt").

Unit and e2e tests.

### CODE REVIEW

**Comment by dvail** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3065** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3065" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3065?utm_source=stack-comment).

**Review by pedrottimark — APPROVED** [review]
Thank you for thinking about git history when you planned the steps.

**Pull request merged**
