### PR TITLE
feat(qa): Update IIBs to build v4.4.0-11 & re-enable few tests on P/Z

### PR DESCRIPTION
**Pull request by pratham-m**
This PR updates index images (used for ACS deployment via downstream builds) for `ppc64le` and `s390x` platforms. Also re-enables tests disabled in #10202.

### CODE REVIEW

**Comment by pratham-m** [comment]
@robbycochran @gavin-stackrox can you kindly review this PR?

**Comment by gavin-stackrox** [comment]
> @robbycochran @gavin-stackrox can you kindly review this PR?

@pratham-m are you OK with the test failures?

**Comment by pratham-m** [comment]
> > @robbycochran @gavin-stackrox can you kindly review this PR?
> 
> @pratham-m are you OK with the test failures?

Yes. only `DefaultPoliciesTest` is failing due to recent changes in code to use non-MA image. I am working to add fix for the same.

**Review by gavin-stackrox — APPROVED** [review]

**Comment by pratham-m** [comment]
Merging. `DefaultPoliciesTest` will be pushed separately.

**Pull request merged**
