### PR TITLE
ROX-18485: Emit administration events from reprocessor

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

This PR enables the reprocessor package to emit administration events.

The package has previously been prepared to use structured logging (i.e. `Errorw/Warnw`) where applicable, the only thing missing is to enable the logger to also send administration events.

Created a helper option within Central which calls the `stream.Singleton()`, so that all packages within Central may import `events.EnableAdministrationEvents()` and use-as-is, without requiring additional dependencies to `pkg/administration/event/stream`.

Additionally, fixed a bug within the log converter:
When more than one field was given which specifies a resource, we previously printed a warning. This might be cumbersome, since there are log statements that are complementary.

As an example, when node scanning failed, the structured log within the reprocessor may include the node ID and its associated cluster.

Instead of printing a warning and taking the latter found resource type, we should instead follow a more structured approach:
Remove the duplicate resource field for the structured log statement and panic in dev builds / write a log in release builds when duplicate resource fields are set.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

1. Deploy central and enable the `ROX_ADMINISTRATION_EVENTS` feature flag.
```bash
k set env -n stackrox deploy/central ROX_ADMINISTRATION_EVENTS=true
```
2. Generate image scanning failures. You may do so by deploying a _private_ image which cannot be scanned by Central:
```bash
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: administration-event
  name: administration-event
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administration-event
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: administration-event
    spec:
      containers:
      - image: quay.io/rhacs-eng/qa:nginx-unprivileged-1.15.12
        name: administration-event
EOF
```
3. Observe within the logs that an image scanning error _does_ exist.

4. Query the administration events API to see that the event has been created successfully:
```bash
roxcurl /v1/administration/events | jq
```
```json
{
  "events": [
    {
      "id": "51bfa739-8434-5f73-88f3-8034b72a51ee",
      "type": "ADMINISTRATION_EVENT_TYPE_LOG_MESSAGE",
      "level": "ADMINISTRATION_EVENT_LEVEL_ERROR",
      "message": "Error enriching image",
      "hint": "An issue occurred scanning the image. Please ensure that:\n- Scanner can access the registry.\n- Correct credentials are configured for the particular registry / repository.\n- The scanned manifest exists within the registry / repository.",
      "domain": "Image Scanning",
      "resourceType": "Image",
      "resourceId": "gke.gcr.io/gke-metrics-agent-windows:1.10.0-gke.0@sha256:070fbb7ce1b627a38174c9f7886b2adbce7824b7dfaf2c0bff2d0fb7bb5fc0c0",
      "numOccurrences": "1",
      "lastOccurredAt": "2023-09-16T00:05:53.756540639Z",
      "createdAt": "2023-09-16T00:05:53.756540639Z"
    }
  ]
}
```

5. Let this run for some time (to ensure we get a couple of reprocessing loops) and observe the events within the API:
```bash
roxcurl /v1/administration/events | jq
```
```json
{
  "events": [
    {
      "id": "51bfa739-8434-5f73-88f3-8034b72a51ee",
      "type": "ADMINISTRATION_EVENT_TYPE_LOG_MESSAGE",
      "level": "ADMINISTRATION_EVENT_LEVEL_ERROR",
      "message": "Error enriching image",
      "hint": "An issue occurred scanning the image. Please ensure that:\n- Scanner can access the registry.\n- Correct credentials are configured for the particular registry / repository.\n- The scanned manifest exists within the registry / repository.",
      "domain": "Image Scanning",
      "resourceType": "Image",
      "resourceId": "gke.gcr.io/gke-metrics-agent-windows:1.10.0-gke.0@sha256:070fbb7ce1b627a38174c9f7886b2adbce7824b7dfaf2c0bff2d0fb7bb5fc0c0",
      "numOccurrences": "13",
      "lastOccurredAt": "2023-09-18T00:04:36.559781869Z",
      "createdAt": "2023-09-16T00:05:53.756540639Z"
    }
  ]
}
```
### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7812** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7812" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7812?utm_source=stack-comment).

**Review by stehessel — APPROVED** [review]

**Comment by stehessel** [comment]
> I'm wondering if we should have allowed a list of resources in events. Then we would not need the priority algorithm and could just attach all relevant resources to the event.

For posterity, we decided to not extend the API with a resource list because a) it's not clear that is needed and b) it would not be clear how to do the deduping. Instead, we now require that no multiple resources are present in the log context, and enforce this by a panic in the debug build.

**Pull request merged**
