### PR TITLE
fix(cvss): improve CVSS vector parsing

### PR DESCRIPTION
**Pull request by RTann**
## Description

We have seen a few instances where we get logs about invalid CVSS vectors but with very limited information. This change improve our CVSS processing by:

1. Use a library which already implements this and account for non-base metrics, which is something we missed in the past
2. Log the entire invalid CVSS vector instead of just the single invalid metric, so we have an idea of what the vector looks like

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

### Here I tell how I validated my change

CI is sufficient, as we already have unit tests

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by vikin91 — COMMENTED** [review]
The idea is great, but unit tests are unhappy

**Comment by RTann** [comment]
> The idea is great, but unit tests are unhappy

Good, they should be. They were bad tests it seems. Will fix

**Comment by RTann** [comment]
@vikin91 unit tests seem happy again and the other test failures seem unrelated

**Review by vikin91 — APPROVED** [review]
Thanks!

Sensor integration tests failure is unrelated - we have it on Maple's radar.

**Pull request merged**
