### PR TITLE
ROX-13668: Add a simple RHCOS e2e test

### PR DESCRIPTION
**Pull request by vikin91**
## Description

This PR adds e2e tests for RHCOS node scanning.

## Checklist
- [x] Investigated and inspected CI test results
- [x] ~Unit~ e2e test and regression tests added

### N/A
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- [x] Executed the test locally against a remote cluster `./gradlew test --tests=NodeInventoryTest`
- [x] CI - checked that this test is executed

1. GKE [Link](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5690/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1648586176778473472/artifacts/gke-qa-e2e-tests/stackrox-e2e/build-log.txt)
```
NodeInventoryTest > Verify node inventories and their scans STANDARD_OUT
    09:36:19 | INFO  | NodeInventoryTest         | Starting testcase
    09:36:19 | INFO  | NodeInventoryTest         | Node gke-rox-ci-qa-e2e-test-1-default-pool-c74e2862-9c1r scan contains 4 components
    09:36:19 | INFO  | NodeInventoryTest         | Node gke-rox-ci-qa-e2e-test-1-default-pool-c74e2862-qh9v scan contains 4 components
    09:36:19 | INFO  | NodeInventoryTest         | Node gke-rox-ci-qa-e2e-test-1-default-pool-c74e2862-dhf8 scan contains 4 components
    09:36:20 | INFO  | NodeInventoryTest         | Ending testcase

NodeInventoryTest > Verify node inventories and their scans PASSED
```

2. OCP [Link to build artifacts](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/stackrox_stackrox/5690/pull-ci-stackrox-stackrox-master-ocp-4-10-qa-e2e-tests/1648943964989952000/artifacts/qa-e2e-tests/stackrox-e2e/build-log.txt)

```
NodeInventoryTest > Verify node inventories and their scans STANDARD_OUT
    09:08:15 | INFO  | NodeInventoryTest         | Starting testcase
    09:08:15 | INFO  | NodeInventoryTest         | Node ip-10-0-175-225.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-177-243.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-214-218.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-172-183.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-240-86.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-154-97.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Node ip-10-0-226-5.us-west-1.compute.internal scan contains 499 components
    09:08:16 | INFO  | NodeInventoryTest         | Ending testcase

NodeInventoryTest > Verify node inventories and their scans PASSED
```

### CODE REVIEW

**Review by Maddosaurus — APPROVED** [review]
LGTM!

Question: What are we exactly querying with the `node.getScan()` call in line 34?
If we are querying the Node Scanner here, we would not see Vulns, as they are only added by the Scanner container, when the Node Scan result has passed through Central, correct?

**Comment by vikin91** [comment]
> LGTM!
> 
> Question: What are we exactly querying with the `node.getScan()` call in line 34? If we are querying the Node Scanner here, we would not see Vulns, as they are only added by the Scanner container, when the Node Scan result has passed through Central, correct?

We are querying the `storage.NodeScan` object attached to the `storage.Node`. All these are queries to the Central DB and they run over the Central API

**Comment by vikin91** [comment]
The failures of `tests/metadata_test.go` are unrelated but still strange, I think there is a bug in the test, because Central returns `release` (correct) but we expect `development` (incorrect due to the flag `ci-release-build`)

**Comment by jvdm** [comment]
@vikin91 What is this test resilience to temporary issues between Central and Scanner when the first node inventory arrives, and no Components exist in the DB yet? I am unfamiliar with how E2E spins up the clusters, but I am worried that the tests might fail if inventories arrive too soon before Scanner is ready.

**Comment by vikin91** [comment]
@jvdm yeah, this test turned out to be flaky - some fixes here https://github.com/stackrox/stackrox/pull/5782

I would need to handle the situation when scanner is unavailable - will see if the retries from #5782 are enough for this

**Pull request merged**
