### PR TITLE
ROX-20847: Add "Internal entities" to the network graph

### PR DESCRIPTION
**Pull request by vikin91**
## Description

This PR divides the flows that connect "External Entities" on the Network Graph into two groups:
- External Entities - for all flows that leave the cluster
- Internal Entities - for all flows internal to the cluster

Before this PR, all flows for which Sensor was unable to identify the container were treated as external entities. This was mostly incorrect and lead to many customer issues.

The decision whether a flow destination/source is internal/external is done based on the information passed from Collector. If Collector reports a concrete IP, the the entity is considered internal, if Collector reports "255.255.255.255", the the entity is considered external.

Here, we add the following:
- Debug log in Sensor that would print the full IP for all internal entities that have flows
- New UI entity on the graph "Internal Entities" to group the flows that do not leave cluster - see https://github.com/stackrox/stackrox/pull/9460 for screenshots

⚠️ ⚠️ ⚠️ The UI changes have been already reviewed as part of https://github.com/stackrox/stackrox/pull/9460

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

### Here I tell how I validated my change

- [x] Unit tests are available (but they cannot fully cover this change)
- [x] Testing manually on a demo cluster, as this involves changes in the UI
- [ ] e2e tests should be added (in a followup) 

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by vikin91** [comment]
I rebased against a fresh master after merging the UI changes.
I also removed the traces of 	`Unknown Internal Entities`.
Once CI is ready, I will start manual tests and will open that PR for a review.

**Comment by dvail** [comment]
The failures in the e2e UI test job are unrelated and fixed on `master`, so don't worry about those.

**Comment by vikin91** [comment]
@dvail could you help me check if the e2e UI test failures are caused by this PR? 
They look more to be caused by compliance and configuration manager dashboards, but I want to be sure.

**Comment by vikin91** [comment]
> The failures in the e2e UI test job are unrelated and fixed on `master`, so don't worry about those.

Let me rebase then to have a clean record here.

**Comment by dvail** [comment]
Regarding a clean test record, there is another issue due to what I believe is a race condition that affects UI e2e tests. If you get a large block of failure related to:
```
Workload CVE
Entities single view
Vulnerability Management Image CVEs
```
those are also no related to these changes. They are intermittent right now, but still frequent.

**Review by lvalerom — APPROVED** [review]
The backend code looks good to me. I will refer to the UI experts for the frontend 🙂

**Review by dvail — APPROVED** [review]
Approving on behalf of the UI team based on a previous review here https://github.com/stackrox/stackrox/pull/9460

**Pull request merged**
