### PR TITLE
feat(qa): Update midstream index images to use build v4.3.0-7

### PR DESCRIPTION
**Pull request by AlstonDias**
Update midstream iibs to rhacs-operator-bundle-container-**4.3.0-7**

### CODE REVIEW

**Comment by pratham-m** [comment]
@jdao-rh can you trigger builds on Z?

**Comment by pratham-m** [comment]
Hi @gavin-stackrox @robbycochran kindly review and approve the PR

**Review by gavin-stackrox — APPROVED** [review]

**Pull request merged**
