### PR TITLE
ROX-11774: Add basic BATS tests for roxctl netpol generate

### PR DESCRIPTION
**Pull request by vikin91**
## Description

This PR adds basic tests for the new command `roxctl netpol generate`.
Note that we do not test here the output of the the NP-Guard library (e.g., whether the produced network policies are correct), but the wrapper code in `roxctl` binary.

These tests are simple e2e tests and can be extended by adding Go unit tests in cobra.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

- [x] Executed the tests locally with `bats /tests/roxctl/bats-tests/local/roxctl-netpol-generate.bats`
- [ ] CI

### CODE REVIEW

**Review by Maddosaurus — APPROVED** [review]
LGTM!

Questions about test cases, though: 

Should we include something like checking for broken/wrong YAMLs? 
I know we've talked about this in the meeting, but the question is whether we should still include the case to check for error handling, even if we don't introduce validation for now.

**Comment by vikin91** [comment]
Ci failed with:

```
Container test exited with code 1, reason Error
---
networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   creationTimestamp: null
#   name: backend-netpol
# spec:
#   ingress:
#     - from:
#         - podSelector:
#             matchLabels:
#               app: frontend
#       ports:
#         - port: 9090
#           protocol: TCP
#   podSelector:
#     matchLabels:
#       app: backendservice
#   policyTypes:
#     - Ingress
#     - Egress
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   creationTimestamp: null
#   name: frontend-netpol
# spec:
#   egress:
#     - ports:
#         - port: 9090
#           protocol: TCP
#       to:
#         - podSelector:
#             matchLabels:
#               app: backendservice
#     - ports:
#         - port: 53
#           protocol: UDP
#   ingress:
#     - ports:
#         - port: 8080
#           protocol: TCP
#   podSelector:
#     matchLabels:
#       app: frontend
#   policyTypes:
#     - Ingress
#     - Egress
# Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:10.
# 	unmatched text: "document_"
# 
# -- output does not contain line --
# line : 0
# output (2 lines):
#   Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:10.
#   	unmatched text: "document_"
# --
# 
# Last output:
# Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:10.
# 	unmatched text: "document_"
```

As we do not have Junit on OSCI, I need to check that tomorrow.

**Comment by vikin91** [comment]
> LGTM!
> 
> Questions about test cases, though:
> 
> Should we include something like checking for broken/wrong YAMLs? I know we've talked about this in the meeting, but the question is whether we should still include the case to check for error handling, even if we don't introduce validation for now.

Sure, I can try adding such test case tomorrow!

**Pull request merged**
