### PR TITLE
Bump collector to the latest version

### PR DESCRIPTION
**Pull request by Molter73**
## Description

Bump collector to a version using the latest commits for the Falco fork.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- Integration tests on the collector repo are working.
- CI is green.

### CODE REVIEW

**Review by Stringy — APPROVED** [review]

**Comment by gavin-stackrox** [comment]
this should kick off a bit more flavor:
/test gke-kernel-qa-e2e-tests
/test openshift-newest-qa-e2e-tests
/test openshift-oldest-qa-e2e-tests

**Review by gavin-stackrox — APPROVED** [review]
Approved assuming extra openshift e2e + kernel tests are AOK.

**Pull request merged**
