### PR TITLE
ROX-14427: set PSPs for CI to false for k8s version 1.25 and higher

### PR DESCRIPTION
**Pull request by johannes94**
## Description

We've had CI Failures like [this](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-nightlies-osd-gcp-qa-e2e-tests/1615576493528715264), because the bundle installation method tries to install a PodSecurityPolicy for central by default if the env variable `POD_SECURITY_POLICIES` is not set or set to `true`. PodSecurityPolicy was removed from Kubernetes 1.25 and upwards, which is why the test setup is failing.

This PR changes the deploy scripts to query the Kubernetes server version and set `POD_SECURITY_POLICIES` to false if it detects a version >= 1.25.

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

Tested with commenting `/test osd-gcp-qa-e2e-tests`

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Comment by gavin-stackrox** [comment]
hi @johannes94 I added the all label and kicked off some more tests. I feel like those PSPs were required for some tests but this will give enough coverage to see.

**Comment by johannes94** [comment]
Thanks @gavin-stackrox, looks to me like all tests are green, I'll merge it.

**Pull request merged**
