### PR TITLE
ROX-15334: Use non-blocking locks in Postgres upserts

### PR DESCRIPTION
**Pull request by connorgorman**
## Description

Straight forward, plus a metric for ProcessAggregator

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Will check CI logs to see if any new conflicts are added

### CODE REVIEW

**Review by dashrews78 — CHANGES_REQUESTED** [review]
Need to include `central/processindicator/store/postgres/store.go` as it is no longer generated due to PLOP.

**Review by md2119 — APPROVED** [review]
Did not verify the coverage but the locking change lgtm.

**Review by dashrews78 — APPROVED** [review]

**Pull request merged**
