### PR TITLE
ROX-21069: enabled FF for offline v3

### PR DESCRIPTION
**Pull request by lvalerom**
## Description

Enabled offline v3.

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- `[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

- [x] CI

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]
LGTM!

This enables the feature - don't we need a changelog entry? The behavior of sensor while offline has actually changed.

**Comment by lvalerom** [comment]
> don't we need a changelog entry? The behavior of sensor while offline has actually changed.

@vikin91 Yeah I see where you are coming from, but I'm not sure if we need the entry. I believe we didn't add one for v1 and I think it would be inconsistent to add one only for v3. 🤷‍♂️ WDYT?

**Review by fredrb — APPROVED** [review]

**Pull request merged**
