### PR TITLE
ROX-13263: Refactor tests to reusue code

### PR DESCRIPTION
**Pull request by janisz**
## Description

Code cleanup

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3616** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3616" target="_blank">Graphite</a>  👈
    * **PR #3615** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3615" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3616?utm_source=stack-comment).

**Review by dashrews78 — APPROVED** [review]
Well that is certainly a lot cleaner.

**Review by md2119 — APPROVED** [review]
Ideally, The test should be renamed to `TestOptionsMapExist` because this unit test does not test the correctness of the options map.

**Pull request merged**
