### PR TITLE
ROX-11303: retry k8s requests in qa tests

### PR DESCRIPTION
**Pull request by janisz**
## Description

Configure k8s client to retry failed requests (500 and IOException). 
See: https://github.com/fabric8io/kubernetes-client#configuring-the-client

Refs: 
- https://github.com/fabric8io/kubernetes-client/pull/3293 
- https://github.com/fabric8io/kubernetes-client/pull/3164 

## Testing Performed

CI

### CODE REVIEW

**Review by stehessel — APPROVED** [review]

**Comment by msugakov** [comment]
@janisz how did you find out about

> 500 and IOException

?

**Comment by janisz** [comment]
Read the code. I liked related PRs that enabled it

**Comment by msugakov** [comment]
Thanks Tomek! I also +1 the change, but please do labels dance as Gavin suggests to ensure this doesn't break tests.

**Review by janisz — COMMENTED** [review]
/retest-required

**Comment by msugakov** [comment]
What is a bit concerning: `QA Automation Platform Part 1` tests execution time increased from 1h45m to more than 3 hours.
Without the change: https://app.circleci.com/pipelines/github/stackrox/stackrox/14670/workflows/9433c0e9-8f6e-4cfb-9cfa-1c2e21c45efe/jobs/686214
After the change: https://app.circleci.com/pipelines/github/stackrox/stackrox/14711/workflows/f841c852-728d-47d6-99d5-da85ceb5dbcf/jobs/688082/steps

I think this might be somehow related.

**Comment by janisz** [comment]
@msugakov label for all-qa tests was enabled. I'll remove it and rerun the test

**Comment by janisz** [comment]
Closing, I have no idea how to have green build on this

**Pull request closed without merging**
