### PR TITLE
chore(.github): format scripts with shellfmt

### PR DESCRIPTION
**Pull request by janisz**
## Description

Format scripts with shellfmt. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by porridge** [comment]
Screenshot from 2024-02-19 08-11-49

I think it will be difficult to:
- find someone with the stamina needed to review this all,
- avoid conflicts popping up during the review period

How about splitting this up by directory @janisz ?

**Comment by vikin91** [comment]
I scrolled through the changes and so far I like them. I didn't give ✅ as this was still in WIP.

**Comment by Maddosaurus** [comment]
@janisz if possible, could WIP PRs be flagged as drafts in the future? I'm aware that this doesn't work always, especially when we're working on CI. Still, let's strive to only notify reviewers once the PR is ready to merge 😄

**Review by gavin-stackrox — COMMENTED** [review]
Nice. I like the way it arrives as a go tool and not a rox-ci-image bump. 

I think changes to lint/style/format should be proposed and 'socialized' with #eng-discuss before implementation.

**Review by porridge — COMMENTED** [review]
1. Is the golangci-lint failure unrelated?
2. I'm not very fond of removing the space after `<`, `>` etc. I'm interested in what others think about this. Is this configurable? Can you check which way is more frequent in this repo?

Other than that I like this a lot!

**Pull request closed without merging**
