### PR TITLE
feat: added gosec G103

### PR DESCRIPTION
**Pull request by kadern0**
Signed-off-by: Pablo Caderno <kaderno@gmail.com>

## Description
As described on https://github.com/stackrox/stackrox/issues/3545, added gosec G103

### CODE REVIEW

**Comment by 0x656b694d** [comment]
Hi @kadern0. Thank you for addressing this! Now, please help us to fix the G103 alerts:
```
pkg/concurrency/error_signal.go:117:51: G103: Use of unsafe calls should be audited (gosec)
	if !atomic.CompareAndSwapPointer(&s.errPtr, nil, unsafe.Pointer(&err)) {
	                                                 ^
pkg/concurrency/error_signal.go:132:12: G103: Use of unsafe calls should be audited (gosec)
		errPtr:  unsafe.Pointer(&[]error{nil}[0]),
		         ^
pkg/concurrency/error_signal.go:147:13: G103: Use of unsafe calls should be audited (gosec)
		statePtr: unsafe.Pointer(newErrorSignalState()),
		          ^
```

**Comment by janisz** [comment]
@kadern0 `pkg/concurrency/error_signal.go` has some issues

**Review by janisz — CHANGES_REQUESTED** [review]
style checks are failing

**Review by janisz — APPROVED** [review]

**Review by misberner — APPROVED** [review]
LGTM. Now that generics exists, it might be good to add a generic atomic (pointer) value to contain the use of `unsafe.Pointer`s to low-level library code (not in this PR). Maybe Uber's atomic library already has something?

**Pull request merged**
