### PR TITLE
feat(tooling): Improve proto tooling

### PR DESCRIPTION
**Pull request by SimonBaeumer**
## Description

Improve proto tooling to automatically resolve a proto to the configure database.

Changelist:

 - to read from stdin added  `--stdin` flag (breaking change)
 - automatically resolve proto `storage.XYZ` to its table name
 - automatically connect to the database, configure it like a testing databases
 - added `--id` flag to easily provide an id
 - added `--where` to add where clauses to the query
 - added `--debug` flag

This allows to easily run a database locally or port-forwarded, connect to it and print a de-serialized proto for a table entry.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

 - tested documented queries locally from `README.md`

### CODE REVIEW

**Review by BradLugo — APPROVED** [review]
Only things I'm wondering about:
1.  If we should tidy up the `context.TODO()` contexts
2. Is there another function we can use to retrieve the connection string that doesn't require `testing`?

Otherwise, LGTM. Thanks Simon!

**Review by dashrews78 — APPROVED** [review]
LGTM

**Comment by SimonBaeumer** [comment]
> If we should tidy up the context.TODO() contexts

Hm, I did not cared much about it in the tooling. Could have used `context.Background()` though. 

> Is there another function we can use to retrieve the connection string that doesn't require testing?

The alternative I've seen was to remove the testing parameter, but that would remove the indicator to not use it in production stackrox code, that's why I've sticked with it.

**Pull request merged**
