### PR TITLE
ROX-18197: reenable test sensor reconnects

### PR DESCRIPTION
**Pull request by jschnath**
## Description

Testing if Test_SensorReconnects is still flaky

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Testing if Test_SensorReconnects is still flaky

### CODE REVIEW

**Comment by fredrb** [comment]
The integration tests don't run on non-groovy step. They run on `gke-sensor-integration-tests`.

**Comment by fredrb** [comment]
Also, you don't need to build new images everytime you re-run the tests because the commit sha did not change.

**Comment by jschnath** [comment]
With the tests passing it seems to me that everything is in order. I'll run them a few more times to rule out flakiness, but otherwise I think this can be merged as is

**Comment by jschnath** [comment]
@fredrb I've ran the test multiple times and it keeps passing so I think we are good to re-enable it. If you could give me a green I'll merge this, and perhaps we should keep an eye on the nightlies in the next few days to make sure it's not flaking in those.

**Review by fredrb — APPROVED** [review]

**Pull request merged**
