### PR TITLE
ROX-18291: backport to release-4.1

### PR DESCRIPTION
**Pull request by stehessel**
## Description

Backport to release-4.1 branch.

### CODE REVIEW

**Review by vladbologa — APPROVED** [review]

**Comment by stehessel** [comment]
hmm pretty much everything failing...

**Comment by vladbologa** [comment]
> hmm pretty much everything failing...

The 4.1 branch was pretty unstable, but this is too much. The operator ones definitely were not failing.

**Comment by stehessel** [comment]
The problem seems to be that the job to build the operator image fails in https://github.com/stackrox/stackrox/actions/runs/6406757405/job/17392024256.

**Comment by vladbologa** [comment]
> The problem seems to be that the job to build the operator image fails in https://github.com/stackrox/stackrox/actions/runs/6406757405/job/17392024256.

Yes and it fails because (thanks @porridge for noticing this):
[build-and-push-operator (RHACS_BRANDING)](https://github.com/stackrox/stackrox/actions/runs/6406757405/job/17428914944)
System.IO.IOException: No space left on device : '/home/runner/runners/2.309.0/_diag/Worker_20231005-125427-utc.log'

**Comment by stehessel** [comment]
Ok now it's looking much more reasonable. I believe the remaining failures are unrelated to this PR.

**Comment by stehessel** [comment]
I'll go ahead with the merge.

**Pull request merged**
