### PR TITLE
ROX-22479: set Scanner V4 env vars in Sensor correctly

### PR DESCRIPTION
**Pull request by vladbologa**
## Description

Alternative approach to https://github.com/stackrox/stackrox/pull/9904, in which I modify the Helm templates.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

TODO(replace-me)  
Use this space to explain **how you validated** that **your change functions exactly how you expect it**.
Feel free to attach JSON snippets, curl commands, screenshots, etc. Apply a simple benchmark: would the information you
provided convince any reviewer or any external reader that you did enough to validate your change.

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by mclasmeier** [comment]
I don't quite understand the necessity for *this* particular change yet. In my mind, what you call `._rox.sensor.localImageScanningV4.enabled == true` is completely equivalent to `._rox._scannerV4Enabled == true && chart == "secured-cluster-services"`?

**Comment by vladbologa** [comment]
> I don't quite understand the necessity for _this_ particular change yet. In my mind, what you call `._rox.sensor.localImageScanningV4.enabled == true` is completely equivalent to `._rox._scannerV4Enabled == true && chart == "secured-cluster-services"`?

It allows me to set `localImageScanningV4` to `true` from the operator, while otherwise not enabling `scannerV4`. It follows the same logic of scannerV2.

**Comment by mclasmeier** [comment]
> > I don't quite understand the necessity for _this_ particular change yet. In my mind, what you call `._rox.sensor.localImageScanningV4.enabled == true` is completely equivalent to `._rox._scannerV4Enabled == true && chart == "secured-cluster-services"`?
> 
> It allows me to set `localImageScanningV4` to `true` from the operator, while otherwise not enabling `scannerV4`. It follows the same logic of scannerV2.

Understood. thanks.

**Comment by vladbologa** [comment]
Closing this, as we decided on the https://github.com/stackrox/stackrox/pull/9904 approach.

**Pull request closed without merging**
