### PR TITLE
Groovy test changes to add multi-arch support

### PR DESCRIPTION
**Pull request by pratham-m**
## Description

This PR intends to add multi-arch support for the groovy tests.
Test images used in respective test are changed to use alternate multi-arch images which support 3 platforms viz. `x86_64`, `ppc64le` and `s390x`.

Changes are verified manually using `./gradlew test --tests=TestName`

### CODE REVIEW

**Comment by pratham-m** [comment]
@robbycochran @gavin-stackrox kindly check

**Comment by gavin-stackrox** [comment]
I will need to create another PR with these changes as CI is currently non-operational for external contributors.

**Comment by pratham-m** [comment]
#4298 created in favor of this since builds are not supported for external contributors.
Refer https://github.com/stackrox/stackrox/pull/4262#issuecomment-1370125024

**Comment by pratham-m** [comment]
Few github action based builds are failing due to quay authentication issues, may be due to the `external-contributor` tag since the PR was created from a fork.
https://github.com/stackrox/stackrox/pull/4358 directly from the branch in main repo.

**Pull request closed without merging**
