### PR TITLE
chore(deps): upgrade k8s-overlay-patch - optional overlays

### PR DESCRIPTION
**Pull request by ludydoo**
## Description

- Upgrading the `k8s-overlay-patch` dependency (the new version allows for optional patches, that won't throw if a resource is not found)
- Adding the corresponding `optional` flag to our `Overlay` type.

### Why ? 
- We will add the `networkPolicies: disabled` (or similar) to the CRDs/helm which allows disabling the generation of NetworkPolicies in ROX-23972
- On ACS-CS, we have overlays to that modify the network policies
- We will be disabling the generation of NetworkPolicies on ACS-CS to use our own
- Without the `optional: true`, the operators would suddenly start failing because the overlay targets (NetworkPolicies) don't exist anymore
- With the `optional: true`, it will be a smoother transition
- The operator will still complain, but it won't throw. See this https://github.com/stackrox/k8s-overlay-patch/blob/74a2a4fd2bae89a6724d4cdcbd2b3b784947e2a3/pkg/patch/patch.go#L163-L166

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~~Unit test and regression tests added~~
- [ ] ~~Evaluated and added CHANGELOG entry if required~~
- [ ] ~~Determined and documented upgrade steps~~
- [ ] ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

Added 2 unit tests
- One that tests that an optional Overlay that targets a non-existing resource won't throw and will be skipped
- One that tests that a non-optional Overlay that targets a non-existing resource will throw

### CODE REVIEW

**Review by dhaus67 — APPROVED** [review]
Would be great to have a meaningful PR description :)

**Review by porridge — APPROVED** [review]
LGTM apart from the untouched PR description template.

**Comment by ludydoo** [comment]
@porridge sorry about that. As I was writing the description, I also realized I forgot to update the CRD itself to include that new flag. 🤦  Would you mind taking a second look ?

**Review by porridge — CHANGES_REQUESTED** [review]
One wording improvement inline.

I think the PR title should primarily mention the added optional feature 🤔 

Also, the generated file check is failing.

**Comment by porridge** [comment]
The `Testing Performed` section also needs a touch 😉

**Review by porridge — APPROVED** [review]

**Pull request merged**
