### PR TITLE
Remove unneeded context

### PR DESCRIPTION
**Pull request by janisz**
## Description

After removal of auth plugin we no longer need context in scope checker. This PR removes it.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2726** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2726" target="_blank">Graphite</a> 
    * **PR #2722** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2722" target="_blank">Graphite</a> 
      * **PR #2750** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2750" target="_blank">Graphite</a> 
        * **PR #2751** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2751" target="_blank">Graphite</a> 
          * **PR #2752** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2752" target="_blank">Graphite</a> 
            * **PR #2774** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2774" target="_blank">Graphite</a> 
              * **PR #2775** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2775" target="_blank">Graphite</a> 
                * **PR #2776** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2776" target="_blank">Graphite</a> 
                  * **PR #2777** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2777" target="_blank">Graphite</a>  👈
                    * **PR #2778** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2778" target="_blank">Graphite</a> 
                      * **PR #2779** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2779" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/2777?utm_source=stack-comment).

**Review by md2119 — APPROVED** [review]
🪓  away

**Review by rhybrillou — APPROVED** [review]

**Comment by janisz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/2777?utm_source=stack-comment).


Job Reference: KaXF6lRV7xj8fvvZbgOl

**Pull request merged**
