### PR TITLE
fix(ui): Misc VM 2.0 Improvements

### PR DESCRIPTION
**Pull request by sachaudh**
## Description

Following changes were made in this PR

1. A simple change for the display name from "Fixable" to "CVE status"
2. We want to have the image name link point to VM 2.0 instead of VM 1.0 in the following areas: Violations, Network Graph, Risk

### The filter chip display name should be changed from "Fixable" to "CVE status"

Screenshot 2024-04-05 at 11 55 42 AM
Screenshot 2024-04-05 at 11 56 09 AM

### The image name link should point to VM 2.0 instead of VM 1.0 in Violations

Screenshot 2024-04-04 at 4 09 37 PM
Screenshot 2024-04-04 at 4 10 13 PM

### The image name link should point to VM 2.0 instead of VM 1.0 in Network Graph

Screenshot 2024-04-04 at 4 14 51 PM
Screenshot 2024-04-04 at 4 15 12 PM

### The image name link should point to VM 2.0 instead of VM 1.0 in Risk

Screenshot 2024-04-04 at 4 18 48 PM
Screenshot 2024-04-04 at 4 19 07 PM

### CODE REVIEW

**Review by dvail — COMMENTED** [review]
These changes look good, but one thought I don't think we have discussed:

Do we need or want a feature flag for `ROX_VM_2_GA` as a fallback in case we need to revert to VM 1.0? I'm thinking things like these links, how to render the main app navigation, etc, depending on the state of VM 2.0 at release time.

**Comment by sachaudh** [comment]
> These changes look good, but one thought I don't think we have discussed:
> 
> Do we need or want a feature flag for `ROX_VM_2_GA` as a fallback in case we need to revert to VM 1.0? I'm thinking things like these links, how to render the main app navigation, etc, depending on the state of VM 2.0 at release time.

Yea, that's worth adding. I guess if there's a chance we don't GA for some reason, it's better to be safe

**Comment by sachaudh** [comment]
@dvail I did an edit to this PR to add feature flag logic. Let me know if the updates look good to you as well.

**Review by dvail — APPROVED** [review]
LGTM

Only one nit: do you think we will use this feature flag as the general gate for VM 2.0 GA?

If so, it might be better to name it something more closely communicating that it will enable all the GA changes (side navigation, removing VM 1.0, etc.).

**Comment by dvail** [comment]
> Would that also include the platform/node CVEs work and advanced filters? 

Personally I think those should be different, like the flags you listed above. I'm thinking that anything we would theoretically be able to (or want to) release _regardless_ of GA should have its own flag, and any changes that are deprecating VM 1.0 should be in another flag.

I think these would fall under the former:
- Advanced filters
- Node/Platform CVEs
- Namespace view
- General Workload CVE fixes

While these would fall under the latter:
- Changing links from other places in the app to point to VM 2.0 instead of VM 1.0
- Removing VM 1.0 from the left navigation
- Removing VM 1.0 routes
- Removing all Tech Preview labels, banners, etc. from VM 2.0

> I may do it in a future PR since I want to move this along.

Totally fine with me. The naming is just a nit, but I think if we split it up functionality like above we should be fine. 🚢

**Pull request merged**
