### PR TITLE
Bumps collector version to 3.15.0

### PR DESCRIPTION
**Pull request by Stringy**
## Description

In preparation for code-freeze, this bumps the collector version to the newly cut version 3.15.0

### CODE REVIEW

**Comment by ovalenti** [comment]
@Stringy , I think I remember now that pointing to a commit which is not on _master_ breaks midstream. We should maybe point to 3.15.x instead and bump collector to 3.15.0 once release-4.1 is cut ?

**Comment by Stringy** [comment]
> pointing to a commit which is not on master breaks midstream

I think it only needs to be a valid commit that is reachable on some branch in the repo. Unless I am remembering that incorrectly?

**Comment by msugakov** [comment]
> I think it only needs to be a valid commit that is reachable on some branch in the repo. 

Yes, that. No need to worry about custom branches and commits as long as they are **present** in the repo. That previous time the commit was not findable in the repo.

**Comment by ovalenti** [comment]
> > pointing to a commit which is not on master breaks midstream
> 
> I think it only needs to be a valid commit that is reachable on some branch in the repo. Unless I am remembering that incorrectly?

I mixed-up with the submodules branches, which can't find the commit if not on the specified branch. Sorry :)

**Pull request merged**
