### PR TITLE
Print debug logs in e2e tests

### PR DESCRIPTION
**Pull request by janisz**
## Description

Enable debug logs in e2e tests to help debugging issues.
Refs: https://github.com/stackrox/stackrox/pull/2661
## Testing Performed
CI

Refs:  ROX-12096

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2994** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2994" target="_blank">Graphite</a> 
    * **PR #2995** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2995" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/2995?utm_source=stack-comment).

**Comment by gavin-stackrox** [comment]
Lets run with `ci-race-condition-tests` so that `gke-race-condition-qa-e2e-tests` run. If they can handle debug mode without error then 👍 
/test gke-race-condition-qa-e2e-tests

**Review by janisz — COMMENTED** [review]
/retest

**Comment by janisz** [comment]
It's no longer needed as we put our debug logs in `Info` level and filter they by deployment name

**Pull request closed without merging**
