### PR TITLE
ROX-15236: Silence http logs containing preface

### PR DESCRIPTION
**Pull request by connorgorman**
## Description

Silence preface logs due to haproxy probes

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Run in environment where this error occurs

### CODE REVIEW

**Comment by kylape** [comment]
Any concern that this could hide legitimate problems where this log message is emitted due to a cause other than haproxy probes?

**Comment by connorgorman** [comment]
@kylape Potentially, I did try to make it as specific to the message as possible. Not sure what other options we have to silence it though. I can make it specific to managed services flag if you'd prefer

**Comment by kylape** [comment]
yeah... it's probably worth hiding it behind the managed services flag.  I assume we've never seen customer logs flooded with these "preface" messages before, right?

**Comment by connorgorman** [comment]
@kylape updated

**Review by kylape — APPROVED** [review]
lgtm

**Pull request merged**
