### PR TITLE
Bump collector version to 3.11.x latest

### PR DESCRIPTION
**Pull request by Stringy**
## Description

This includes the fix for a SEGFAULT in ProtoAllocator. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

Testing performed in collector repository, will also inspect outcomes of stackrox CI.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by msugakov — APPROVED** [review]
Please check that CI failures are not induced by the change.

**Comment by Stringy** [comment]
The failure in `gke-postgres-qa-e2e-tests` is a known flake: https://issues.redhat.com/browse/ROX-12926

`gke-nongroovy-e2e-tests` I'm less sure about. I'll retest to see if it's consistent.

**Comment by Stringy** [comment]
It appears that the failure on `gke-nongroovy-e2e-tests` was inconsistent and now that step has passed so I think it's fair to say that it is unrelated to bumping the collector version. I'll merge.

**Pull request merged**
