### PR TITLE
ROX-18124: compliance add compliance operator edit roles

### PR DESCRIPTION
**Pull request by dashrews78**
## Description

For the next generation compliance ACS secured clusters need the ability to create certain compliance operator objects in order to create scan schedules.  In particular ACS (specifically sensor) need to be able to write ScanSetting and ScanSettingBinding CRs on the secured clusters to create compliance operator scans.  This PR adds the role and rolebinding needed to accomplish this. 

Question:  Is there a way to check to see if the required `openshift-compliance` namespace exists before trying to apply the role and rolebindings?

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

Used executed the deploy scripts with the compliance operator flag on and off.  Tested on openshift and GKE clusters to ensure if the deploy script set the helm flag that the role and rolebinding deployed as long as the `openshift-compliance` namespace existed.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by porridge** [comment]
> Question: Is there a way to check to see if the required openshift-compliance namespace exists before trying to apply the role and rolebindings?

@dashrews78 yes, look at the `safeLookup` function. You might also find inspiration from the `*openshift-monitoring.yaml` manifests which do similar things.
However note that if you go down the `lookup` path that this is disabled when using the operator, so you'd need to do a check there and plumb a boolean down.

**Review by SimonBaeumer — CHANGES_REQUESTED** [review]

**Pull request merged**
