### PR TITLE
ROX-21015: Switch OCP jobs to 2 x e2-standard-8 workers

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

This PR makes the OCP cluster worker node type and count more explicit and in line with requests (see ROX-21015).

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

... most OCPs ...

### CODE REVIEW

**Review by porridge — APPROVED** [review]
It seems we're switching **both** `n2-standard-4 x 3` and `n2-standard-4 x 4` ((4CPU, 16GB) x {3,4}) to `e2-standard-8 x 2` ((8CPU, 32GB) x 2)?

Assuming I got this right, sounds like things should fit.

**Comment by gavin-stackrox** [comment]
> It seems we're switching **both** `n2-standard-4 x 3` and `n2-standard-4 x 4` ((4CPU, 16GB) x {3,4}) to `e2-standard-8 x 2` ((8CPU, 32GB) x 2)?
> 
> Assuming I got this right, sounds like things should fit.

:+1:

**Pull request merged**
