### PR TITLE
Move generators to a separated module

### PR DESCRIPTION
**Pull request by janisz**
## Description

Similary to linters and test tools let's move generators to their own module so they will not mess with root `go.mod`

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3009** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3009" target="_blank">Graphite</a> 
    * **PR #2994** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2994" target="_blank">Graphite</a> 
      * **PR #2995** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2995" target="_blank">Graphite</a> 
    * **PR #2992** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2992" target="_blank">Graphite</a> 
      * **PR #2969** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2969" target="_blank">Graphite</a> 
        * **PR #3064** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3064" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3064?utm_source=stack-comment).

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3009** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3009" target="_blank">Graphite</a> 
    * **PR #2994** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2994" target="_blank">Graphite</a> 
      * **PR #2995** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2995" target="_blank">Graphite</a> 
    * **PR #2992** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2992" target="_blank">Graphite</a> 
      * **PR #2969** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2969" target="_blank">Graphite</a> 
        * **PR #3064** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3064" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3064?utm_source=stack-comment).

**Review by misberner — CHANGES_REQUESTED** [review]
I don't think we want this for all generators. For some of these, the generated code has runtime dependencies on the respective library. We do not want versions for generation to diverge from the runtime libraries.

I haven't conducted a complete audit, but this is certainly the case for:
- gogo/protobuf
- mailru/easyjson
- golang/mock
- maureicelam/genny

**Comment by janisz** [comment]
@misberner Thanks, I completely forgot about this and few removed entries from go.mod didn't ring a bell for me. Thanks!

**Pull request closed without merging**
