### PR TITLE
Run style action on PRs, tags and master

### PR DESCRIPTION
**Pull request by janisz**
## Description

Currently we are running style action only on PRs. This is suboptimal as cache is not populated by master branch. This change enables `style` on all PRs and pushes to master

### CODE REVIEW

**Comment by janisz** [comment]
I created a PR to show how it will look like https://github.com/stackrox/stackrox/pull/4131
I did not focused on UX of this change but if tools supports sarif then we could use it (e.g. golangci-lint provides an action that comment directly on PR https://github.com/golangci/golangci-lint-action#golangci-lint-action).
So far I tried to keep it simple and use `make` instead of actions but maybe we switch to actions over our scripts ;) 

This PR is mostly about populating cache after every merge so `make style` will take ~20min instead of ~60.

Refs:
https://www.npmjs.com/package/@microsoft/eslint-formatter-sarif

**Review by gavin-stackrox — APPROVED** [review]
Got it.

**Comment by janisz** [comment]
Here is the example failure https://github.com/stackrox/stackrox/pull/4131
For now it will stop when first `check` fails. I created couple of issues but only golangci was reported.

**Pull request merged**
