### PR TITLE
ROX-26908: set operator fips-compliant:true

### PR DESCRIPTION
**Pull request by davdhacs**
### Description

Setting fips-compliant operator feature to true.

This is not technically true for upstream. But we do not publish the upstream operator, and it is true for the published operator (downstream (CPaaS and Konflux)).

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

change me!

### CODE REVIEW

**Review by msugakov — APPROVED** [review]
LGTM

Please: reference JIRA ticket (so that we can recover context later) and get approval from one of the Install team colleagues.

**Review by vladbologa — COMMENTED** [review]
I'm not very familiar with the topic, but I think that for fips compliance we need to:
* use a fips compliant base image
* compile with `CGO_ENABLED=1` so that the binaries use the OpenSSL libs from the base image

I think that downstream and Konflux already do that, but quickly going through our code, the upstream might not, e.g. see https://github.com/stackrox/stackrox/blob/master/operator/Dockerfile#L52

Is that a problem? cc @msugakov @porridge @mclasmeier

**Comment by msugakov** [comment]
Declaring FIPS upstream but not supporting it for the time being is fine, in my opinion.
* We don't distribute upstream-built operator to community; there are no community builds of the operator. I mean quay.io/stackrox-io/
* Even if we did, free product users wouldn't care about FIPS.
* Internally (I mean quay.io/rhacs-eng/), we don't have tests that deeply check FIPS conformance which would break because of that.

**Comment by vladbologa** [comment]
> Declaring FIPS upstream but not supporting it is fine, in my opinion.
> 
> * We don't distribute upstream-built operator to community; there are no community builds of the operator. I mean quay.io/stackrox-io/
> * Even if we did, free product users wouldn't care about FIPS.
> * Internally (I mean quay.io/rhacs-eng/), we don't have tests that deeply check FIPS conformance which would break because of that.
> 
> > use a fips compliant base image
> 
> FWIW, UBI8 has fips-certified openssl (we use only that). CentOS Stream most certainly doesn't. It would be impossible to be fully FIPS upstream but nobody cares, I believe. FIPS is important for the commercial product.

I agree with you, I just wonder if we should actually mention anywhere that the upstream build is marked as fips compliant when it's actually not.

**Review by vladbologa — APPROVED** [review]
LGTM.

I was a bit concerned that we're also marking the upstream build as fips compliant when it's not (see my other comments and Misha's reply). We could at least mention this somewhere (even the description of this PR would be ok for me).

**Pull request merged**
