### PR TITLE
Upgrade cypress 10.6.0 devDependencies in ui

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

Catch up with cypress after pause to fix intermittent test failures in OpenShift CI.

Welcome_to_Cypress

Choose_a_Browser

Click a name to run a test file
Specs

When the tests have finished, click the **Specs** button to run another test file
Results

### Resources

1. https://docs.cypress.io/guides/references/changelog#10-4-0
    * Upgraded electron from 18.3.0 to 19.0.8
    * Upgraded bundled Node.js version from 16.13.2 to 16.14.2
    * Upgraded bundled Chromium version from 100.0.4896.75 to 102.0.5005.148
2. https://docs.cypress.io/guides/references/changelog#10-2-0
    * Cypress is now available natively on Apple silicon, including the M1 and M2 processor families. For more details, read our blog post:
        https://www.cypress.io/blog/2022/06/21/cypress-10-2-0-run-tests-up-to-2x-faster-on-apple-silicon-m1/
    * Cypress is now available natively on ARM64 and AArch64 systems running Linux.
3. https://docs.cypress.io/guides/references/changelog#10-0-0
4. https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0
    * https://docs.cypress.io/guides/references/migration-guide#baseUrl
        The `baseUrl` config option is no longer valid at the top level of the configuration, and may only be defined inside the `e2e` configuration object.
    * https://docs.cypress.io/guides/references/migration-guide#ignoreTestFiles-excludeSpecPattern
        The `ignoreTestFiles` option has been replaced with the `excludeSpecPattern` options.
        Instead, replace with `specPattern` option inside the `e2e` configuration object.
    * https://docs.cypress.io/guides/references/migration-guide#pluginsFile
        The `pluginsFile` option is no longer used.
    * https://docs.cypress.io/guides/references/migration-guide#Migrating-from-cypress-file-upload-to-selectFile
        The argument signature is different for Cypress' builtin `.selectFile()` command than the `.attachFile` command the `cypress-file-upload` plugin provided.
        Rename `fileContent` as `contents` property. Inferred from docs that if no `fileName` property then `contents` can have relative file path from folder which contains Cypress config file. Therefore, it needs `Cypress.config('fixturesFolder')` unlike `fixture` which is relative to fixtures folder.
        Remove `encoding` property. It is no longer needed due to improved binary file handling in Cypress 9.0.
        In most cases you do not need to give a `mimeType` explicitly. Cypress will attempt to infer the MIME type based on the extension of the fileName if none is provided.
5. https://docs.cypress.io/guides/references/configuration
    * https://docs.cypress.io/guides/references/configuration#Intelligent-Code-Completion
        The `defineConfig` helper function is exported by Cypress, and it provides automatic code completion for configuration in many popular code editors. See comment below about unexpected side effect.
    * https://docs.cypress.io/guides/references/configuration#Options
6. https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Support-file
    * To include code before your test files, `supportFile` is set to look for cypress/support/e2e.js

### Changed files

1. Replace ui/cypress.json with ui/cypress.config.js

    ```js
    {
        "baseUrl": "https://localhost:3000", // e2e
        "blockHosts": ["*.*"],
        "chromeWebSecurity": false,
        "ignoreTestFiles": ["**/constants/**/*", "**/helpers/**/*"], // e2e specPattern
        "viewportWidth": 1440,
        "viewportHeight": 850,
        "numTestsKeptInMemory": 0,
        "pluginsFile": false, // not needed
        "retries": { // Global options: not needed because default value
            "runMode": 0,
            "openMode": 0
        }
    }
    ```

    ```js
    const { defineConfig } = require('cypress');

    module.exports = defineConfig({
        blockHosts: ['*.*'], // Browser options
        chromeWebSecurity: false, // Browser options
        numTestsKeptInMemory: 0, // Global options
        viewportHeight: 850, // Viewport options
        viewportWidth: 1440, // Viewport options

        e2e: {
            baseUrl: 'https://localhost:3000',
            specPattern: 'cypress/integration/**/*.test.js',
        },
    });
    ```

2. Replace `attachFile` with `selectFile` method:
    * network.test.js: 1 occurrence
    * policies/importPolicy.test.js: 4 occurrences

3. Delete obsolete mainmenu.test.js

4. Adjust support files
    * Rename cypress/support/index.js as cypress/support/e2e.js which is the new default for e2e test.
    * Edit cypress/support/commands.js to delete `import 'cypress-file-upload';` which is superseded by `selectFile` method.
        **Residue**: Refactor network tests to call helper function instead of `Cypress.Commands.add('getCytoscape', …)` command.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Edited integration tests

## Testing Performed

1. `yarn cypress-open` in ui/apps/platform select an assortment of tests:
    * clusters/clusters.test.js
    * compliance/complianceDashboard.test.js
    * configmanagement/dashboard.test.js **1 test fails locally**
    * integrations/externalBackups.test.js
    * integrations/general.test.js
    * integrations/imageIntegrations.test.js
    * integrations/notifiers.test.js
    * networkGraph/networkFlows.test.js **5 tests fail locally**
    * networkGraph/networkGraph.test.js **1 test fails locally**
    * policies/exportPolicy.test.js
    * policies/importPolicy.test.js has 4 occurrences of `selectFile` method
    * policies/policyWizardStep3.test.js
    * violations/violations.test.js
    * vulnmanagement/dashboard.test.js
    * risk/risk.test.js
    * general.test.js
    * network.test.js has 1 occurrence of `selectFile` method
    * productBranding.test.js
    * systemconfig.test.js

### CODE REVIEW

**Comment by pedrottimark** [comment]
The `defineConfig` helper function intended to provide automatic code completion for configuration in many popular code editors had subtle side-effect to cause some errors in unit test files:

```text
ui/apps/platform/src/Containers/Dashboard/PatternFly/ScopeBar.test.tsx
56:29  error  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return
70:29  error  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return
120:29  error  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return
ui/apps/platform/src/services/cancellationUtils.test.ts
19:9  error  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return
27:9  error  Unsafe return of an `any` typed value  @typescript-eslint/no-unsafe-return
```

**Review by dvail — APPROVED** [review]
Amazing the seemingly unrelated tooling changes that cause issues in other parts of the code base. 🤷

**Comment by pedrottimark** [comment]
Yeah, out of an abundance of caution, I will merge first thing Monday morning.

**Pull request merged**
