### PR TITLE
ROX-17655: fix declarative config "orpaned resources" test

### PR DESCRIPTION
**Pull request by ivan-degtiarenko**
## Description

Investigation didn't give any results - for some reason, auth provider is not guaranteed to be returned at this point in test.
I added retries, and the test seems to pass(I ran it ±100 times).

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

1. CI is sufficient + tested before within this PR

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]
groovy!

**Review by stehessel — APPROVED** [review]

**Pull request merged**
