### PR TITLE
Use search for network policies instead of walks (#6079)

### PR DESCRIPTION
**Pull request by tommartensen**
## Description

Cherry-picking #6079.

### CODE REVIEW

**Review by connorgorman — APPROVED** [review]

**Comment by connorgorman** [comment]
@tommartensen Not sure what we can do about those two failing stages

**Comment by gavin-stackrox** [comment]
@connorgorman @tommartensen I've asked about this in https://redhat-internal.slack.com/archives/CBN38N3MW/p1684864225577309
It does not seem at all related to changes we made to the CI config lately so hopefully we'll get a resolution there or I will escalate.

**Comment by gavin-stackrox** [comment]
/retest
The fix is in.

**Comment by gavin-stackrox** [comment]
Whoa. All green.

**Comment by tommartensen** [comment]
> Whoa. All green.

Never seen all green on this branch before 😱

**Pull request merged**
