### PR TITLE
OSCI: onboard gke-qa-e2e-tests

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

This PR enables `gke-qa-e2e-tests` (formerly `gke-api-e2e-tests`) for OpenShift CI.

## Checklist
- [x] Investigated and inspected CI test results

## Test Plan

May/23/2022: A hard 2 hour timeout applied to openshift/release pj-rehearse tests means that most of the negative test cases will need to happen post merge.

### gke-qa-e2e-tests

- Happy path
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Artifacts are stored similar to CCI

- Cluster create fails
  - [ ] The prow buildlog indicates it was the create that failed
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Teardown is attempted but should not block

- Unit test fails in part I (forced)
  - [ ] The test that failed is indicated
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Backend logs are gathered at point of failure and saved to artifacts
  - [ ] Part II tests still run
  - [ ] DB tests do not run
  - [ ] Artifacts are stored similar to CCI

- Test meltdown (delete cluster mid test)
  - [ ] Some number of failed tests are indicated in the prow buildlog
  - [ ] The process completes without openshift CI timeout
  - [ ] Part II tests still run
  - [ ] DB tests do not run
  - [ ] Artifacts are stored similar to CCI

- Unit test fails in part II (forced)
  - [ ] The test that failed is indicated
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Backend logs are gathered at point of failure and saved to artifacts
  - [ ] DB tests do not run
  - [ ] Artifacts are stored similar to CCI

- DB test fails at backup
  - [ ] The point of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] DB test artifacts are saved in artifacts

- DB test fails at restore
  - [ ] The point of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] DB test artifacts are saved in artifacts

- Error in central logs after part I (verifies check_stackrox_logs())
  - [ ] The cause of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Part II tests still run
  - [ ] DB tests do not run
  - [ ] Artifacts are stored similar to CCI

- Error in central logs after part II (verifies check_stackrox_logs())
  - [ ] The cause of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] DB tests do not run
  - [ ] Artifacts are stored similar to CCI

- Error in central logs after DB test (verifies check_stackrox_logs())
  - [ ] The cause of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Artifacts are stored

### gke-upgrade-tests

- Happy path
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Artifacts are stored similar to CCI

- Forced failure
  - [ ] The point of failure is indicated in the prow buildlog
  - [ ] There are no spurious errors in the prow buildlog
  - [ ] Artifacts are stored similar to CCI

### After merge tests

Pre merge these runs are rehearsed by openshift CI and the tag + label checks
will not apply to set BAT -v- all level of tests.

- [ ] On a new PR ensure that BAT only runs
- [ ] With the 'all' label ensure that all runs
- [ ] With the 'no' label ensure that QA tests do not run
- [ ] With only UI changes ensure that QA tests do not run

### CODE REVIEW

**Review by sbostick — APPROVED** [review]
LGTM

**Review by janisz — COMMENTED** [review]
There is a lot of python code. Do we have linter and formatter for python? I will be great to have it before working on python code as it can easily detect some issues and force convention.

**Comment by gavin-stackrox** [comment]
> There is a lot of python code. Do we have linter and formatter for python? I will be great to have it before working on python code as it can easily detect some issues and force convention.
Yes @janisz see https://raw.githubusercontent.com/stackrox/stackrox/gavin-OSCI-onboard-gke-api-e2e/.openshift-ci/README.md.

**Pull request merged**
