### PR TITLE
Remove envisolator references in non-generated code

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

The `pkg/testuitls/envisolator` pre-dates the `go1.17` release where `t.Setenv` was added.

While it served us well, we should switch to the officially maintained solution of `t.Setenv`.

The PRs are split into the following:
- removal of non-generated references within our code and replace with `t.Setenv` (this includes also refernces that were left over).
- removal of generated references within our code.
- final removal of the package `pkg/testutils/envisolator`.

## Checklist
- [ ] Investigated and inspected CI test results
~~- [ ] Unit test and regression tests added~~
~~- [ ] Evaluated and added CHANGELOG entry if required~~
~~- [ ] Determined and documented upgrade steps~~
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

- see CI, as each tests should have the same behavior as prior to the change.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3593** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3593" target="_blank">Graphite</a>  👈
    * **PR #3594** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3594" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3593?utm_source=stack-comment).

**Review by md2119 — APPROVED** [review]

**Review by misberner — APPROVED** [review]

**Review by janisz — APPROVED** [review]

**Pull request merged**
