### PR TITLE
ROX-17885: Bump collector to 3.13.3

### PR DESCRIPTION
**Pull request by ovalenti**
## Description

This is just a rebuild with included python CVE fixes in the base image

## Checklist
- [ ] Investigated and inspected CI test results

### CODE REVIEW

**Review by dashrews78 — APPROVED** [review]

**Comment by ovalenti** [comment]
After analysis of the failures, it seems that most of them are due to CRDs not being setup.

`gke-postgres-nongroovy-e2e-tests` fails consistently on a process list expectation; which may be related to changes in the test images.

Should we merge as is @dashrews78 ?

**Comment by dashrews78** [comment]
> After analysis of the failures, it seems that most of them are due to CRDs not being setup.
> 
> `gke-postgres-nongroovy-e2e-tests` fails consistently on a process list expectation; which may be related to changes in the test images.
> 
> Should we merge as is @dashrews78 ?

Yeah.  I'm going to have to spend some time and cherry pick some additional test fixes it appears with the PSP deal.

**Comment by dashrews78** [comment]
Sorry about the accidental closure.

**Comment by dashrews78** [comment]
@ovalenti Also some of these failures will be fixed by the back port of the sensor upgrade issue.  So I think this PR is good to go.

**Pull request merged**
