### PR TITLE
Bump 4.4 version to 4.4.7 in upgrade test

### PR DESCRIPTION
**Pull request by SimonBaeumer**
### Description

Bump 4.4 version in upgrade test

### CODE REVIEW

**Review by vjwilson — APPROVED** [review]
/lgtm

**Review by dashrews78 — CHANGES_REQUESTED** [review]
You somehow started with an old version.  Need to add it to this one

https://github.com/stackrox/stackrox/blob/371080c5613e9c75f98e778e23d9195e62938506/tests/upgrade/postgres_run.sh#L13

**Comment by SimonBaeumer** [comment]
@dashrews78 In this case the MR can be closed, because `master` is using `4.4.6` as a previous release already, correct?

**Comment by dashrews78** [comment]
> @dashrews78 In this case the MR can be closed, because `master` is using `4.4.6` as a previous release already, correct?

No, you need to bump it to use `4.4.7`.  The point of this is so that the upgrade test always walks the latest version available for each release.

**Pull request closed without merging**
