### PR TITLE
fix(CI): Remove pause-reconcile annotation before cleanup

### PR DESCRIPTION
**Pull request by mdafsanhossain**
### Description

Setting pause-reconcile annotation to `true` causes problem when deleting central and secured-cluster services in static clusters(ppc64le) before deploying and running tests.
This PR removes the annotation before cleanup of central and secured-cluster is performed. 

### User-facing documentation

(*must be* 2 items and both *must be* checked)

- [ ] CHANGELOG is updated
- [ ] CHANGELOG update is not needed
- [ ] Documentation PR is created and linked above
- [ ] Documentation is not needed

### Testing

- [ ] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests
- [ ] contributed **no automated tests**
  

#### How I validated my change

Change validated by running the change against an ocp 4.16 ppc64le cluster.

### CODE REVIEW

**Comment by mdafsanhossain** [comment]
@robbycochran Can you review this?

**Comment by robbycochran** [comment]
@mclasmeier Any thoughts on this PR? You added some related code here: https://github.com/stackrox/stackrox/pull/9866/files. I'm also wondering if the CRs are ever deleted after your change if `namespace` is not defined?

**Comment by mdafsanhossain** [comment]
@robbycochran Are the changes ok or do you suggest any improvements? Or is it good to merge?

**Comment by robbycochran** [comment]
This looks good to me.

**Comment by mdafsanhossain** [comment]
@robbycochran Can you approve this?

**Review by robbycochran — APPROVED** [review]

**Pull request merged**
