### PR TITLE
chore(backport): ci disk free

### PR DESCRIPTION
**Pull request by stehessel**
## Description

Backport of https://github.com/stackrox/stackrox/pull/7985 to release-4.0 branch.

### CODE REVIEW

**Review by vjwilson — APPROVED** [review]

**Review by gavin-stackrox — APPROVED** [review]
Thanks Stephan!

**Comment by gavin-stackrox** [comment]
I wonder why this PR is not building though.

**Comment by gavin-stackrox** [comment]
> I wonder why this PR is not building though.

This was because the PR was opened against master originally and editing the target branch does not cause github to take action. So I pushed an empty commit. ~If~Once CI passes I'll merge.

**Pull request merged**
