### PR TITLE
ROX-21937: Remove stackrox.io references

### PR DESCRIPTION
**Pull request by mclasmeier**
## Description

This PR removes outdated references to the `stackrox.io` registry, which doesn't exist anymore, alongside references to the old `stackrox.io` image flavor.

There are other references to the `stackrox.io` domain, which are still perfectly valid.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## How these occurrences were identified

Essentially I have been using a command like the following to find potential problematic occurences:

```
rg \
  --no-heading \
  --only-matching "[^ \"'\`]*stackrox\.io[^:\"'\` ]*" \
  -g '!*.test.ts' \
  -g '!**/sensor/upgrader/common/metadata.go' \
  -g '!docker-auth.sh' -g '!PROJECT' \
  -g '!CHANGELOG.md' \
  -g '!50-images.yaml.htpl' \
  -g '!Dockerfile' \
  -g '!*_test.go' \
  -g '!*.test.yaml' \
  -g '!**/cypress/fixtures/clusters/*.json' \
  -g '!**/pkg/fixtures/image.go' \
  -g '!StaticConfigurationSection.js' \
  -g '!*.groovy' stackrox | \
  rg -v ".*:.*(\
/run/secrets/stackrox.io|\
/run/stackrox.io|\
quay.io/stackrox-io|\
platform.stackrox.io|\
network-policies\.stackrox\.io|\
auto-upgrade\.stackrox\.io|\
sensor-upgrader\.stackrox\.io|\
admission\.stackrox\.io|\
modified-by.stackrox.io|\
init-bundle.stackrox.io|\
stackrox.io/description|\
generator.stackrox.io/|\
metadata.stackrox.io|\
policyeval.stackrox.io|\
k8sevents.stackrox.io|\
/run/config/stackrox.io|\
pvc.stackrox.io|\
install.stackrox.io|\
charts.stackrox.io|\
collector-modules.stackrox.io|\
www.stackrox.io|\
bf7ea6a2.stackrox.io|\
golang.stackrox.io|\
install.stackrox.io/scanner|\
alpn.stackrox.io|\
stackrox.io/authz.metadata|\
upgrader.sensor.stackrox.io|\
stackrox.io/code-conduct|\
definitions.stackrox.io|\
stackrox.io/jwt|\
stackrox.io/pause-reconcile|\
stackrox.io/info|prevent.stackrox.io\
)" | \
  sort | uniq 
```

### CODE REVIEW

**Comment by Maddosaurus** [comment]
If possible, could you open WIP PRs as a draft in the future?
When not opened as draft, all code owners get tagged and notified immediately, which makes the GitHub notification inbox very hard to use.
Thanks!

**Comment by mclasmeier** [comment]
> If possible, could you open WIP PRs as a draft in the future? When not opened as draft, all code owners get tagged and notified immediately, which makes the GitHub notification inbox very hard to use. Thanks!

Of course, sorry for the noise.

**Review by fredrb — APPROVED** [review]
Looks good to me @mclasmeier, couldn't find anything that requires changing. 

The `opensource` flavor was a requirement to remove stackrox.io, but since that has been in place for a long time, there is no need to keep this flavor around.

I noticed that non-groovy tests are passing, which is a good sign that you didn't break the bats tests. 

Thanks for taking this!

**Pull request merged**
