### PR TITLE
tests: central and image prefetches metrics

### PR DESCRIPTION
**Pull request by porridge**
## Description

This is a slightly modified (more DRY and with improved naming) piece of #10822 from @janisz with additional support for saving/loading of metrics from the image prefetcher.

## Checklist
- [x] Investigated and inspected CI test results
- [x] ~Unit test and regression tests added~
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

### Here I tell how I validated my change

None, really, because I don't think I have the permissions to write to that GCS bucket nor bigtable.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]
> None, really, because I don't think I have the permissions to write to that GCS bucket nor bigtable.

CI should do it

**Comment by porridge** [comment]
The lone failure is unrelated. Metrics upload looks OK.

**Pull request merged**
