### PR TITLE
ROX-20399: Add mutable feature flag for policy criteria modal

### PR DESCRIPTION
**Pull request by vjwilson**
## Description

Pre-work for ROX-19032, "Policy Criteria, change from drag-and-drop"

This flag will allow for testing this feature on release builds.

It will also allow us to turn it off and go back to the old drag and drop criteria if needed.

## Checklist
- [x] Investigated and inspected CI test results

### Here I tell how I validated my change

Because this change only adds the feature flag, I plan to deploy the PR build image, and point a UI at it.

Manual tests:

1. With flag off by default and no environmental variable set, observe the response from the `/featureflags` API call and see that this flag is false.
2. With flag off by default but an environmental variable setting it to true, observe the response from the `/featureflags` API call and see that this flag is true.

Response with env off
Screen Shot 2023-10-24 at 6 17 27 PM

Response with env ON
Screen Shot 2023-10-24 at 6 22 07 PM

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by theencee — APPROVED** [review]

**Comment by pedrottimark** [comment]
As a separate pull request, can you add conditional skip in policyWizardStep3.test.js file, and then plan to add an alternative test file with the opposite conditional skip.

**Pull request merged**
