### PR TITLE
rox 13014 mock grpc server should record process info of endpoints

### PR DESCRIPTION
**Pull request by JoukoVirtanen**
## Description

For the processes listening on ports MVP we need to add process information to endpoints. We need integration tests for that in collector and we need the mock grpc server to record the process information that the endpoint messages have.

## Checklist
- [ ] Investigated and inspected CI test results
- [x] Used new grpc server in collector integration tests.

## Testing Performed

See above

### CODE REVIEW

**Comment by erthalion** [comment]
Thanks, looks reasonable. The only question I have is whether it's going to look readable? Other fields in this output are single values, where the originator is going to be a combination of three values (exe, args, path) somehow put together.

**Review by erthalion — APPROVED** [review]

**Comment by JoukoVirtanen** [comment]
> Thanks, looks reasonable. The only question I have is whether it's going to look readable? Other fields in this output are single values, where the originator is going to be a combination of three values (exe, args, path) somehow put together.

I have another PR which reads the output. You can find it here https://github.com/stackrox/collector/pull/870/files

I think at some point we might store these things in json.

**Pull request merged**
