### PR TITLE
test(ui): Add Cypress tests for Workload CVE overview page

### PR DESCRIPTION
**Pull request by dvail**
## Description

e2e tests for the Workload CVE overview page

1. Tests basic page properties and defaults
2. Test behavior of severity filter across the three entity tables

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI

### CODE REVIEW

**Comment by dvail** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7811** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7811" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7811?utm_source=stack-comment).

**Review by vjwilson — APPROVED** [review]
A couple of little questions

**Pull request merged**
