### PR TITLE
Sort out `openshift_*_e2e_tests.py` files and symlinks

### PR DESCRIPTION
**Pull request by msugakov**
## Description

Primarily per the idea in https://github.com/openshift/release/pull/36517#issuecomment-1435242209

See commit messages in individual commits.

The plan is to retest this after https://github.com/openshift/release/pull/36517

## Checklist
- [x] Investigated and inspected CI test results

No plans for these:
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

* CI must be green.

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]
LGTM. For the record, this remove helm tests in the OCP flavors but that is covered by other GKE e2e environments.

**Comment by msugakov** [comment]
@gavin-stackrox I decided to keep `openshift_oldest_qa_e2e_tests.py` but renamed to `openshift_helm_qa_e2e_tests.py` for future-us who would want to ensure OCP-Helm coverage in the testing matrix. Maybe that's not so distant future.

**Pull request merged**
