### PR TITLE
chore(scanner): update PGP key

### PR DESCRIPTION
**Pull request by RTann**
## Description

Updates include:

* New PGP key
  * PGP keys for Postgres RPMs are now stored in a different location and have different contents. See the `README.txt` in https://apt.postgresql.org/pub/repos/yum/keys/
* Actually import the PGP key for RPM verification
  * Somehow this was missed?

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

### Here I tell how I validated my change

trivial

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by RTann** [comment]
This was created as it was requested in a review for https://github.com/stackrox/stackrox/pull/9042

**Review by dcaravel — COMMENTED** [review]
Looks good to me, one question/comment regarding: 

> It is expected the indexer/matcher read this env var to determine which database to use for non-ClairCore DB requirements

Are the updates to read this in indexer/matcher part of another PR?

**Comment by RTann** [comment]
> Looks good to me, one question/comment regarding:
> 
> > It is expected the indexer/matcher read this env var to determine which database to use for non-ClairCore DB requirements
> 
> Are the updates to read this in indexer/matcher part of another PR?

Yes, the intention is to add this to another PR

> Looks good to me, one question/comment regarding:
> 
> > It is expected the indexer/matcher read this env var to determine which database to use for non-ClairCore DB requirements
> 
> Are the updates to read this in indexer/matcher part of another PR?

I'm going to remove the stuff about using the separate DB in favor of taking a step back to see how others feel about how to approach it

**Review by dcaravel — APPROVED** [review]
LGTM

**Pull request merged**
