### PR TITLE
fix: remove trailing punctuation from log

### PR DESCRIPTION
**Pull request by janisz**
## Description

This PR is for @rukletsov who do not like trailing dots (`.`) in log messages.

- https://github.com/stackrox/stackrox/pull/8613

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by RTann** [comment]
our logger automatically adds a period?

**Comment by janisz** [comment]
> our logger automatically adds a period?

Nope. Alex just do not like ending sentences with period ([source](https://github.com/stackrox/stackrox/pull/8476#discussion_r1389875805)) so I've created a linter so he do not need to review all PRs manually.

**Pull request closed without merging**
