### PR TITLE
Update navigation to use UX standardized badges

### PR DESCRIPTION
**Pull request by dvail**
## Description

Updates the sidebar navigation to communicate the status of new features in a standard way according to UX mocks from @zhenpesky . This currently only impacts the Workload CVE and Network Graph features.

_Easier to review with "Hide whitespace" turned on_

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Load the app and view the left hand navigation, with ROX_VULN_MGMT_WORKLOAD_CVES and ROX_POSTGRES_DATASTORE and ROX_NETWORK_GRAPH_PATTERNFLY enabled. Note that we are not officially deprecating any of the navigation items for VM 1.0 at this point, even if Workload CVEs are beginning their deprecation.

image
image

Load the app with ROX_NETWORK_GRAPH_PATTERNFLY disabled. (This is marked deprecated in the nav still, even with the FF off since we have previously released it as a deprecated version. I'm not sure having the flag disabled is even a valid consideration at this point.)
image

Load the app with ROX_VULN_MGMT_WORKLOAD_CVES disabled.
image

### CODE REVIEW

**Comment by dvail** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6227** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6227" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/6227?utm_source=stack-comment).

**Comment by dvail** [comment]
@zhenpesky just a heads up that the coloration of the "Deprecated" badge is a little different than what you provided in the mocks. The colors in the mocks had too low contrast which was violating our accessibility testing tool.

**Review by zhenpesky — APPROVED** [review]
@dvail LGTM

**Comment by pedrottimark** [comment]
> I'm not sure having the flag disabled is even a valid consideration at this point.

@dvail Indeed, conditional rendering NetworkGraphNavItems is obsolete.

**Review by pedrottimark — APPROVED** [review]
Approved, pending changes to fix integration test failures.

**Pull request merged**
