### PR TITLE
ROX-9617: Fold two functions into a single generic one.

### PR DESCRIPTION
**Pull request by porridge**
## Description

This was supposed to be an exercise in Go generics, but turned out that:
- generics don't actually help, since you cannot do `func bla[T whatever]() { obj := &T{} }` that would be required here (`invalid composite literal type`)
- generics are not required, since as of more recent controller-runtime versions one can achieve this result using an `UnstructuredList` and pass the GVK at runtime

## Checklist
- [ ] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

Relying on CI now that I added an e2e test for this functionality.
Also ran the e2e test manually and made sure it works.

### CODE REVIEW

**Comment by porridge** [comment]
https://github.com/stackrox/stackrox/pull/3281

**Review by misberner — APPROVED** [review]

**Comment by porridge** [comment]
Thanks for the tip, @misberner . However the result is still problematic for another reason:
```
pkg/reconciler/reconciler_factory.go:99:26: list.Items undefined (type T has no field or method Items)
```
AFAICT accessing the `Items` field is the only way to iterate over the items :-/

**Comment by porridge** [comment]
The operator tests and all required tests passed, which is all matters here, merging.

**Pull request merged**
