### PR TITLE
feat(qa): Update to downstream ACS build 4.5.4-x stable

### PR DESCRIPTION
**Pull request by mdafsanhossain**
### Description

Same as title. Updates iibs to 4.5.4 build for `ppc64le` and `s390x`.

### User-facing documentation

- [ ] CHANGELOG is updated **OR** update is not needed
- [ ] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [ ] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [ ] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

Validated with successful deployment of images in CI.

### CODE REVIEW

**Comment by mdafsanhossain** [comment]
@porridge Can you approve this PR? It updates the image.

**Comment by tommartensen** [comment]
@mdafsanhossain can you re-run the e2e tests on power and fill out the PR template? Thank you!

**Comment by mdafsanhossain** [comment]
The e2e test will fail mid-way since we still don't have the image-prefetcher enabled for p/z but atleast stackrox should deploy with these images.

**Comment by porridge** [comment]
> The e2e test will fail mid-way since we still don't have the image-prefetcher enabled for p/z

FTR, I added @jdao-rh as reviewer on https://github.com/stackrox/stackrox/pull/13259 but received no feedback so far, perhaps you can take a look @mdafsanhossain ?

**Review by porridge — APPROVED** [review]
LGTM modulo what Tom said.

**Pull request merged**
