### PR TITLE
ROX-23463: Bump Collector version

### PR DESCRIPTION
**Pull request by erthalion**
## Description

Use 3.18.2 (without bumping modules version) to include workarounds for limiting number of ring buffers.

## Checklist
- [x] Investigated and inspected CI test results
~- [ ] Unit test and regression tests added~
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

### Here I tell how I validated my change

The fix was manually exercised on large machines where the issue could be triggered:
* Spin up n2-standard-128
* Run Collector with memory limit 1Gi
* There should be no initialization crash
* Memory usage should be approximately half of what it was before

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by vikin91 — APPROVED** [review]

**Comment by erthalion** [comment]
> /retest-required

The Collector image for a new tag wasn't ready yet.

**Pull request merged**
