### PR TITLE
ROX-27323: Suport hostname in LB ingress.

### PR DESCRIPTION
**Pull request by porridge**
### Description

The ticket in $SUBJECT collected failures of the following jobs:
- `rosa-qa-e2e-tests`
- `rosa-hcp-qa-e2e-tests`
- `eks-qa-e2e-tests`
- `eks-qa-ebpf-e2e-tests`
- `osd-aws-qa-e2e-tests`

Apparently on ROSA, EKS and OSD-AWS the load balancer reports the ingress endpoint through the `.hostname` key rather than `.ip`.

Added support for this, along with BATS unit tests.

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [x] CI results are inspected

#### Automated testing

- [x] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [x] modified existing tests

#### How I validated my change

Triggered the previously problematic jobs.

### CODE REVIEW

**Review by mtodor — APPROVED** [review]
This PR is really nicely done.

From description and logs:
```
curl: (6) Could not resolve host: null
```
it's clear what is going on. Tests also cover possible variations.

**Comment by porridge** [comment]
`rosa-qa-e2e-tests` failure seems unrelated - kube API flake when polling for central to become ready

**Comment by porridge** [comment]
- `osd-aws-qa-e2e-tests` failure also seems unrelated

**Pull request merged**
