### PR TITLE
ROX-18195: Add ProcessesListeningOnPortsTest to the parallel set

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

This PR makes some changes to `ProcessesListeningOnPortsTest.groovy` to support parallel execution (i.e. a unique namespace for the test) as well as some minor test flow and orchestrator call use refactoring. With this change there are now 2 concurrent tests in Groovy e2e tests, DeclarativeCongfigTest & ProcessesListeningOnPortsTest.

It also changes logging to undo the prior attempt to get a normalized thread description and replaces it with a test specification context logline to help correlate logs to test. Dealing with test output in a concurrent test world in a viable manner is still something of a work in progress, but at least for this change the output looks good to me. 

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

CI++

- [x] ran a 100x loop of `./gradlew testParallel`, all tests passed.
- [x] force a failure of DeclarativeCongfigTest and verify the failure is identified correctly and can be found in the log.
   - fails as [expected](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6806/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1676017285329850368).
   - failure logs are difficult but not impossible to parse.
- [x] force a failure of ProcessesListeningOnPortsTest and verify the failure is identified correctly and can be found in the log.
   - fails as [expected](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6806/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1676646735482458112).
   - logs are OK.

### CODE REVIEW

**Comment by gavin-stackrox** [comment]
cc @dhaus67 as this change may impact DeclarativeConfigTest (but shouldn't, so just a heads up).

**Comment by JoukoVirtanen** [comment]
"force a failure of DeclarativeCongfigTest and verify the failure is identified correctly and can be found in the log."
"force a failure of ProcessesListeningOnPortsTest and verify the failure is identified correctly and can be found in the log."

How were the failures forced?

**Comment by JoukoVirtanen** [comment]
Can you link to the previous PR for DeclarativeCongfigTest

**Comment by gavin-stackrox** [comment]
> "force a failure of DeclarativeCongfigTest and verify the failure is identified correctly and can be found in the log." "force a failure of ProcessesListeningOnPortsTest and verify the failure is identified correctly and can be found in the log."
> 
> How were the failures forced?

Unfortunately, I dropped those commits. The test results are:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6806/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1676646735482458112
and
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/6806/pull-ci-stackrox-stackrox-master-gke-qa-e2e-tests/1676017285329850368

**Comment by gavin-stackrox** [comment]
> Can you link to the previous PR for DeclarativeCongfigTest?

https://github.com/stackrox/stackrox/pull/6689

**Review by JoukoVirtanen — APPROVED** [review]
LGTM!

**Pull request merged**
