### PR TITLE
chore(proto): replace jsonpb with jsonutil

### PR DESCRIPTION
**Pull request by janisz**
### Description

This PR replaces deprecated jsonpb with jsonutil with backward compatible `Marshal` implementation. This is first part of `jsonpb` replacement the second is here: https://github.com/stackrox/stackrox/pull/12367/files

- [x] CHANGELOG update is not needed
- [x] Documentation is not needed
### Testing
- [x] inspected CI results
#### Automated testing
- [x] modified existing tests
- [x] contributed **no automated tests**
#### How I validated my change
CI

### CODE REVIEW

**Comment by vikin91** [comment]
Could you make sure that the compatibility is not affected by this change? We used to have problems with that in the past: https://issues.redhat.com/browse/ROX-14188

**Comment by janisz** [comment]
@vikin91 I think the issue you mentioned is not related as this is only about marshaling

**Review by 0x656b694d — APPROVED** [review]

**Review by rhybrillou — APPROVED** [review]
Would it make sense to add a linter to prevent usage of jsonpb (validateimports would be the location) ?

**Pull request merged**
