### PR TITLE
Use retry in DeploymentEventGraphQLTest

### PR DESCRIPTION
**Pull request by janisz**
## Description

Currently we use plain loop with assertions in it's body. So when condition is not satisfied we never retry.
This PR replaces for-loop with retry and return unecessary returns.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3047** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3047" target="_blank">Graphite</a> 
    * **PR #3048** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3048" target="_blank">Graphite</a> 
      * **PR #3049** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3049" target="_blank">Graphite</a> 
        * **PR #3050** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3050" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3050?utm_source=stack-comment).

**Review by RTann — APPROVED** [review]

**Comment by janisz** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3050?utm_source=stack-comment).


Job Reference: EWf7JXZwBVjaRD9hhYFV

**Comment by gavin-stackrox** [comment]
Adding `set -x` to diagnose the `get_pr_details()` failure gets an all green run.
Reverting that caused the failure to reoccur. 
https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=3050
So this "Could not determine if this is a PR versus a merge" failure requires some more research.

@janisz I am passing this PR back to you. Depending on how https://github.com/stackrox/stackrox/pull/3073 goes, you might want to rebase on that so that at least tests run.

**Pull request merged**
