### PR TITLE
build: Drop clamav-scan resource requests

### PR DESCRIPTION
**Pull request by msugakov**
### Description

Let the Konflux team manage these resources as they seem to be on track of doing that
https://github.com/konflux-ci/build-definitions/pull/1247

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [x] CI results are inspected

#### Automated testing

No changes to automated testing.

#### How I validated my change

Only CI.

### CODE REVIEW

**Review by tommartensen — APPROVED** [review]

**Comment by msugakov** [comment]
Some last failures
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-gzlhc
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-5h94w
- https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-7mbdh

`build-source-image` (https://issues.redhat.com/browse/KFLUXBUGS-1508) obviously fails us.
Fortunately, [main-build-5h94w](https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/main-build-5h94w) shows that `clamav-scan` succeeded.

I'm going to merge it.

**Pull request merged**
