### PR TITLE
refactor(pg): remove unused context arg

### PR DESCRIPTION
**Pull request by janisz**
## Description

`insertInto` has context param that is not used. This PR removes it. 

## Checklist
- [x] Investigated and inspected CI test results

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7050** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7050" target="_blank">Graphite</a> 
    * **PR #7051** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7051" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7051?utm_source=stack-comment).

**Review by rhybrillou — APPROVED** [review]

**Comment by janisz** [comment]
@janisz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7051).

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7051) couldn't merge this PR because it had conflicts with the trunk branch.

**Review by connorgorman — APPROVED** [review]

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7051) rebased this pull request as part of a merge.

**Comment by janisz** [comment]
@janisz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7051).

**Pull request merged**
