### PR TITLE
ROX-14973: Various fixes for release-3.73

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

WIP.

## Picked so far

1e0fd6ff29 Drop PodSecurityPolicy from errors files. (#4774)
eb1b45f04c Start using the batch/v1 api for CronJobs (#3854)
5e1595c454 ROX-14485: update monitoring psp (#4655)
f5baf265f9 ROX-14427: set PSPs for CI to false for k8s version 1.25 and higher (#4488)
42719ea90b ROX-12856: roxctl: Make sure that PSPs are not rendered for deployment bundles (#3230)

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

CI is sufficient

### CODE REVIEW

**Comment by robbycochran** [comment]
Do we also need https://github.com/stackrox/stackrox/pull/4813 ?

**Comment by gavin-stackrox** [comment]
Whatabout #3787 that was on Jouko's 3.72 PR #4790

**Comment by robbycochran** [comment]
> #3787

That's already on 3.73, but we will need it for 3.72.

**Comment by msugakov** [comment]
Q about `grouped-static-checks` https://srox.slack.com/archives/CMH5M8MHN/p1676290246758339

**Comment by gavin-stackrox** [comment]
> @gavin-stackrox I order to fix `grouped-static-checks` failures, we need this file https://github.com/stackrox/stackrox/pull/3820/files#diff-4771170f9cb1ab90b7940d157dccf8aae343b2b5fe5070f8cd8bdd4fde2aafc4
> 
> You can get it via
> 
> ```shell
> git co ce14d08a24250612ba4d66fd723f83d998c0c569 -- central/deployment/store/postgres/gen.go
> ```

This did not work for me. And I could not find a way to include a single file change from a commit. So I manually went with c9d879b.

> Also, this one #4837 should help deal with `stringer` issues.

Picked.

**Review by msugakov — APPROVED** [review]

**Pull request merged**
