### PR TITLE
Simplify theme for SimulationFrame in Network Graph 1.0

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

Prerequisite simplification to solve insufficient color contrast issues elsewhere.

### Problems

1. Classic theme has subtle lightness distinctions within a hue:
    * Even if foreground and background have sufficient contrast, lightness distinctions probably do not.
    * Especially for red, PatternFly has fewer distinctions.

2. Color in template makes it hard for us or Tailwind to know which classes are in use.

    * src/Components/SimulationFrame.tsx 14 `flex items-center bg-${colorType}-700 text-base-100 font-600 uppercase p-2 mt-1 hover:bg-${colorType}-800`
    * src/Components/SimulationFrame.tsx 17 `mr-2 w-4 h-4 text-${colorType}-100`
    * src/Components/SimulationFrame.tsx 32 `bg-${colorType}-600 text-base-100 font-600 uppercase p-2 ml-1 mt-1`
    * src/Containers/Network/SidePanel/Simulator/Simulator.tsx 48 `bg-${colorType}-600 hover:bg-${colorType}-700`

4. Indirect reference to theme colors in css file is very subtle.

### Analysis

1. Use 700 level for alert and success because it is most common for non-base colors.

2. Specify colors via full class names:
    * before:text for box shadow
    * border for label and button
    * bg for label

3. Use plain bg, bg:hover, and text colors for button at upper left.

4. Adding insult to injury, `hover:bg-alert-300` in `CloseButton` element at upper right wins over conditional classes because of rule order in app.tw.css file:

### Solution

1. Replace conditional stop button colors with `text-base-600 hover:bg-base-200` like many other buttons.

2. Replace background color of frame with either `bg-alert-700` or `bg-success-700` class. Because Network Graph 1.0 is deprecated, and therefore this component will become obsolete, specify classes in the file.

3. Replace conditional background color of `CloseButton` element with neutral color because its inherent hover color is alert, which looks strange when the non-hover color is success (see below).

4. Delete indirect color references and conditional style rules for box shadow in app.tw.css file.

## Checklist
- [x] Investigated and inspected CI test results
- [x] ~Unit test and regression tests added~

#### Simulation success

complicated theme with classic colors
success_Tailwind

simplified theme mapped to PatternFly colors (coming soon)
success_PatternFly

#### Simulation failure

complicated theme with classic colors
alert_Tailwind

simplified theme mapped to PatternFly colors (coming soon)
alert_PatternFly

#### Simulator close button

A nuance that I missed at first:
* Click **Network Policy Simulator** to open Creator.
* And then click **Generate and simulate network policies** to open Simulator.

Close button is green for simulator success
Simulator_success

Close button hover is red regardless of simulator success or failure
Simulator_hover

### CODE REVIEW

**Comment by sachaudh** [comment]
The button next to the label for the simulation frame does look a bit odd in white compared to the green/red. I don't know if I'm a big fan of that 🤔

**Comment by pedrottimark** [comment]
Here are updated pictures for button after replacing base with success and alert background colors.

First I tried as analogy to PatternFly 50 the pair of classic 200 and hover 300, but was concerned that y’all might think (or maybe better to say, someone with limited color vision might think) the pale tint was too close to whitish gray.

bg-success-300
SimulationFrame_success_300

hover:bg-success-400
SimulationFrame_success_400

bg-alert-300
SimulationFrame_alert_300

hover:bg-alert-400
SimulationFrame_alert_400

Although it is water under the bridge at this point in the life of classic Network Graph, I am curious if there is a difference between **Stop** button at upper left and ordinary close button at upper right? Until I searched for unique color contrast combinations, I had always clicked the close button because I never even noticed the **Stop** button.

Network Graph 2.0 has only a close button at the upper right of the side panel.

**Comment by zhenpesky** [comment]
> Although it is water under the bridge at this point in the life of classic Network Graph, I am curious if there is a difference between **Stop** button at upper left and ordinary close button at upper right? Until I searched for unique color contrast combinations, I had always clicked the close button because I never even noticed the **Stop** button.
From a UX perspective, If they are the exact same functionality I would also suggest removing the stop button. First, there is only one close action needed and we have the user behavior to close a view using the icon on the right across products. Second, the only intention of the stop button was to imply this view is simulating and users see the changes in live action but the stop button could have been used in a more complex behavior/scenario than what we needed on the current behavior in the network graph.

**Comment by sachaudh** [comment]
Yea @pedrottimark maybe we can remove the stop button and not have to deal with the above contrast issue. It will be deprecated soon so no need to do too much in this area

**Comment by pedrottimark** [comment]
Superseded by deletion of Network Graph 1.0 in #6699 #6825 #6827

**Pull request closed without merging**
