### PR TITLE
fix(check-pr): increase max length of PR title

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

I'd favor to increase the length of the PR title, it's currently a bit hard to create meaningful PR titles with the current limitations of 70 characters.

As examples:
- https://github.com/stackrox/stackrox/pull/6309
- https://github.com/stackrox/stackrox/pull/6378

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6389** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/6389" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/6389?utm_source=stack-comment).

**Comment by 0x656b694d** [comment]
The 70 characters limitation comes from GitHub UI limitations. See https://github.com/stackrox/stackrox/pull/6107#issuecomment-1579030158.

**Comment by 0x656b694d** [comment]
> fix(enricher): Ensure image names are used in image enricher
61 characters already

> ROX-13888: Migrate permission sets referencing Policy and VulnerabilityReports resources
Could be "ROX-13888: Migrate permission sets referencing deprecated resources" (68)

**Comment by janisz** [comment]
I'd prefer to keep lower limit as github and Linux follow it as well https://github.com/stackrox/stackrox/pull/6378

**Pull request closed without merging**
