### PR TITLE
fix(be): Expose all v2 APIs in docs

### PR DESCRIPTION
**Pull request by charmik-redhat**
### Description

When v2 APIs were newly introduced, we did not want to document them right away before they were ready to become GA. So we created a list of v2 APIs that are ready to go in api docs so that only those APIs are exposed. Now that v2 APIs have existed since a couple of releases, we should change the implementation to allow all v2 APIs to be exposed in docs.

### User-facing documentation

(*must be* 2 items and both *must be* checked)

- [X] Documentation is not needed

### Testing

- [ ] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [X] contributed **no automated tests**
   Verifying that all v2 APIs are present in API docs is enough
  

#### How I validated my change

Manual verification

9D728FBE-E4C8-49C3-8782-26CE15756F02

### CODE REVIEW

**Comment by porridge** [comment]
@charmik-redhat FYI since rc1 is stable there will most likely not be an rc2

**Review by dashrews78 — APPROVED** [review]
LGTM

**Comment by charmik-redhat** [comment]
> @charmik-redhat FYI since rc1 is stable there will most likely not be an rc2

That is fine. This change can go in a patch.

**Pull request merged**
