### PR TITLE
ROX-14780: Disable re-sync when deploying ACS with deploy.sh

### PR DESCRIPTION
**Pull request by fredrb**
## Description

Disable re-sync when deploying ACS using `deploy/k8s` scripts. 

## Checklist
- [x] Investigated and inspected CI test results
- [ ] ~~Unit test and regression tests added~~
- [ ] ~~Evaluated and added CHANGELOG entry if required~~
- [ ] ~~Determined and documented upgrade steps~~
- [ ] ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

## Testing Performed

- [x] Deploying ACS using the updated script and check that resync is really disabled.

### CODE REVIEW

**Review by Maddosaurus — CHANGES_REQUESTED** [review]
The change itself looks good to me!
Why I am requesting changes:

Have you tried this on an OpenShift cluster? 
AFAIK even `deploy/openshift/deploy.sh` calls `common/k8sbased.sh`, which would also disable resync on OpenShift clusters, wouldn't it?
The question is whether this is a problem or not.

In case this is not a problem at all, let me know and I'll approve the PR 😸

**Comment by fredrb** [comment]
> AFAIK even deploy/openshift/deploy.sh calls common/k8sbased.sh, which would also disable resync on OpenShift clusters, wouldn't it?

It does, but that's why this is guarded by an env check:
```bash
if [[ -n "$ROX_RESYNC_DISABLED" ]]; then # Only disable if ROX_RESYNC_DISABLED is set 
    kubectl -n stackrox set env deploy/sensor ROX_RESYNC_DISABLED="true"
fi
```

And `ROX_RESYNC_DISABLED="true"` is only set on the k8s specific path: `deploy/k8s/sensor.sh`. If you check `deploy/openshift/deploy.sh` you'll notice that it doesn't set this env. 

However, you comment just made me realise that we're only checking if the env is set, not its content. Meaning that if for some reason you export `ROX_RESYNC_DISABLED="false"` in your env before running Openshift deploy, it will _incorrectly_ disable the re-sync.

**Review by lvalerom — APPROVED** [review]
LGTM

**Review by Maddosaurus — APPROVED** [review]
Ah, thanks for your comment and the fix!
Completely missed the fact you only set the env var in `/k8s/sensor.sh`, but happy to hear this lead to a fix 😹

**Pull request merged**
