### PR TITLE
fix: update snappy url

### PR DESCRIPTION
**Pull request by 0x656b694d**
Use the EOL el8 snappy version from the vault instead of picking from el9.

### CODE REVIEW

**Review by mtodor — APPROVED** [review]

**Review by tommartensen — APPROVED** [review]
LGTM if it builds.

**Review by msugakov — APPROVED** [review]

**Comment by msugakov** [comment]
Please make sure to check e2e test results before merging. At the very least, StackRox should start and pass some tests.

**Comment by 0x656b694d** [comment]
> LGTM if it builds.

if it builds it sits

**Pull request merged**
