### PR TITLE
tests: auto \retest all PRs

### PR DESCRIPTION
**Pull request by janisz**
### Description

This PR introduces auto-retesting for all PRs targeting master. Previously, this was an opt-in feature, but it will now be automatically enabled for everyone. To opt out of auto-retesting, simply remove the auto-retest label. This change aims to help identify flaky tests and ensure tests pass eventually.

Refs:
- https://github.com/stackrox/stackrox/pull/12074
- https://github.com/stackrox/stackrox/pull/10635
- https://github.com/stackrox/stackrox/pull/10438

---

- [x] CHANGELOG update is not needed
- [x] Documentation is not needed
### Testing
- [x] inspected CI results
#### Automated testing
- [x] modified existing tests
- [x] contributed **no automated tests**
#### How I validated my change
CI

### CODE REVIEW

**Comment by BradLugo** [comment]
We don't necessarily have a budget for CI (at least, not one that I'm aware of), but we should be vigilant about this change.

cc @stackrox/infra

**Review by tommartensen — CHANGES_REQUESTED** [review]
> We don't necessarily have a budget for CI (at least, not one that I'm aware of), but we should be vigilant about this change.

GitHub Actions runs are free, because this is a public repository. 

OpenShift CI runs however are accruing costs for the clusters we provision in our cost center. Engineers would re-run until they have a green run as well. I rather see the problem of someone breaking a test (true negative) and this thing retriggering the job although it's not a flake. 

I might not have all context, but a few questions:

1. IIUC this PR adds `auto-retest` label to all PRs if they target master branch?
2. What does the "bot" do to retrigger failed tests? A blanko `/retest` or `/test name-of-failed-job`? Can we teach it to retrigger GHA as well?
3. You mention that "[t]his change aims to help identify flaky tests" - how? AFAICT it hides them with retries.

**Comment by janisz** [comment]
> What does the "bot" do to retrigger failed tests? A blanko /retest or /test name-of-failed-job? Can we teach it to retrigger GHA as well? Does it detect failed Konflux checks (we know that enterprise-contract always fails at the moment, so re-runs there would be less than ideal)?

It uses `/retest`. Currently it does not check on konflux nor retest GHA but we can teach it anything we want as it lives in https://github.com/stackrox/stackrox/tree/master/tools/retest

> You mention that "[t]his change aims to help identify flaky tests" - how? AFAICT it hides them with retries.

Correct it hides some information but we collect tests results so we can see how many jobs filiped from red to green for the same commit.

**Comment by janisz** [comment]
Closing as there is not much interest in this.
@mtodor Feel free to reopen if you still think we should have it

**Pull request closed without merging**
