### PR TITLE
chore(deps): upgrade go to 1.21

### PR DESCRIPTION
**Pull request by janisz**
## Description

This PR backports:
- #10305
- https://github.com/stackrox/stackrox/pull/10514
- https://github.com/stackrox/stackrox/pull/10375

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by RTann** [comment]
Is this needed in 4.4?

**Comment by janisz** [comment]
I needed this branch to fix upgrade test but I found a better solution:
- https://github.com/stackrox/stackrox/pull/10559
Still I think we should upgrade to 1.21 to fix known issues with our binaries and to make updates easier in the future as we need to maintain 4.4.0 for some time and Go 1.20 is not supported.

**Review by c-du — APPROVED** [review]

**Review by stehessel — CHANGES_REQUESTED** [review]
We need to wait with the bump until golang 1.21 dev tool images (RHEL 8.10) are available. Those are scheduled to release on `2024-05-14` (see https://docs.engineering.redhat.com/pages/viewpage.action?pageId=146918125).

**Comment by janisz** [comment]
Closing this could be reopend on 14th of May

**Pull request closed without merging**
