### PR TITLE
ROX-22101: use gogo TimestampProto through abstraction layer

### PR DESCRIPTION
**Pull request by rhybrillou**
## Description

The goal is to remove direct calls to the gogo protobuf layer and have all of them happen through an abstraction layer in order to ease the migration to a new protobuf library.

This PR moves the calls to TimestampProto from the gogo protobuf package to the protocomapt abstraction layer.

The change is the application through the refactoring tool `eg` of the following template:

```
package refactor

import (
	"time"

	gogoProto "github.com/gogo/protobuf/types"
	"github.com/stackrox/rox/pkg/protocompat"
)

func before(t time.Time) (*gogoProto.Timestamp, error) {
	return gogoProto.TimestampProto(t)
}

func after(t time.Time) (*gogoProto.Timestamp, error) {
	return protocompat.ConvertTimeToTimestampOrError(t)
}
```

PR stack:
- #9148
  - #9156 
  - #9145 
  - #9196 
  - #9198
  - #9201

## Checklist
- [ ] Investigated and inspected CI test results
~~- [ ] Unit test and regression tests added~~
~~- [ ] Evaluated and added CHANGELOG entry if required~~
~~- [ ] Determined and documented upgrade steps~~
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI run.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by dhaus67 — COMMENTED** [review]
Changes look good, however is there any plan to a) include the `eg` template within the current code base and b) execute this within CI in e.g. the generated source step?

Right now, there's no way telling that you got the latest changes (or even used the template you provided in the PR description) or prevent people from adding code that _does not_ use the compatibility layer.

Back when we first talked about the migration, this was one of the plans initially to make use of `eg` within CI as well (and potentially also introduce `roxvet` analyzers for that).

**Comment by rhybrillou** [comment]
> Changes look good, however is there any plan to a) include the `eg` template within the current code base and b) execute this within CI in e.g. the generated source step?
> 
> Right now, there's no way telling that you got the latest changes (or even used the template you provided in the PR description) or prevent people from adding code that _does not_ use the compatibility layer.
> 
> Back when we first talked about the migration, this was one of the plans initially to make use of `eg` within CI as well (and potentially also introduce `roxvet` analyzers for that).

I do not plan to integrate the eg templates in the codebase yet. My idea would rather be to aim at applying all required changes in order to be able to ban the `github.com/gogo/protobuf` imports in the codebase (with the obvious exception of the compatibility layer).
A few challenges I faced using `eg` are (potentially linked to the version I do use, but I imported `latest`):
- the tool seems to expect the target go files to have all imports present in the template. In most cases, the imports needed for the `after` part are not yet in the files that require changes. This therefore requires a pre-processing step outside of IDE (the IDE I use automatically removes the unused imports without asking most of the time). I think eg allows the application of a pre-processing script, but I have not reached the point where I could squeeze the required import in the import list at the correct position in a scripted manner.
- the tools does not perform any post-application re-validation of the imports and therefore requires a post-processing step to trim away the imports that are not used anymore.
- the application of template is best performed on a per-file basis, possibly at package (directory) level, but does not seem to offer recursive application on a whole filesystem.

At the moment, I rely on my IDE to tell me where the function I want to use through the compatibility layer is used, have a pre-processing pass on the list of files to add the imports needed for template application, run `eg` file by file on the result of the previous lookup, and re-open the files in the IDE to check for required import removals.

I do welcome ideas to improve and automate that process, though.

**Review by md2119 — COMMENTED** [review]
I have the following thoughts:
1.  `/pkg/protoconv/` would be a more suitable location for the conversion functions. `protoconv` has a few type converters that are used in the codebase, therefore, it seems natural that developers would go looking for type converters there.
2. If you have already replaced all the timestamp conversions in this PR, then you can push the `roxvet` validation through this PR by updating [validateimports/analyzer.go](https://github.com/stackrox/stackrox/blob/e471609d00e0b5e1de9412d9cae963ba11733c96/tools/roxvet/analyzers/validateimports/analyzer.go)

**Review by mtodor — APPROVED** [review]
Adjust the list of cleaned packages if needed.

**Pull request merged**
