### PR TITLE
feat(qa): Update midstream index images to use build v4.4.1-4

### PR DESCRIPTION
**Pull request by pratham-m**
This PR updates index images (used for ACS deployment via downstream builds) for `ppc64le` and `s390x` platforms.

### CODE REVIEW

**Comment by pratham-m** [comment]
On `Power` 
- 4.13 passed
- 4.14/15 have known flaky failures
- 4.12 executed separately downstream

**Review by jdao-rh — APPROVED** [review]

**Comment by pratham-m** [comment]
hi @gavin-stackrox @robbycochran can you kindly approve the PR?

**Comment by pratham-m** [comment]
Thanks Gavin. 
Merging the PR.

**Pull request merged**
