### PR TITLE
Fix docs/Makefile git submodule command is not plural

### PR DESCRIPTION
**Pull request by msierks**
## Description

As far as I can tell, the git submodule command should not be pluralized.

## Testing Performed

No testing done, this change is purely informational.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Comment by msierks** [comment]
@msugakov  This PR has been stagnant for some time, is there a different process I should be following?

**Comment by msierks** [comment]
Appears to have been fixed not long after this PR was opened, closing.

**Comment by msugakov** [comment]
Well, it looks like this PR fell through the cracks and did not appear in the triage dashboard we're using. Let me follow up on this internally.
Meanwhile, I'd suggest you add `Reviewers` using GitHub suggestion (i.e. people who recently edited changed files and who recently reviewed edited files). This at least should give some visibility in the team.

**Comment by msierks** [comment]
Doesn't appear I have the ability to add or edit reviewers.

**Comment by msugakov** [comment]
Sorry to hear this but thank you for checking! There's definitely something about the process that must be improved on our side. I'll follow up on this.

**Pull request closed without merging**
