### PR TITLE
Implement basic markup structure of collection form

### PR DESCRIPTION
**Pull request by dvail**
## Description

Adds the main layout of the collection form page, with empty components stubbed in where they will be located once implemented.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~~Unit test and regression tests added~~
- [ ] ~~Evaluated and added CHANGELOG entry if required~~
- [ ] ~~Determined and documented upgrade steps~~
- [ ] ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

## Testing Performed

Visit the main collections page and click the "Create collection" button. If on a large screen, the preview drawer should be open by default. If on a small screen, the preview drawer should be closed.
image
image

Test that resizing the browser window beyond the "large" threshold sets the preview drawer state to open (when the window is large) and closed (when the window is small).

Test that clicking the "Hide preview results" button closes the drawer and updates the button text. Test that clicking the button again re-opens the drawer.
image

Test the the drawer open state in the small screen view results in an "overlay" drawer, as opposed to the drawer the pushes the content to the left in the large screen view.
image

Test that the top level "Collections" link in the breadcrumbs takes you back to the main collections table page.
image

Test the visiting a page in "Create", "Clone", or "Edit" mode removes the action menu and places a "Save" and "Cancel" button in the page footer.
image

### CODE REVIEW

**Comment by dvail** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3348** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3348" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3348?utm_source=stack-comment).

**Review by pedrottimark — APPROVED** [review]
Markup structure is clear. A question and a thought as you continue step by step:
* Does view display a live preview of current results? That is, without editing.
    UI has either precedent: access scope does and policy does not.
* It seems worthwhile to see how form state (if you intend to use formik) and validation criteria (if you intend to use yup) fit together with the rendering tree somewhere in the middle instead of at the end of fleshing out form elements.

**Comment by dvail** [comment]
Yep, the intention is the the read-only view displays the page load time results in the right side panel.

I haven't had a ton of experience with formik, so I'll take a look at that next to see if and how it fits in for this use case.

**Comment by pedrottimark** [comment]
Capabilities of formik might overlap with `FormStateReducerAction` in #3372
For example, https://formik.org/docs/api/formik#setfieldvalue-field-string-value-any-shouldvalidate-boolean--void
Although text inputs do not even need to call that function directly.

**Pull request merged**
