### PR TITLE
ROX-17414: remove duplicated existence check

### PR DESCRIPTION
**Pull request by janisz**
## Description

This PR removes superfluous code and reduces memory use for > 90%.

In `Control` implementation we do heavy operation of creating new object (`ToProto`)
https://github.com/stackrox/stackrox/blob/1bc6e2e294ee09a3cfffa8cfad5d11e4c20acf59/central/compliance/standards/registry.go#L212-L217
This is not necessary as in `GetCategoryByControl` we access the same element (`r.controlsByID[controlID]`) and return it without any modifications.
By removing first check we can significantly reduce number of allocations.

https://github.com/stackrox/stackrox/blob/1bc6e2e294ee09a3cfffa8cfad5d11e4c20acf59/central/compliance/standards/registry.go#L201-L209

```bash
# go test -bench=. ./central/compliance/aggregation/... -benchtime=10s -benchmem -count 10

name                 old time/op    new time/op    delta
AggregatedResults-8     175ms ± 1%     153ms ± 2%  -12.22%  (p=0.000 n=10+10)

name                 old alloc/op   new alloc/op   delta
AggregatedResults-8    13.0MB ± 0%     0.0MB ± 1%  -99.99%  (p=0.000 n=9+10)

name                 old allocs/op  new allocs/op  delta
AggregatedResults-8     90.0k ± 0%      0.0k ± 0%  -99.99%  (p=0.000 n=10+10)
```

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7327** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7327" target="_blank">Graphite</a> 
    * **PR #7328** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/7328" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7328?utm_source=stack-comment).

**Review by connorgorman — APPROVED** [review]

**Review by rhybrillou — APPROVED** [review]

**Comment by janisz** [comment]
@janisz started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7328).

**Comment by janisz** [comment]
[Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7328) rebased this pull request as part of a merge.

**Comment by janisz** [comment]
@janisz merged this pull request with [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/7328).

**Pull request merged**
