### PR TITLE
ROX-21731: Service integration test flake fix

### PR DESCRIPTION
**Pull request by fredrb**
## Description

Uses correct assertion function

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
- [ ] ~~Evaluated and added CHANGELOG entry if required~~
- [ ] ~~Determined and documented upgrade steps~~
- [ ] ~~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

### Here I tell how I validated my change

Tests passing 

- [ ] 5 green integration tests

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by lvalerom — APPROVED** [review]

**Comment by fredrb** [comment]
2/5 ✅
/test gke-sensor-integration-tests

**Comment by fredrb** [comment]
3/5 ✅
/test gke-sensor-integration-tests

**Comment by fredrb** [comment]
4/5 ✅
/test gke-sensor-integration-tests

**Comment by fredrb** [comment]
5/5 ✅ :ship:

**Pull request merged**
