### PR TITLE
ROX-21053: roxctl netpol generate - allow users to set custom dns port

### PR DESCRIPTION
**Pull request by zivnevo**
## Description

Adding the optional flag `--dnsport` to `roxctl netpol generate`, allowing users to set a custom DNS port for egress rules in the generated NetworkPolicy resources.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

Added a test to `tests/roxctl/bats-tests/local/roxctl-netpol-generate-release.bats` and to `tests/roxctl/bats-tests/local/roxctl-netpol-generate-development.bats`. This test uses the new flag and verifies that the new port is indeed being used in the output NetworkPolicies.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by lvalerom** [comment]
@zivnevo I think this PR needs a rebase to solve some of the CI failures

**Comment by zivnevo** [comment]
> @zivnevo I think this PR needs a rebase to solve some of the CI failures

Done

**Comment by vikin91** [comment]
I am running CI checks in a clone-PR: #10597

**Comment by zivnevo** [comment]
> It looks like now all unit tests from `TestGenerateNetpol` are failing:
> 
> ```
> === RUN   TestGenerateNetpolCommand/TestGenerateNetpol/not_existing_inputFolderPath_should_raise_'does_not_exist'_error
>     generate_test.go:137: 
>         	Error Trace:	/__w/stackrox/stackrox/roxctl/netpol/generate/generate_test.go:137
>         	            				/go/pkg/mod/github.com/stretchr/testify@v1.9.0/suite/suite.go:115
>         	Error:      	Received unexpected error:
>         	            	illegal port number: must be between 1 and 65535, inclusive
>         	Test:       	TestGenerateNetpolCommand/TestGenerateNetpol/not_existing_inputFolderPath_should_raise_'does_not_exist'_error
> ```
> 
> (src in my clone of this PR: https://github.com/stackrox/stackrox/actions/runs/8555988379/job/23444700984?pr=10597)
> 
> I think, we must check if the flag is correctly setting the default value, or whether the validation works well when `--dnsport` is not specified.

Thanks for the report. Definitely my mistake.
Unit testing bypasses parsing command-line flags, and so default was not set properly.
Now properly setting the default DNS port in unit-testing too.

**Comment by vikin91** [comment]
This has been merged now in #10597.

The problems with CI checks for PRs from external contributors have been reported and I hope they will be fixed soon. For now, we need do make copies of such PRs (so that ACS member is the author) and merge them internally.

**Pull request closed without merging**
