### PR TITLE
chore: remove qemu

### PR DESCRIPTION
**Pull request by janisz**
## Description

Installing qemu failed for me in this job https://github.com/stackrox/stackrox/actions/runs/6027762599/job/16354089057?pr=7645
Let's remove it if it's not needed.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

CI

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by connorgorman** [comment]
I see that this works, but honestly I can't understand why. How does buildx get a power or z machine 🤔

**Review by connorgorman — APPROVED** [review]

**Comment by janisz** [comment]
So maybe it's not working but we do not have a check for Z?

**Comment by stehessel** [comment]
> Let's remove it if it's not needed.

How do you know that? Did you check that images are actually pushed for power and Z?

**Review by stehessel — CHANGES_REQUESTED** [review]
Please verify that this actually works beyond the action being green.

**Comment by janisz** [comment]
@stehessel Good point. We have no tests running on arm nor ppc. Let's close it for now until we have a way to verify that everything is working. Also we have qemu action in more places.

**Comment by janisz** [comment]
Closing in favour of 
- https://github.com/stackrox/stackrox/pull/12041

**Pull request closed without merging**
