### PR TITLE
Prefactor: generate postgres schemas in central instead of pkg

### PR DESCRIPTION
**Pull request by rhybrillou**
## Description

Move the schema generation from pkg to central.
This is a preliminary step to moving the scoped access control checks from the generated store code down to the postgres search query generator.

## Checklist
- [ ] Investigated and inspected CI test results
~~- [ ] Unit test and regression tests added~~
~~- [ ] Evaluated and added CHANGELOG entry if required~~
~~- [ ] Determined and documented upgrade steps~~
~~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~~

If any of these don't apply, please comment below.

## Testing Performed

CI should be sufficient.

Manual deployment will be done to ensure the migrator behaves as expected.

### CODE REVIEW

**Comment by rhybrillou** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5660** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/5660" target="_blank">Graphite</a>  👈
    * **PR #5661** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/5661" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/5660?utm_source=stack-comment).

**Comment by dashrews78** [comment]
Shouldn't we pull over non-generated stores like `network_flows` and `groups` too?

**Comment by rhybrillou** [comment]
> Shouldn't we pull over non-generated stores like `network_flows` and `groups` too?

This is done in https://github.com/stackrox/stackrox/pull/5661 . I wanted this PR to focus only on generated code in order to make the review easier (only the generator source should need review here).

**Comment by rhybrillou** [comment]
This approach does not work.
The migrator relies on the schema declarations in pkg to initialize or update the datamodel before central starts.
Moving the schemas to central cuts the registrations from pkg globals, which in the end results in central starting on an empty DB.
The approach initially considered in the following pull requests looks better.
https://github.com/stackrox/stackrox/pull/5325
https://github.com/stackrox/stackrox/pull/5326
https://github.com/stackrox/stackrox/pull/5327
The implementation of scope checks needs progressive deployment, though.

**Pull request closed without merging**
