### PR TITLE
fix(qa): WGET violations issue fixes for P/Z

### PR DESCRIPTION
**Pull request by pratham-m**
This PR intends to fix the issue where `Wget in Image` violations were not getting triggered on P/Z. The new image used is built as per changes in #6012

### CODE REVIEW

**Comment by pratham-m** [comment]
hi @gavin-stackrox  @robbycochran  kindly review this PR. currently this 1 has the debug tag enabled, I will revert that once you approve.

**Review by robbycochran — APPROVED** [review]

**Comment by pratham-m** [comment]
Thanks Robby for the approval. ALl CI checks have passed ✅, merging the PR.

**Pull request merged**
