### PR TITLE
Support multi-arch binaries

### PR DESCRIPTION
**Pull request by yselkowitz**
This reverts #2945 and reinstates #2820.

/cc @misberner

### CODE REVIEW

**Comment by misberner** [comment]
This seems to have succeeded:
```
$ docker run quay.io/stackrox-io/roxctl:3.71.x-473-g99ebf5aeb2 version
3.71.x-473-g99ebf5aeb2
```

**Review by misberner — APPROVED** [review]

**Comment by misberner** [comment]
Merging because this is basically the same as the earlier PR which passed all tests, and I have manually verified that the roxctl image works

**Comment by janisz** [comment]
This breaks `turbo-build`

**Pull request merged**
