### PR TITLE
ROX-19233: Fix verify connections from external sources

### PR DESCRIPTION
**Pull request by vikin91**
## Description

Not yet sure how to fix that flake, as I am still trying to reproduce it... This description will be updated once a solution is found.

### So far I tried/observed the following

1. Was unable to increase the timeout of 800s to 1600s - the solution using `Timeout globalTimeout = new Timeout(1600, TimeUnit.SECONDS)` does not help.

[CI log](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/7600/pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests/1696188892962623488)
```
18:28:17 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Checking for edge between deployments: sourceId 104a577f-c658-4212-bdfa-b8e2b75bbfbf, targetId 81bb672b-541f-4165-9836-a08be4289b8c
18:28:17 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Looking at edges for 1 source node(s)
18:28:18 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Checking for edge between deployments: sourceId 104a577f-c658-4212-bdfa-b8e2b75bbfbf, targetId 81bb672b-541f-4165-9836-a08be4289b8c
18:28:18 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Looking at edges for 1 source node(s)
18:28:20 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Checking for edge between deployments: sourceId 104a577f-c658-4212-bdfa-b8e2b75bbfbf, targetId 81bb672b-541f-4165-9836-a08be4289b8c
18:28:20 | DEBUG | NetworkFlowTest           | NetworkGraphUtil          | Looking at edges for 1 source node(s)
18:28:20 | WARN  | NetworkFlowTest           | NetworkGraphUtil          | SR did not detect the edge in Network Flow graph
18:28:20 | WARN  | NetworkFlowTest           | NetworkFlowTest           | Edge coming from OpenShift ingress router to 81bb672b-541f-4165-9836-a08be4289b8c not found
18:28:20 | ERROR | NetworkFlowTest           | Helpers                   | An exception occurred in test
(...)
18:31:38 | INFO  | NetworkFlowTest           | NetworkFlowTest           | Ending testcase
NetworkFlowTest > Verify connections from external sources FAILED
org.junit.runners.model.TestTimedOutException: test timed out after 1600 seconds
```

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

- This is a CI flake, so I will try to demonstrate that it does not happens again. This will happen through rerunning the affected test (`ocp-4-13-qa-e2e-tests` or `ocp-4-10-qa-e2e-tests`) several times and looking if the test got executed and passed.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by jschnath — APPROVED** [review]

**Comment by vikin91** [comment]
[4be408e](https://github.com/stackrox/stackrox/pull/7600/commits/4be408e6e0d2a1ff4d019b9b7e1d73e3edab53a0) was not flaking

**Comment by vikin91** [comment]
[d7c783b](https://github.com/stackrox/stackrox/pull/7600/commits/d7c783b83a09a953ec3730c2ccfdb1e4c1306611) also not flaking

**Comment by vikin91** [comment]
There is no cluster that can be used for testing this: 
```
WARN[[20](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/7600/pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests/1696802013318221824#1:build-log.txt%3A20)23-08-30T09:42:40Z] Found 1 conditions for ClusterClaim:
  *[2023-08-30T08:42:40Z]NoClusters: No clusters in pool are ready to be claimed
```

**Comment by vikin91** [comment]
@vjwilson I am adding you to this PR as FYI

**Comment by vikin91** [comment]
Last failure unrelated. Trying again to get 5 successful executions

/test ocp-4-10-qa-e2e-tests

**Comment by vikin91** [comment]
Last run passed. Let's run this again

/test ocp-4-10-qa-e2e-tests

**Pull request merged**
