### PR TITLE
ROX-9570: go test flake to use k8s api

### PR DESCRIPTION
**Pull request by keyallis**
## Description

We are going to be removing the flaky test since it has an equivalent test in groovy that is more comprehensive.

I looked into making the switch to the k8s api rather than using kubectl wrapped in an exec invocation and these were some of the difficulties I ran into along that path:
1.  The k8s api will parse objects as particular types. If we try to parse a pod yaml as a deployment it will fail. This means we would have to add wrapper functions on clients of every type of k8s object we try to deploy and then switch to usage of those functions in every relevant test.
2. Many tests create deployments from just image objects. For the sake of ease these would probably need to be defined as deployments in the yaml so we can more easily control the name of those created deployments rather than spinning up just an image.

I've opted to revert the changes rather than leave in functions which are never invoked, but I've kept them in the git history of this PR.

### CODE REVIEW

**Review by viswajithiii — COMMENTED** [review]
Why not just remove this test since it's a duplicate of an existing Groovy test?

**Comment by clickboo** [comment]
> Why not just remove this test since it's a duplicate of an existing Groovy test?

+1

**Comment by keyallis** [comment]
My understanding is that we want to migrate to go for e2e testing, and these were already changes that I had made. I think making these changes is the right course of action, and then if it ends up being a flake and getting reopened we can remove the test but leave some of the functions that were defined in the common file for potentially future use

**Comment by theencee** [comment]
+1 on what @keyallis said. The go test framework doesn't seem to be going away, so this is a better way to handle deployments instead of doing `exec.Command(kubectl...)`

**Review by theencee — APPROVED** [review]

**Comment by viswajithiii** [comment]
> +1 on what @keyallis said. The go test framework doesn't seem to be going away, so this is a better way to handle deployments instead of doing `exec.Command(kubectl...)`

We can keep those functions and the refactor, but I still think we should delete the duplicate test, because we will otherwise be doing the team a disservice -- this test may flake again in the future, someone else may spend time investigating, all for a test that we are not receiving any value from. Definitely support keeping the refactor to use the k8s client, and if you want to hook the other Go E2E tests up to that as well, that would be great.

**Comment by keyallis** [comment]
I've updated the PR description

**Review by viswajithiii — APPROVED** [review]

**Review by theencee — APPROVED** [review]

**Pull request merged**
