### PR TITLE
Don't silently fail on junit2jira

### PR DESCRIPTION
**Pull request by janisz**
## Description

Currently when junit2jira fails we skip it and continue normal flow. Since we now rely on this tool for our day to day job let's not ignore failures and get slca notifications for them as a part of CI trap. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Review by gavin-stackrox — COMMENTED** [review]
One problem I see with this is that if that curl, junit2jira or jira are having a bad day, every merge job pass and success will result in a slack notice to #test-failures. 

Also, if this allowed to fail it should move after the `cp` so at least the junit files get copied for prow to look at.

**Review by porridge — CHANGES_REQUESTED** [review]
Let's move the `cp` before the `junit2jira` invocation, then. We don't want to skip copying if the tool has problems, right?

**Comment by janisz** [comment]
How about making it like slack notifications but include nightly runs?

**Comment by gavin-stackrox** [comment]
Whatabout only ignoring failures from the curl (as well as moving below the cp)? That is probably where the most 'weakness' lies from github rate limiting. If the tool or jira access is a problem we have more control and can always spin a quick fix. Another option is put junit2jira in the repo or the ci image (with the usual image update pain).

**Pull request closed without merging**
