### PR TITLE
ROX-24913: Verify URLs read form dockerconfig secrets

### PR DESCRIPTION
**Pull request by vikin91**
## Description

Dockerconfig secrets contain URLs of container registries. Those secrets are defined by the users on their clusters. Sensor reads those secrets and tries to dial the registries and discover whether they are TLS terminated.

We want to make sure that the URLs are valid and a call to such URL has chances of succeeding before we call it.
This PR adds such validation early in the process. If an invalid URL is found, an error is printed to the logs and processing of such secret is skipped.

## Checklist
- [ ] Investigated and inspected CI test results
- [x] Unit test and regression tests added

### N/A
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

- [x] Unit tests
- [ ] On a cluster with creation of dockerconfig secret that contains a space in the URL 

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by rukletsov** [comment]
I'm quite sure this covers the issue we've seen recently. Here is my understanding

We see URL of the following format being attempted: `"tcp:// registry-dev.<acme-corp>.com:443"` in the logs. The `tcp://` comes from [our code here](https://github.com/stackrox/stackrox/blob/927822886ea54ee556a39c311d25ea778909d66d/pkg/httputil/proxy/proxy.go#L123-L126). So apparently a string with a leading space was provided. `" registry-dev.<acme-corp>.com:443"` is rejected by `url.Parse()`, so apparently we added the port [here](https://github.com/stackrox/stackrox/blob/5b163bd264197c379acb3b3be63c5e344ab48793/pkg/tlscheck/tlscheck.go#L36). 

So the problematic input that is allowed by `url.Parse()` but after a series of transformations becomes invalid is `" registry-dev.<acme-corp>.com"`. With that, I'd suggest to strip leading and trailing spaces. At the very least, add this example to the test case : ).

**Review by lvalerom — COMMENTED** [review]
I think this could make invalid secrets with registries like "qua.io:443/whatever/path". Are we ok with this?

**Comment by vikin91** [comment]
> I think this could make invalid secrets with registries like `"quay.io:443/whatever/path"`. Are we ok with this?

Yeah, that is a problem. I guess, this validation would need to look a bit differently. Let me propose a different version

**Comment by vikin91** [comment]
Apparently validating the host name is not so trivial (there are many more characters that are disallowed). I would close this PR in favor of #11668, which seems to be a better place to check that.

**Pull request closed without merging**
