### PR TITLE
ROX-19283: Validate only stackrox CRs

### PR DESCRIPTION
**Pull request by porridge**
## Description

* Replace a workaround mentioned in #5821 with proper filtering using `yq`.
* Also use the same `yq` version for another script for consistency and automatic version bumps.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Rebase on master once https://github.com/stackrox/stackrox/pull/5821 is merged
- [x] ~Unit test and regression tests added~
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

### Here I tell how I validated my change

CI should be sufficient.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by porridge** [comment]
FTR, I already deleted the ephemeral GKE cluster behind the credential leaked earlier.

**Review by GrimmiMeloni — APPROVED** [review]
LGTM

**Pull request merged**
