### PR TITLE
feat(CI): [do-not-merge] Build ppc64le main & central-db images 

### PR DESCRIPTION
**Pull request by anup-kodlekere**
## Description

This PR brings workflow changes that will allow to build multi-arch images with the help of buildx. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Validated locally. Inspecting CI results via the PR.

### CODE REVIEW

**Comment by mdafsanhossain** [comment]
@robbycochran This is the current status for central go build on ppc64le

`central-build-nodeps` fails to cross compile for ppc64le due to dependency on CGO

`make central-build-nodeps GOOS=linux GOARCH=ppc64le` throws the below error

`build constraints exclude all Go files in /home/ubuntu/stackrox/pkg/rocksdb`

Compiling with `CGO_ENABLED=1` starts the compilation but fails due to incompatible gcc compiler (amd64) throwing the following errors
https://github.com/stackrox/stackrox/actions/runs/4981092681/jobs/8914866721?pr=6021

To circumvent that I have setup Advance toolchain power cross compiler from IBM (https://www.ibm.com/support/pages/advtool-cross-compilers).

After compiling with the cross compiler, we do not get the above but we have problems while linking since the deps are for x86 arch. Following is the error log.

```
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/local/lib//librocksdb.so when searching for -lrocksdb
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/lib/x86_64-linux-gnu//liblz4.so when searching for -llz4
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/lib/x86_64-linux-gnu//libz.a when searching for -lz
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/lib/x86_64-linux-gnu//libzstd.so when searching for -lzstd
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/lib/x86_64-linux-gnu//libsnappy.a when searching for -lsnappy
/opt/at15.0/bin/powerpc64le-linux-gnu-ld: skipping incompatible /usr/lib/x86_64-linux-gnu//libbz2.a when searching for -lbz2
```


Note:  We followed the official instruction for rocksdb installation https://github.com/stackrox/dev-docs/blob/main/docs/getting-started/getting-started-linux.md#install-rocksdb

**Comment by mdafsanhossain** [comment]
@robbycochran @gavin-stackrox Can you review the changes in this PR and let us know if some things need to be changed? Also, can you clarify the naming convention for pushing the images?

**Comment by connorgorman** [comment]
@anup-kodlekere A PR based on this one has been merged into master. Can we close?

**Comment by anup-kodlekere** [comment]
Closing this PR as #6979 implements what's needed for multi-arch builds. Thanks @connorgorman!

**Pull request closed without merging**
