### PR TITLE
ROX-17192: Update np-guard/netpol-analyzer to v0.4.3

### PR DESCRIPTION
**Pull request by adisos**
## Description

Update  np-guard/netpol-analyzer to v0.4.3 
Includes a few compatibility updates:
- update to `roxctl/connectivity-map/cta.go`
- update to connectivity-map bats tests, since netpol-analyzer v0.4.3 does not necessarily traverses input YAML files by lexical order.

### CODE REVIEW

**Comment by janisz** [comment]
- https://github.com/stackrox/stackrox/pull/7385

**Comment by rhybrillou** [comment]
This looks to be a duplicate of #7385

**Comment by vikin91** [comment]
@janisz @rhybrillou dependabot shall not update NP-Guard dependencies - I instructed it to skip all updates to the `0.y` versions. Instead, we will be updating it manually in PRs like this. Thus, this is not a true duplicate 😉

**Pull request merged**
