### PR TITLE
chore(migration): generic store for migrations

### PR DESCRIPTION
**Pull request by dashrews78**
## Description

This is a take on a generic store for migrations.  The tooling from the `make bootstrap_migration` target was updated to take in a list of storage protos.  For each storage proto it will create a `gen.go` that will create a store `gogen -run pg-table-bindings` is executed.  The store being generic will allow for the previous data to be retrieved as those functions simply return the protos (or IDs) generically.  The generated store will contain the insert logic for the latest proto and as such will insert data in the form the current release understands.  See the testing section below to look at an example.

I made a copy for the migration to provide a level of isolation.  If we decide we can simply use the generic store in `pkg/search/postgres` I would recommend we do that under additional tech debt tickets.  Since currently we cannot use a copy of a store for a migration easily due to the move to the generic store.  Similarly if we decide we want to handle sac in migrations that would be another issue to handle as tech debt.  I simply removed all the SAC checks in the copy of the store for the migrator.

This also includes any necessary changes for ROX-17423, ROX-18778.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Created #7387 where I created `m_188_to_m_189_test_generic_example` to demonstrate the use of the generic store and executed the migration test.  (Ignore the `m_187_to_m_188_add_nftables_to_policy` as that was my first example attempt)

### CODE REVIEW

**Review by rhybrillou — COMMENTED** [review]
At first glance, the changes seem to introduce a copy of the generic store with the following changes:
- calls to metrics monitoring are removed
- Scoped access control checks are removed

Technically, the generated metrics functions could be replaced by an empty pass-through function.
On the Scoped access control side, I'd rather be in favour of using `sac.WithAllAccess(ctx)` in the migrations. That would leave room for some foreseeable changes to the way stores do work (the SAC checks could be moved from the generic stores further down to the SQL query generator).

**Comment by dashrews78** [comment]
> At first glance, the changes seem to introduce a copy of the generic store with the following changes:
> 
> * calls to metrics monitoring are removed
> * Scoped access control checks are removed
> 
> Technically, the generated metrics functions could be replaced by an empty pass-through function. On the Scoped access control side, I'd rather be in favour of using `sac.WithAllAccess(ctx)` in the migrations. That would leave room for some foreseeable changes to the way stores do work (the SAC checks could be moved from the generic stores further down to the SQL query generator).

The idea with the copy was to strip out stuff the migrations didn't need while also isolating the migrations from changes to the generic store so that we would be more intentional about what was included.  Regarding SAC, the migrations do run with `sac.WithAllAccess(ctx)` passed through the caller to the functions, so that should be fine.  I'm going to spend some time cleaning this up next couple days.  Any additional thoughts you may have would be appreciated.

**Review by rhybrillou — COMMENTED** [review]
Thank you for this great piece of work.

I really like the idea of auto-generating the store files for migrations. This will definitely improve the developer experience when writing data migrations.
I think the migration management experience improvement could be achieved with less code duplication (details as to why and how follow).

----------
The recent changes in `pkg/search/postgres/store.go` move the access control checks of the read and delete functions down to `pkg/search/postgres/common.go` and `pkg/search/postgres/common.go`.

After this, the remaining changes between the `migrator/migrations/postgreshelper/store.go` file and `pkg/search/postgres/store.go` are:
- removal of the metrics collection logic (in store struct, constructor and internal functions)
- removal of the operation type from the acquireConn function and function calls
- removal of the access-control related elements and logic (in store struct, constructor as well as helper and Upsert* functions)
- small differences to the query passed down to the functions from `pkg/search/postgres/common.go` (`search.ConjunctionQuery` not removed where only one argument remains or `nil` vs `search.EmptyQuery()`)

The `migration_store.go.tpl` file in `tools/generate-helpers/pg-table-bindings` also has few changes compared to the `store.go.tpl` file:
- removal of the metrics collection functions
- removal of the access-control related elements

The time metrics collection functions could be replaced with empty pass-through functions in the generated code in the case of migration.

The access control checks will be there anyway for `Walk`, `Count` and `Get*` functions, and will therefore require the migrations to use contexts with elevated permissions. The elevated-permission context could be crafted in a way that the access control checks in the `Upsert*` functions would pass anyway.

I think using the standard `store.go.tpl` template with minor adjustments covering the migration-related cases would significantly reduce the need for code duplication here.

**Comment by dashrews78** [comment]
> 

That's great info.  Thanks.  I'm HOPING I can get back to this and finish it in the near future.  Especially since the SAC changes were moved.  Should simplify things.

**Pull request closed without merging**
