### PR TITLE
docs: Update testing guideline in PR template

### PR DESCRIPTION
**Pull request by msugakov**
## Description

~~A suggestion here is to shift focus from "testing", that can be misunderstood, to have authors prove they checked how their thing actually works. That can be done through doing manual actions and observing results, creating and running automated tests, or something else. At this point, the suggestion is to promote the activity of validating the change and tackling _automated_ testing can be done later.~~

Let me try differently.

I have a feeling that "testing" is currently undervalued and in the context of PRs misunderstood as "just let CI run".
The problems of "just letting CI run" is that (a) it requires author to create automated tests, (b) it requires test tests actually cover significant parts of the change (ideally all).
The problem with (a) is that I see many PRs that go out without creating any tests at all. It's good if tests are added eventually but that may not even happen. The bigger thing is that sometimes authors forget to test the change manually as well. "No testing" is even worse than "no automated testing".
The problem with (b) is that tests seem to be focusing on the happy case scenario or not be actually _end_ to _end_. There's little value in dropping few unit tests and letting the entire change go out unvalidated. The validation then becomes burden of colleague engineers or users.

I don't think it's productive to argue about terminology, e.g. what e2e test means, or start complaining how it is inconvenient to write groovy tests.

Instead, the idea is simple. When you change something, you need to validate it actually works. Right? Right?

That's the angle I want to approach this problem from. Let each one of us think "how do I validate my change" instead of thinking "oh, that CI is slow and there are so many flakes".

Naturally, as soon as you answer how to validate your change and you do that, you'd benefit from _automating_ this validation, i.e. from creating automated tests. That's the goal, but let's not rush there so much that we forget the first step.

## Checklist
- [x] Investigated and inspected CI test results

These don't apply and won't be done:
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

### Here I tell how I validated my change

Only looked at the rendered version here: https://github.com/stackrox/stackrox/blob/misha/update-testing-in-pr-template/.github/pull_request_template.md

Interestingly, this PR was created _without_ the use of the new template. I applied it "manually". I hope it's going to work fine after merge but will try with a PR.
Perhaps GitHub takes the template from the target branch, not from the source one.

It's not practical to create automated tests for this change.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by GrimmiMeloni — COMMENTED** [review]
To me this change feels like we are advocating for less automated tests, which I would consider a very dangerous practice.
Why are we pivoting in this direction? Do we need to invest in simpler test automation?

**Comment by msugakov** [comment]
@GrimmiMeloni What specifically makes you feel

> we are advocating for less automated tests

?

That was not the intent at all and I'd like to fix it.

**Review by rukletsov — APPROVED** [review]

**Review by GrimmiMeloni — APPROVED** [review]
Looking good. Changed perspective on current daily business definetely helped me better understand the reasoning behind this.

**Comment by msugakov** [comment]
The PR template gets applied to new PRs. Example: https://github.com/stackrox/stackrox/pull/7515

**Pull request merged**
