### PR TITLE
Use official nginx image for docs

### PR DESCRIPTION
**Pull request by janisz**
## Description

Current docs image contains much more packages then we need. This creates big areas for vulnerabilities. 
By using smaller official image we reduce number of potentially vulnerable packages.

Config was obtained with `docker run -p 8081:8080 registry.access.redhat.com/ubi8/nginx-120:latest cat /etc/nginx/nginx.conf` but it will be better if we could use defaults and expose port `80` and changed to reflect new static files path.

## Testing Performed

N/A

### CODE REVIEW

**Review by msugakov — CHANGES_REQUESTED** [review]
Sorry. I don't think we should do this. I don't know what problem the image size causes and why it is worth solving.

**Comment by 0x656b694d** [comment]
The list of installed packages might be different, hence the vulnerable surface. I'd support the change if the difference is dramatic.

**Comment by msugakov** [comment]
First things first, here's a link to a Slack thread with the context https://srox.slack.com/archives/C0321S70YK1/p1651168113744619
Here's a Slack thread about why shipping docs as tarball should better be discussed with PMs https://srox.slack.com/archives/CELUQKESC/p1650976966100689

Secondly, if the problem that we're solving is vulnerabilities in the docs image, we can try address by adding `dnf upgrade -y`, just like how it was done for scanner images. See here
https://github.com/stackrox/scanner/blob/28fbde2c5304640da6dd1ff08371ff102b605513/image/scanner/rhel/Dockerfile#L27

The spell looks like this
```
RUN dnf upgrade -y && \
    dnf clean all && \
    rpm --verbose -e --nodeps $(rpm -qa curl '*rpm*' '*dnf*' '*libsolv*' '*hawkey*' 'yum*') && \
    rm -rf /var/cache/dnf /var/cache/yum
```

WDYT @janisz

**Comment by msugakov** [comment]
Finally, you may want to link this ticket to https://issues.redhat.com/browse/ROX-10097 @janisz

**Comment by msugakov** [comment]
Also, I don't know why is there such a concern about `ubi8/nginx-120` image. It looks like there's only one vulnerability, with `gzip`, that **is** updated if you run `dnf upgrade`.
https://catalog.redhat.com/software/containers/ubi8/nginx-120/6156abfac739c0a4123a86fd?container-tabs=security

**Comment by janisz** [comment]
We used to have `dnf upgrade` in main image and it does not solve vulns we had so we switched to ubi-mini in #1054. 
My point is to use minimal possible image to minimize vulnerability surface. 
What are the benefits of using `registry.access.redhat.com/ubi8/nginx-120:latest` over `nginx:alpine`?

**Comment by msugakov** [comment]
The main point for me to stick with the Red Hat images is consistency. We also use ubi/nginx from Red Hat registry downstream (although that one wasn't updated 1.18->1.20). Having smaller difference between upstream and downstream dockerfiles saves mental overhead when adapting changes and allows detecting issues during normal CI.

**Pull request closed without merging**
