### PR TITLE
ROX-13640: Build mock-grpc-server image on GHA

### PR DESCRIPTION
**Pull request by janisz**

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3926** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3926" target="_blank">Graphite</a> 
    * **PR #3942** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3942" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3942?utm_source=stack-comment).

**Review by gavin-stackrox — COMMENTED** [review]
I will defer to @JoukoVirtanen on this one. 
https://github.com/stackrox/stackrox/blob/master/.openshift-ci/build/Dockerfile.build-mock-grpc-server sets a specific version which may be what is required for this image.

**Comment by JoukoVirtanen** [comment]
I was able to pull the mock grpc server image and the tag looks good. Before I approve I would like to understand the CI failures. They don't appear to be related to the changes made here, but still I don't want to approve of a PR with failing tests without understanding the failures.

**Comment by janisz** [comment]
@JoukoVirtanen @gavin-stackrox PTAL

**Comment by janisz** [comment]
@gavin-stackrox @JoukoVirtanen PTAL

**Review by gavin-stackrox — APPROVED** [review]
LGTM, e2e is fine now and @JoukoVirtanen already said the image is good so :shipit:

**Pull request merged**
