### PR TITLE
ROX-12709: Build operator using apollo-ci

### PR DESCRIPTION
**Pull request by msugakov**
### Description

This follows up on this discussion https://github.com/stackrox/stackrox/pull/3126#discussion_r974928788

### Checklist

- [x] checked CI status

Not customer visible therefore other items don't apply.

### Testing

* Relying on CI

### CODE REVIEW

**Comment by misberner** [comment]
[Operator says](https://console.cloud.google.com/storage/browser/_details/roxci-artifacts/stackrox/1a6a49c90644f79e245b6806968d8cb08af363b0/1572130329634803712-pull-ci-stackrox-stackrox-master-openshift-newest-operator-e2e-tests/k8s-service-logs/stackrox-operator/pods/rhacs-operator-controller-manager-c57ccc96b-tzgpm-manager-previous.log;tab=live_object?authuser=1)
```
/usr/local/bin/stackrox-operator: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Looks like once again, we get tripped up by `CGO_CFLAGS` and `CGO_LDFLAGS` being set unconditionally in the build container. We should really remove this from the apollo-ci container. For now, I guess `ENV CGO_LDFLAGS=""` in the operator Dockerfile should suffice?

**Review by porridge — APPROVED** [review]

**Pull request merged**
