### PR TITLE
ROX-19953: use image SHA in SAC test

### PR DESCRIPTION
**Pull request by janisz**
## Description

As [proposed](https://github.com/stackrox/stackrox/pull/10106#issuecomment-1966648185) use Image SHA to have all benefits of image caching and reduce possibility of a flake.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI 

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Review by stehessel — CHANGES_REQUESTED** [review]
`nginx-unprivileged` was introduced because of this problem https://github.com/stackrox/stackrox/pull/7651. So if you want to unify, I think it's better to switch `TEST_IMAGE` to `nginx-unprivileged`.

**Comment by dhaus67** [comment]
As a general recommendation, let's use s digest reference for the image we test with and not a tag reference.
This way Central and Sensor can make use of caching of previous scan results and lowers the chance of flakes when no image scan is required to be tested.

**Review by dhaus67 — APPROVED** [review]

**Pull request merged**
