### PR TITLE
ROX-13915: Move docker.io images used in ImageManagementTest to quayio/rhacs-eng to prevent rate limiting

### PR DESCRIPTION
**Pull request by theencee**
## Description

See title

## Checklist
- [x] Investigated and inspected CI test results
~[ ] Unit test and regression tests added~
~[ ] Evaluated and added CHANGELOG entry if required~
~[ ] Determined and documented upgrade steps~
~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed

this is a test

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Comment by theencee** [comment]
Ignore the prow failures. They were from before it was migrated to GHA

**Review by gavin-stackrox — APPROVED** [review]
LGTM

**Pull request merged**
