### PR TITLE
Dashrews/gke postgres upgrade test collector

### PR DESCRIPTION
**Pull request by dashrews78**
## Description

The nature of this tests involves lots of upgrades and restarts.  So pods are coming up and down fairly regularly by design.  So when some of those restarts are slow we can get into situations where something like sensor takes too long to come back up so collector may have an unallowed restart because sensor took too long to come back up.  For this test, things like that are not really an issue.  So for this test only we will allow such restarts of collector.

This solves the issues where the tests gets flagged for collector having a previous.  Not the issue where the test cannot get metadata if it gets rotated to a 1.24 cluster.

## Checklist
- [ ] Investigated and inspected CI test results
~- [ ] Unit test and regression tests added~
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

All about this test.

### CODE REVIEW

**Comment by c-du** [comment]
Would you like to have some explanations for the changes?

**Comment by dashrews78** [comment]
> Would you like to have some explanations for the changes?

What happens is if central and/or sensor are down long enough during the upgrades, collector will bounce because it cannot communicate with sensor.  Then collector will be left with a previous and this is a way to clear it out.  That said, I created this PR real fast because I saw 2 failures quickly after pushing the updates to the test in master.  I was waiting to see if we really needed it which is why I don't have a description for it yet.

**Comment by dashrews78** [comment]
Closing this.  Incorporated these changes in #5229

**Pull request closed without merging**
