### PR TITLE
ROX-25407: Stabilize Splunk Violation Test

### PR DESCRIPTION
**Pull request by Maddosaurus**
### Description
After additional sanity checks for Splunk have been introduced in #12090, we should update this test as well.
While working on it, I also bumped the grace times for both search queries, as we have found in testing that initial data ingestion can take a long time, depending on the Node load Splunk runs on.

This is a follow-up to #12090 and requires the changes from that to be merged. Until then it is not ready for review.

### Testing

- [x] inspected CI results

#### Automated testing

- [x] modified existing tests

#### How I validated my change

Local testing against an OpenShift 4 infra cluster, CI

### CODE REVIEW

**Comment by Maddosaurus** [comment]
/\test gke-nongroovy-e2e-tests

**Review by lvalerom — APPROVED** [review]

**Comment by lvalerom** [comment]
@Maddosaurus question: Why are you running multiple times the `nongroovy` step? Shouldn't be `gke-qa-e2e-tests`?

**Review by vikin91 — APPROVED** [review]
The code changes look great! Let's make sure it runs correctly in CI (see Luis'es comment about the test target)

**Comment by Maddosaurus** [comment]
@lvalerom oh yes, absolutely right. Copy-paste mistake!

**Pull request merged**
