### PR TITLE
ROX-16554: Rename Helm setting nodeInventoryResources to nodeScanningResources

### PR DESCRIPTION
**Pull request by vikin91**
## Description

Renaming a Helm setting as discussed in https://redhat-internal.slack.com/archives/C04213W844U/p1681745465572349

## Checklist
- [x] Investigated and inspected CI test results

### N/A
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

- [x] CI
- [x] Manual deploy with Helm

### CODE REVIEW

**Comment by vikin91** [comment]
The failure in `ocp-4-12-qa-e2e-tests` will be fixed in #5782

**Review by jschnath — APPROVED** [review]

**Comment by msugakov** [comment]
Late to the party, but this is user-facing change and so it should be noted in the `CHANGELOG.md`.

**Comment by vikin91** [comment]
> Late to the party, but this is user-facing change and so it should be noted in the `CHANGELOG.md`.

Thanks! Here it is: https://github.com/stackrox/stackrox/pull/5836

**Pull request merged**
