### PR TITLE
chore: migrate sensor awscredentials to aws-go-sdk-v2

### PR DESCRIPTION
**Pull request by stehessel**
### Description

`aws-sdk-go` has been deprecated and will be removed eventually (see https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/). This is the last package to migrate from `aws-sdk-go` to `aws-sdk-go-v2` (S3 backup is staying on v1 intentionally).

I also added a client timeout and proxy setup to the AWS config.

### User-facing documentation

- [x] CHANGELOG is updated **OR** update is not needed
- [x] [documentation PR](https://spaces.redhat.com/display/StackRox/Submitting+a+User+Documentation+Pull+Request) is created and is linked above **OR** is not needed

### Testing and quality

- [x] the change is production ready: the change is GA or otherwise the functionality is gated by a feature flag
- [x] CI results are inspected

#### Automated testing

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests

#### How I validated my change

I verified that ECR image integrations are auto-generated for EKS clusters.

SCR-20241111-tbvx

### CODE REVIEW

**Review by Maddosaurus — APPROVED** [review]
Looks good, the nit is non-blocking for me.
Could you fill in the "How I validated my change" part, so interested reviewers can reproduce and verify your test results?

**Review by jschnath — APPROVED** [review]
Looks good to me, please address what Matthias mentioned above

**Pull request merged**
