### PR TITLE
Use gogo Un/Marshal for version and cve store

### PR DESCRIPTION
**Pull request by janisz**
## Description

Adjust to generated code.

## Testing Performed

CI

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3446** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3446" target="_blank">Graphite</a> 
    * **PR #3448** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3448" target="_blank">Graphite</a> 
      * **PR #3449** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3449" target="_blank">Graphite</a> 
        * **PR #3450** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3450" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3450?utm_source=stack-comment).

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* master
  * **PR #3446** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3446" target="_blank">Graphite</a> 
    * **PR #3448** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3448" target="_blank">Graphite</a> 
      * **PR #3449** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3449" target="_blank">Graphite</a> 
        * **PR #3450** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/3450" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/3450?utm_source=stack-comment).

**Review by misberner — APPROVED** [review]

**Review by md2119 — APPROVED** [review]

**Pull request merged**
