### PR TITLE
ROX-18660: Add docs on registryOverride parameter

### PR DESCRIPTION
**Pull request by ebensh**
Add documentation on the registryOverride parameter.

## Description

Just adds documentation missed in https://github.com/stackrox/stackrox/pull/7429

### CODE REVIEW

**Review by porridge — COMMENTED** [review]
I don't this is something that should be mentioned in the changelog. It explicitly says:

> Entries in this file should be limited to:
> -  Any changes that introduce a deprecation in functionality, OR
> -  Obscure side-effects that are not obviously apparent based on the JIRA associated with the changes.
> 
> Please avoid adding duplicate information across this changelog and JIRA/doc input pages.

**Comment by ebensh** [comment]
> I don't this is something that should be mentioned in the changelog. It explicitly says:
> 
> > Entries in this file should be limited to:
> > 
> > * Any changes that introduce a deprecation in functionality, OR
> > * Obscure side-effects that are not obviously apparent based on the JIRA associated with the changes.
> > 
> > Please avoid adding duplicate information across this changelog and JIRA/doc input pages.

I don't know if I buy this - looking at the CHANGELOG we see a lot of similar examples:

> - ROX-16532: Resource limits and requests for the node-inventory container can now be configured via the operator.

and

>  - ROX-16962: A new parameter `spec.admissionControl.replicas` has been added to the `SecuredCluster` CRD.

Maybe the amount of detail could be dropped, instead leaving it at the name of the field being added, but it seems like exactly the sort of thing that we actually do put in the changelog?

**Comment by porridge** [comment]
> looking at the CHANGELOG we see a lot of similar examples

Either the instructions are wrong, or these were added without paying attention to instructions.
I think the latter is more likely.

**Comment by ebensh** [comment]
I've been advised that the release docs are not required for adding a field to the CR(D) because it is self documenting. Closing out.

**Pull request closed without merging**
