### PR TITLE
:rotating_light: G112 gosec rule enabled

### PR DESCRIPTION
**Pull request by bgalek**
## Description

G112 check enabled in gosec config

### CODE REVIEW

**Comment by janisz** [comment]
```
pkg/metrics/http_server.go:54:17: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
	httpServer := &http.Server{
		Addr:    s.Address,
		Handler: mux,
	}
pkg/grpc/endpoints.go:175:15: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
		httpSrv := &http.Server{
			Handler:   actualHTTPHandler,
			TLSConfig: tlsConf,
			ErrorLog:  golog.New(httpErrorLogger{}, "", golog.LstdFlags),
		}
migrator/main.go:46:10: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
	srv := &http.Server{Addr: ":6060", Handler: handler}
	        ^
```

**Review by janisz — CHANGES_REQUESTED** [review]
CI is failing

**Comment by porridge** [comment]
Any updates @bgalek ?

**Comment by janisz** [comment]
Closing due to lack of activity.
@bgalek feel free to reopen this PR

**Pull request closed without merging**
