### PR TITLE
:rotating_light: G306 gosec rule enabled

### PR DESCRIPTION
**Pull request by bgalek**
## Description

G306 check enabled in gosec config

### CODE REVIEW

**Comment by janisz** [comment]
@bgalek Please use `//nolint:gosec:G306` in false positive lines https://golangci-lint.run/usage/false-positives/#nolint-directive

**Comment by bgalek** [comment]
Ok! Sure thing!

**Comment by janisz** [comment]
@bgalek There are still some issues

**Comment by bgalek** [comment]
I'll check it today!

**Review by janisz — CHANGES_REQUESTED** [review]
CI is failing

**Comment by bgalek** [comment]
Yeah, I'll check it out

**Comment by porridge** [comment]
@bgalek any updates?

**Comment by janisz** [comment]
Closing due to lack of activity.
@bgalek feel free to reopen this PR

**Pull request closed without merging**
