### PR TITLE
ROX-11693: Port scale tests to OSCI

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

Per title. This PR resurrects the CI scale tests that run on nightly and release builds (anything tagged).

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

- pprof data saved.
- Baseline and GCP monitoring metrics saved once in test commit, only on nightly runs going forward.

### CODE REVIEW

**Comment by connorgorman** [comment]
@md2119 Can you give me an example of when this would occur?

**Review by sbostick — APPROVED** [review]
LGTM

**Review by connorgorman — APPROVED** [review]

**Pull request merged**
