### PR TITLE
Upgrade scanner to 2.27.6

### PR DESCRIPTION
**Pull request by daynewlee**
## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

Let CI pass

### CODE REVIEW

**Review by tommartensen — APPROVED** [review]
LGTM

**Comment by janisz** [comment]
Refs: 
- https://github.com/stackrox/stackrox/pull/4911

**Pull request merged**
