### PR TITLE
Add git config for dubious repository ownership

### PR DESCRIPTION
**Pull request by c-du**
## Description

Add git config for dubrious repository ownership error during local build. 
```
fatal: detected dubious ownership in repository at '/src'
To add an exception for this directory, call:

	git config --global --add safe.directory /src
```
It looks like the same error has been addressed in ci build. This one is to fix local build who is using latest git version.

## Checklist
- [ ] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

If any of these don't apply, please comment below.

## Testing Performed
local build with git 2.36.1
make main-image

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Comment by msugakov** [comment]
I fixed this with simply running this command once in my repo
```sh
sudo chown -R "${USER}:${USER}" .
```

**Comment by c-du** [comment]
This is the build in docker who brutally treat my users as "501 root"

**Comment by porridge** [comment]
I think it might be better to try and fix the permissions, local dockerized builds should really be working once permissions are set correctly, after:
- https://github.com/stackrox/stackrox/pull/4622 and
- https://github.com/stackrox/stackrox/pull/4567
:thinking:

**Comment by c-du** [comment]
@porridge Thanks for pointing out the alternative way for this.

But I am running with that in master and setting up user or uid:gid cannot address my issue here. It could be related to my MacOs with M1 environment.

**Comment by c-du** [comment]
drwxr-xr-x   82 cong  staff      2624 Mar  1 10:34 rox
cong@cdu-mac stackrox:$ id
uid=501(cong) gid=20(staff) ....
It fails with all these:
 docker run --user "501:20"
  docker run --user "501:0"
 docker run --user "501"

**Comment by porridge** [comment]
@c-du can you please run the following for me?
```
cdrox;id;ls -ld .;git status;echo;docker run -v"$(pwd)":/src:delegated --user "$(id -u)" -w /src quay.io/stackrox-io/apollo-ci:stackrox-build-0.3.56 bash -c "id;ls -ld .;git status"
```

WFIW in my case it prints:
```
uid=4200660 gid=4200660 groups=4200660,3(sys),100(users),972(docker)
drwxr-xr-x 36 4200660 docker 4096 Mar  2 07:16 .
On branch porridge/ROX-7026-re-enable
nothing to commit, working tree clean

uid=4200660 gid=0(root) groups=0(root)
drwxr-xr-x. 36 4200660 972 4096 Mar  2 06:16 .
On branch porridge/ROX-7026-re-enable
nothing to commit, working tree clean
```

**Comment by porridge** [comment]
@c-du this is the weird part:
```
drwxr-xr-x 62 root root 1984 Mar 3 19:54 .
```
Looks like inside the container, the directory gets owned by `root:root`, rather than your user. This is weird. I wonder if it's a general docker-on-mac thing, or something specific to M1, or to your particular machine. :thinking:
Are you even able to modify the directory from within the container? Try adding `touch .;` right before the `git status`?

**Comment by c-du** [comment]
Yes, I can.

**Comment by porridge** [comment]
For completeness, here are results from @vikin91 

```
➜ cdrox2;id;ls -ld .;git status;echo;docker run -v"$(pwd)":/src:delegated --user "$(id -u)" -w /src quay.io/stackrox-io/apollo-ci:stackrox-build-0.3.56 bash -c "id;ls -ld .;touch .;git status"

uid=501(prygiels) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
drwxr-xr-x  60 prygiels  staff  1920 Mar  6 09:11 .
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

uid=501 gid=0(root) groups=0(root)
drwxr-xr-x 60 root root 1920 Mar  6 08:11 .
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

and @kovayur 

```
stackrox git:(master) cdrox;id;ls -ld .;git status;echo;docker run -v"$(pwd)":/src:delegated --user "$(id -u)" -w /src quay.io/stackrox-io/apollo-ci:stackrox-build-0.3.56 bash -c "id;ls -ld .;touch .;git status"
uid=501(ykovalev) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
drwxr-xr-x  64 ykovalev  staff  2048 Mar  6 12:17 .
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

uid=501 gid=0(root) groups=0(root)
drwxr-xr-x 1 501 games 2048 Mar  6 11:17 .
On branch master
Your branch is up to date with 'origin/master'.


It took 43.62 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing to commit, working tree clean

stackrox git:(master) git version
git version 2.39.1

stackrox git:(master) docker run -v"$(pwd)":/src:delegated --user "$(id -u)" -w /src quay.io/stackrox-io/apollo-ci:stackrox-build-0.3.56 bash -c "git version"
git version 2.39.0

stackrox git:(master) colima version
colima version 0.5.2
git commit: 6b5b6fe0540e708f0c9d6e8919fab292c671fc72

runtime: docker
arch: x86_64
client: v20.10.20
server: v20.10.20

kubernetes
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.23.6+k3s1
```

Every case is slightly different.

**Review by porridge — APPROVED** [review]
I give up trying to understand this mac weirdness :table_flip:

**Comment by c-du** [comment]
@porridge Thanks for investigating this.

**Pull request merged**
