### PR TITLE
ROX-11245 New graphql endpoint to get a list of sorted images, sorted by CVE severity distribution.

### PR DESCRIPTION
**Pull request by clickboo**
## Description
New endpoint for the new actionable widget in the main dashboard redesign.

## Checklist
- [x] Investigated and inspected CI test results
- [x] ~Unit test and regression tests added~
- [x] ~Evaluated and added CHANGELOG entry if required~
- [x] ~Determined and documented upgrade steps~
- [x] ~Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed
Manual on gke cluster using postman

### CODE REVIEW

**Review by md2119 — COMMENTED** [review]
Boo, this seems like a good opportunity to change our search fields to address use cases like this. Currently, we have search field tags on proto fields that mark them searchable as well as sortable. Fields not coming directly are derived fields. What if we add a derived field option to `search/options.go` and tackle this field at the internal level instead of graphQL layer. That opens doors to use this field to be used elsewhere—image endpoints, images csv export, etc. Further, we can control if the field is searchable or sortable by augmenting `FieldLabel` with new properties.

**Comment by clickboo** [comment]
> Boo, this seems like a good opportunity to change our search fields to address use cases like this. Currently, we have search field tags on proto fields that mark them searchable as well as sortable. Fields not coming directly are derived fields. What if we add a derived field option to `search/options.go` and tackle this field at the internal level instead of graphQL layer. That opens doors to use this field to be used elsewhere—image endpoints, images csv export, etc. Furthermore, we can control if the field is searchable or sortable by augmenting `FieldLabel` with new properties.

Good idea though I believe all that is changing with postgres and Viswa is currently working on it (derived fields especially).

**Review by connorgorman — APPROVED** [review]
If my read is correct, this will read *all* images from the database then run the image vulnerability counter over them. This is really expensive from both a CPU and Memory perspective, and I can't imagine the latency being good at scale. I think we need to rethink the approach

**Review by connorgorman — CHANGES_REQUESTED** [review]
See previous comment, meant to request changes

**Comment by clickboo** [comment]
> If my read is correct, this will read _all_ images from the database then run the image vulnerability counter over them. This is really expensive from both a CPU and Memory perspective, and I can't imagine the latency being good at scale. I think we need to rethink the approach

This has already been brought up to PM but the widget needs it :). The images are going to be filtered down by cluster and/or images from a widget perspective.  In the postgres world, if the derived fields work by Viswa can help this great but the need for the sorting by vuln severity distribution is not going away from the dashboard.

**Comment by viswajithiii** [comment]
> Boo, this seems like a good opportunity to change our search fields to address use cases like this. Currently, we have search field tags on proto fields that mark them searchable as well as sortable. Fields not coming directly are derived fields. What if we add a derived field option to `search/options.go` and tackle this field at the internal level instead of graphQL layer. That opens doors to use this field to be used elsewhere—image endpoints, images csv export, etc. Furthermore, we can control if the field is searchable or sortable by augmenting `FieldLabel` with new properties.

I'm doing this, but it will only work for postgres. @clickboo, do we need this functionality before postgres?

**Comment by clickboo** [comment]
> > Boo, this seems like a good opportunity to change our search fields to address use cases like this. Currently, we have search field tags on proto fields that mark them searchable as well as sortable. Fields not coming directly are derived fields. What if we add a derived field option to `search/options.go` and tackle this field at the internal level instead of graphQL layer. That opens doors to use this field to be used elsewhere—image endpoints, images csv export, etc. Furthermore, we can control if the field is searchable or sortable by augmenting `FieldLabel` with new properties.
> 
> I'm doing this, but it will only work for postgres. @clickboo, do we need this functionality before postgres?

Yes, needed before postgres given release timelines of this feature.

**Comment by md2119** [comment]
@clickboo, maybe we can incorporate the count fields required for the widget in question as top-level fields on image proto. Currently, we store total cve count and total fixable cve count. The total count fields are populated at upserts anyway. We can expand on the current proto to store counts by severity. 

This will also give the data readily for several other use cases.

**Pull request closed without merging**
