### PR TITLE
ROX-18216: Fix NodeInventory flake

### PR DESCRIPTION
**Pull request by vikin91**
## Description

The problem was that the Collector DS restarted with new env var updated all but one pod. 
⚠️ I was unable to reproduce this locally.

This PR:
- Adds one more repetition of the entire process (setting env var to the DS, waiting for pods to be updated)
- Changes the wait time between checking the node-inventory containers from 6s to 10s. This should give more time for the change to propagate (if that is the reason of this failure).

## Checklist
- [x] Investigated and inspected CI test results

### N/A
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]

## Testing Performed

- CI
- Locally running tests

### CODE REVIEW

**Review by lvalerom — APPROVED** [review]

**Review by Maddosaurus — APPROVED** [review]
LGTM!

Idea if that doesn't succeed: Could we delete all pods in the DaemonSets and therefore force them to be recreated? That could eliminate the possibility of one pod missing the env var update in the timeframe.

**Comment by vikin91** [comment]
> LGTM!
> 
> Idea if that doesn't succeed: Could we delete all pods in the DaemonSets and therefore force them to be recreated? That could eliminate the possibility of one pod missing the env var update in the timeframe.

Yes, let's keep that idea as next thing to try if the given solution is insufficient.

**Pull request merged**
