### PR TITLE
Improve icons for Enabled Fixable Pass in UI

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

Follow up after first draft in #5696

Thanks to Mansur for guiding the discussion by Design and Product.

| entity        | text        | icon                  | color         |
| :---          | :---        | :---                  | :---          |
| policy        | Enabled     | CheckIcon             | normal black  |
| policy        | Disabled    | MinusIcon             | normal black  |
| vulnerability | Fixable     | WrenchIcon            | normal black  |
| vulnerability | Not fixable | MinusIcon             | normal black  |
| policy        | Pass        | CircleCheckIcon       | success green |
| policy        | Fail        | ExclamationCircleIcon | danger red    |

Bonus improvements for consistency:
* ImageActiveIconText renders CheckIcon and MinusIcon like policy Enabled/Disabled
* NotApplicableIconText renders MinusIcon like policy Disabled and vulnerability Not fixable

## Checklist
- [ ] Investigated and inspected CI test results
- [x] ~Unit test and regression tests added~

### Integration testing

In ui/apps/platform folder:

1. `export CYPRESS_ROX_POSTGRES_DATASTORE=true`

2. `yarn cypress-open`

    * configmanagement/ciscontrols.test.js
    * configmanagement/clusters.test.js
    * configmanagement/deployments.test.js
    * configmanagement/namespaces.test.js
    * configmanagement/policies.test.js
    * vulnmanagement/clusterCves.test.js
    * vulnmanagement/clusters.test.js
    * vulnmanagement/deployments.test.js
    * vulnmanagement/entitypages.test.js
    * vulnmanagement/imageComponents.test.js
    * vulnmanagement/imageCves.test.js
    * vulnmanagement/images.test.js
    * vulnmanagement/namespaces.test.js
    * vulnmanagement/nodeComponents.test.js
    * vulnmanagement/nodeCves.test.js
    * vulnmanagement/nodes.test.js

#### Configuration Management

1. Visit /main/configmanagement/policies

    * See Disabled/Enabled and Disabled/Fail/Pass in dark theme
        configmanagement_policies_dark

    * See Disabled/Enabled and Disabled/Fail/Pass in light theme
        configmanagement_policies_light

2. Visit /main/configmanagement/controls

    * See Fail and Pass in light theme
        configmanagement_controls_Fail_Pass

    * See Pass and N/A in light theme
        configmanagement_Pass_NA

#### Vulnerability Management

1. Visit /main/vulnerability-management/policies

    * See Pass/Disabled/Fail in dark theme
        vulnerability-management_policies_dark

    * See Pass/Disabled/Fail in light theme
vulnerability-management_policies_light

2. Visit /main/vulnerability-management/node-cves

    * See Not fixable and Fixable in dark theme
        vulnerability-management_node-cves_dark

    * See Not fixable and Fixable in light theme
        vulnerability-management_node-cves_light

3. Visit /main/vulnerability-management/images

    * See Active in dark theme
        vulnerability-management_images_dark

    * See Active in light theme
        vulnerability-management_images_light

### CODE REVIEW

**Review by vjwilson — COMMENTED** [review]
Code is fine.

Two things that I wonder about, 

1. What does a "Watched" image look like, as opposed to Active or Inactive ?
2. Was the Wrench the final decision for Fixable ?

**Comment by pedrottimark** [comment]
@vjwilson Good eyes.
* Remind me which column of which page to look at descriptors for **Watched**? I do not remember seeing it where I replaced `LabelChip` element for **Active**. Which is now only if environment variable, correct?
* **Wrench** is the current final decision.

**Comment by vjwilson** [comment]
> 
> * Remind me which column of which page to look at descriptors for **Watched**? I do not remember seeing it where I replaced `LabelChip` element for **Active**. Which is now only if environment variable, correct?

Ah, there are some examples on stagingdb right now,
https://stagingdb.demo.stackrox.com/main/vulnerability-management/images 

Screen Shot 2023-05-15 at 7 52 04 AM

**Comment by pedrottimark** [comment]
Thanks, then watched links should remain the same, but icons change:
* Active: from green to black color for check mark
* Inactive: from X to minus

**Review by vjwilson — APPROVED** [review]

**Pull request merged**
