### PR TITLE
tests: rewrite in go and simplify TLSChallengeTest

### PR DESCRIPTION
**Pull request by porridge**
### Description

`TLSChallengeTest` is currently by far the most flaky test owned by draco team. Rather than invest more time into debugging the groovy test and the k8s interface library (where the problem seems to lie) I decided to kill two birds with one stone and rewrite this test in Go. This starts to pave the road towards creating an improved e2e testing framework for nongroovy.

While rewriting I also reused the additional CA already in use for `TestCASetup` which speeds up and simplifies the test considerably.

This PR resolves:
- https://issues.redhat.com/browse/ROX-24631(Move TLSChallengeTest to the nongroovy job)
- https://issues.redhat.com/browse/ROX-22594 (TLSChallengeTest / Verify sensor can communicate with central behind an untrusted load balancer FAILED)
And partially addresses:
- https://issues.redhat.com/browse/ROX-9232 (Create end2end testing framework for Go)

### User-facing documentation

(*must be* 2 items and both *must be* checked)

- [x] CHANGELOG update is not needed
- [x] Documentation is not needed

### Testing

- [x] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [x] added e2e tests
- [x] modified existing tests
  

#### How I validated my change

I ran the GKE job [multiple times](https://prow.ci.openshift.org/pr-history/?org=stackrox&repo=stackrox&pr=11986), with flying colors.

### CODE REVIEW

**Comment by porridge** [comment]
FTR I'm working on a fix for the `style-check` failure, will push once the first round of e2es passes.

**Review by janisz — COMMENTED** [review]
I'm not fan of `suite` tests but I think in this case it may help to clean test. We have 2 common args that we pass to multiple functions so it's a good candidate for a struct field `t *testing.T, k8s kubernetes.Interface,`

**Comment by porridge** [comment]
Closing for now to stop the runaway retesting.
Wasn't there supposed to be an upset bound @janisz ?

**Pull request closed without merging**
