### PR TITLE
Convert test containers from x86 arch to multi-arch

### PR DESCRIPTION
**Pull request by kcrane**
## Description

Containers used during testing are x86 and will fail when testing ppc64le or s390x.  Instead use a container repo with multi-arch versions of these containers.

### CODE REVIEW

**Comment by porridge** [comment]
cc @stackrox/collector-team

**Comment by porridge** [comment]
This seems to be against `master` tip as of August, I think you'll need to rebase for the builds/tests to succeed.

**Comment by JoukoVirtanen** [comment]
> This seems to be against `master` tip as of August, I think you'll need to rebase for the builds/tests to succeed.

Yes. @kcrane please rebase.

**Pull request closed without merging**
