### PR TITLE
Sanitize username and password on SMTP AUTH LOGIN (#5126)

### PR DESCRIPTION
**Pull request by amedeos**
Sanitize username and password on SMTP AUTH LOGIN using strings.ToLower before comparing in switch case

## Description
Before compare what from SMTP server we got, it is useful to "sanitize" with ToLower strings function, otherwise we can never intercept "username" and "password" commands.

### CODE REVIEW

**Review by keyallis — CHANGES_REQUESTED** [review]
If you could please give this a rebase onto the current master branch, that should resolve the CI failures.

**Review by rukletsov — APPROVED** [review]

**Pull request merged**
