### PR TITLE
ROX-18276: adapt telemetry metrics to Telemeter feedback

### PR DESCRIPTION
**Pull request by stehessel**
## Description

Based on feedback in https://github.com/openshift/cluster-monitoring-operator/pull/2062, change the telemetry metrics in the following ways:

* `rhacs:telemetry:rox_sensor_secured_nodes` and `rhacs:telemetry:rox_sensor_secured_vcpu` -> `rhacs:telemetry:rox_sensor_info`. The reason for this change is that Telemeter already includes the node count and cpu count in their metrics. We keep the info metric for the remaining information.
* remove `branding` label from all recording rules and filter directly for `RHACS` branding.

~~I also realized that `ROX_PRODUCT_BRANDING` is not set consistently in the container environment. Therefore, switch to the image flavor name `ROX_IMAGE_FLAVOR`, which serves essentially the same purpose. We may switch back to `ROX_PRODUCT_BRANDING` at a later time once we figured out the env problem.~~

~~From https://github.com/stackrox/stackrox/blob/b522f6257b837102c6a32cc5e4fd1138751127ce/pkg/images/defaults/env.go, we assume that `ROX_IMAGE_FLAVOR` having `"rhacs"` string in its value is a solid indication of a production RHACS build.~~

The above bug will be fixed independently, no need for the workaround.

## Testing Performed

Tested the metrics in an OpenShift cluster.

### CODE REVIEW

**Review by janisz — APPROVED** [review]

**Review by rukletsov — APPROVED** [review]

**Comment by stehessel** [comment]
`ocp-4-13-*` tests with due to infra problems with `failed to wait for the created cluster claim to become ready: timed out waiting for the condition`. `ocp-4-10` tests are passing.

`gke-upgrade-tests` fails in pre-flight check
```
upgrader/preflight: 2023/09/01 22:22:46.997020 perform.go:50: Info: Preflight check "Kubernetes authorization" finished with 1 error(s), 1 warning(s)
panic: preflight check "Kubernetes authorization" reported errors:
K8s authorizer did not explicitly allow or deny access to perform action update on resource deployments. This usually means access is denied.. Additionally, it reported the following warnings:
Evaluation error performing access review check for action update on resource deployments: the server is currently unable to handle the request
```
In any case, the recording rule change is orthogonal to this test and only affects OpenShift clusters anyway.

Overall I'm reasonably convinced the failures are unrelated, therefore merging this.

**Pull request merged**
