### PR TITLE
Untie documentation link from the product version

### PR DESCRIPTION
**Pull request by msugakov**
## Description

This follows up on https://github.com/stackrox/stackrox/pull/3541/files#r1014009939

## Checklist
- [x] Investigated and inspected CI test results

None of these will be done:
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

* Opened <https://docs.openshift.com/acs/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs> the browser and saw it being redirected automatically to <https://docs.openshift.com/acs/3.72/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs>.

### CODE REVIEW

**Review by vjwilson — COMMENTED** [review]
@lmaynard88 @kcarmichael08 

I'm going to leave this PR to the docs team to approve, or suggest changes, because I do not fully understand how our documentation works now in the Red Hat world.

**Comment by vjwilson** [comment]
I did notice that when I follow the new link that Misha is proposing,
https://docs.openshift.com/acs/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs

the URL immediately redirects me to,
https://docs.openshift.com/acs/3.72/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs

**Comment by kcarmichael08** [comment]
> I did notice that when I follow the new link that Misha is proposing, [docs.openshift.com/acs/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs](https://docs.openshift.com/acs/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs)
> 
> the URL immediately redirects me to, [docs.openshift.com/acs/3.72/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs](https://docs.openshift.com/acs/3.72/installing/install-ocp-operator.html#adding-a-new-cluster-to-rhacs)

Looks like it is redirecting to the latest version, which is OK for right now. With the help of @gaurav-nelson we will have to edit the redirects slightly on our end before the release (because the URLs changed in the new installation docs structure). It is on our list of things to take care of before the release, though.

**Review by kcarmichael08 — APPROVED** [review]
OK for right now - docs has action item on our end to fix redirects before release.

**Pull request merged**
