### PR TITLE
ROX-20078: Multi-arch handling in DeploymentTest for ppc64le

### PR DESCRIPTION
**Pull request by pratham-m**
This PR intends to add multi-arch support for the `DeploymentTest` QA test.
Test code changes & images used in the test are update to enable test execution on 3 platforms viz. `x86_64`, `ppc64le` and `s390x`.

Changes are verified manually using `./gradlew test --tests=DeploymentTest`

This PR is created skip few tests on P/Z based on discussions in [ROX-20078](https://issues.redhat.com/browse/ROX-20078) and [ROX-16332](https://issues.redhat.com/browse/ROX-16332)

### CODE REVIEW

**Comment by pratham-m** [comment]
This PR is related to analysis done in #8112 and #8113

**Comment by pratham-m** [comment]
hi @robbycochran @gavin-stackrox kindly review the changes.
FYI - currently the tests are executed in debug mode. will revert the debug mode changes once all CI checks are green.

**Comment by pratham-m** [comment]
Logs for quick reference (with `debug` mode enabled)
[x86](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/8209/pull-ci-stackrox-stackrox-master-ocp-4-13-qa-e2e-tests/1714250774692761600)
[ppc64le](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/8209/pull-ci-stackrox-stackrox-master-powervs-qa-e2e-tests/1714250774772453376)
[s390x](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_stackrox/8209/pull-ci-stackrox-stackrox-master-ibmcloudz-qa-e2e-tests/1714345666974584832)

**Review by robbycochran — APPROVED** [review]

**Comment by pratham-m** [comment]
ALl CI checks have passed ✅ on X.

`DeploymentTest` + all other intended tests passed on P/Z.
Note: Few failures observed are flaky on P/Z and would be tracked separately.

**Comment by robbycochran** [comment]
LGTM

**Review by robbycochran — APPROVED** [review]

**Comment by pratham-m** [comment]
Thanks for the approval Robby. 
Merging the PR.

**Pull request merged**
