### PR TITLE
ROX-11748: Enabled Postgres functionality for Node datastore and globaldatastore

### PR DESCRIPTION
**Pull request by mtodor**
## Description

This PR enables Postgres functionality for Node datastore and globaldatastore.

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~ - added with follow-up PR: #2600 
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

To test this functionality, it's best to use unit tests introduced in #2600. Also testing procedure is explained in that PR.

### CODE REVIEW

**Comment by mtodor** [comment]
Current dependencies on/for this PR:
* master
  * **PR #2553** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2553" target="_blank">Graphite</a>  👈
    * **PR #2600** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/2600" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/2553?utm_source=stack-comment).

**Review by md2119 — APPROVED** [review]
What is the plan around removing SAC from datastore?

**Comment by rhybrillou** [comment]
> What is the plan around removing SAC from datastore?

The plan is first to port the Scope Access Control feature, then to clean redundant code where there is some.
Here it seems that some of the SAC checks that are performed are more complex than the ones present in the generated store code base, and some of them might stay.

**Review by rhybrillou — APPROVED** [review]

**Pull request merged**
