### PR TITLE
Update scanner version to 2.28.2

### PR DESCRIPTION
**Pull request by daynewlee**
## Description

Update scanner version to 2.28.2

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

CI is sufficient

### CODE REVIEW

**Comment by tommartensen** [comment]
@daynewlee @RTann this PR should be targeting the `release-3.74` branch directly. 
Note that OSCI will not notice if you change the base branch in the GH PR, so you'll need to open a new PR.

**Comment by RTann** [comment]
@tommartensen why does it need to target the release branch? Do we not just want to cherry-pick this?

**Comment by tommartensen** [comment]
My understanding is that the SCANNER_VERSION on master should be the floating tag, e.g. `2.28.x-...`. Merging to master + cherry-picking, and later changing to the floating tag are just additional steps that I thought we could avoid :)

**Comment by RTann** [comment]
> My understanding is that the SCANNER_VERSION on master should be the floating tag, e.g. `2.28.x-...`.

Not necessarily. Just the latest version

> Merging to master + cherry-picking, and later changing to the floating tag are just additional steps that I thought we could avoid :)

That's fine, but I am under the impression cherry-picking is the preferred method when master has not diverged too far from the release branch. I am pretty sure that is what we have been doing for past releases. Direct merges were typically reserved for older releases or commits which would have been difficult to cherry-pick due to master diverging too far from the release.

I will close this PR for @daynewlee since https://github.com/stackrox/stackrox/pull/4797 was merged

**Pull request closed without merging**
