### PR TITLE
ROX-15886: Skip UI e2e tests that are not relevant for OpenShift

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

* Cluster/Platform might not have any CVEs let alone fixable CVEs.
* Node might not have any CVEs let alone fixable CVEs.
* Image might not have fixable CVEs: passed here but had failed in #4817

### Files changed

1. Edit cypress/helpers/features.js
    * Delete unused default export.
    * Add `hasOrchestratorFlavor` function.

2. Edit cypress/integration/vulnmanagement/clusterCves.test.js for 3 / 4 tests:
    * should sort the CVSS Score column
    * should display vulnerability descriptions
    * should display links for clusters

3. Edit cypress/integration/vulnmanagement/clusters.test.js for 3 / 9 tests:
    * should display links for fixable image CVEs
    * should display links for all node CVEs
    * should display links for all cluster CVEs

4. Edit cypress/integration/vulnmanagement/deployments.test.js for 1 / 5 tests:
    * should display links for fixable image CVEs

5. Edit cypress/integration/vulnmanagement/entitypages.test.js for 5 / 11 tests:
    * related entities tile links should unset search params upon navigation
    * related entities table header should not say "0 entities" or have "page 0 of 0" if there are rows in the table
    * should scope deployment data based on selected policy from table row click
    * should scope deployment data based on selected policy from entity page tab sublist
    * should not filter cluster entity page regardless of entity context

6. Edit cypress/integration/vulnmanagement/imageComponents.test.js for 1 / 7 tests:
    * should display links for fixable image CVEs

7. Edit cypress/integration/vulnmanagement/images.test.js for 1 / 9 tests:
    * should display links for fixable image CVEs and also Risk Acceptance tabs

8. Edit cypress/integration/vulnmanagement/namespaces.test.js for 1 / 6 tests:
    * should display links for fixable image CVEs

9. Edit cypress/integration/vulnmanagement/nodeComponents.test.js for 3 / 6 tests:
    * should sort the Top CVSS column
    * should display links for all node CVEs
    * should display links for fixable node CVEs

10. Edit cypress/integration/vulnmanagement/nodeCves.test.js for 4 / 6 tests:
    * should sort the CVSS Score column
    * should display vulnerability descriptions
    * should display links for nodes
    * should display links for node-components

11. Edit cypress/integration/vulnmanagement/policies.test.js for 1 / 4 tests:
    * should display links for failing deployments

12. Edit scripts/cypress.sh
    * Copy `ORCHESTRATOR_FLAVOR` environment variable to the corresponding CYPRESS environment variable

## Checklist
- [x] Investigated and inspected CI test results
- [x] Skipped integration tests that are not relevant

## Testing Performed

* Ran tests locally with `export ORCHESTRATOR_FLAVOR=openshift` to verify conditional skip.
* Compared snapshots of previous failures with videos of recent successes to confirm that number of fixable CVEs is limited at best.

### CODE REVIEW

**Review by vjwilson — APPROVED** [review]
I'm a little concerned about skipping these entirely, but if we are still going to test, at least once in a while, on non-OpenShift infra, then it's okay.

**Comment by pedrottimark** [comment]
Yeah, we are balancing risks of false negatives versus false positives.
* OpenShift is in addition to GKE where the links are always tested.
* From what I have heard, improvements to node scanning might allow us to remove those skips in the future.
* On the other side of the coin, the original intent of the tests was to test workflow navigation, testing the ability to scan vulnerabilities is a secondary side effect. Although that is an important bonus, the immediate objective is unblock all integration testing in OpenShift.

**Comment by pedrottimark** [comment]
> but if we are still going to test, at least once in a while, on non-OpenShift infra, then it's okay.

@vjwilson you mean **manual testing** on OpenShift infra of functionality that is skipped in CI tests?

**Comment by vjwilson** [comment]
> @vjwilson you mean **manual testing** on OpenShift infra of functionality that is skipped in CI tests?

No, I mean running the CI in a non-OpenShift cluster, so that those tests still run, to account for self-hosted customers.

**Pull request merged**
