### PR TITLE
ROX-17674: Move sensor integration tests to a separate target

### PR DESCRIPTION
**Pull request by vikin91**
## Description

This is a followup to https://github.com/stackrox/stackrox/pull/6399. Here the sensor-integration-tests are removed from `nongroovy-e2e` and a added to the new target `gke-sensor-integration-tests`. Additionally, `ocp-4-*-sensor-integration-tests` are provided as optional (the tests are failing there).

The `ocp-4-*-sensor-integration-tests` are failing, but they are configured to not run automatically.
The 1:1 translation of the existing sensor-integration-tests are available as `gke-sensor-integration-tests` and those are passing.

## Checklist
- [x] Investigated and inspected CI test results

### N/A
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

## Testing Performed

- CI only with the new targets

### CODE REVIEW

**Comment by vikin91** [comment]
@fredrb removing the `nginx-sa` did not help for the OCP tests. Do you have any other ideas?

**Comment by lvalerom** [comment]
> Do you have any other ideas?

I think I found two problems with OCP.

1. OCP cannot resolve the image `nginx:1.14.2`. I just tried changing the image to `k8s.gcr.io/pause:3.1` and the deployment gets created.
2. There are a lot of errors upserting registries in the secrets dispatcher
```
kubernetes/listener/resources: 2023/06/14 18:02:35.288463 secrets.go:268: Error: Unable to upsert registry "image-registry.openshift-image-registry.svc:5000" into store: unable to check TLS for registry "image-registry.openshift-image-registry.svc:5000": dial tcp: lookup image-registry.openshift-image-registry.svc: no such host
```
This makes the test timeout before we even get to sync the initial deployments 😨 

I've commented [these lines](https://github.com/stackrox/stackrox/blob/064a92c29c213091b80cf9e0bb2aaa22b0c1dceb/sensor/kubernetes/listener/resources/secrets.go#L266-L269) in the secrets dispatcher and it works running:

```
go test -race -count=1 github.com/stackrox/rox/sensor/tests/connection
```

Obviously this is not the solution, we need to figure out how to solve those upserts, but at least it seems that there isn't anything fundamentally wrong with the tests 🙂

**Comment by vikin91** [comment]
Thanks @lvalerom ! I was able to reproduce the OCP failures locally with the command you provided.  

I have disabled the OCP tests in [5ccdbc8](https://github.com/stackrox/stackrox/pull/6416/commits/5ccdbc812b98f51e1f96316fc1cee7bc61490bf8) (replaced it with a dummy). There is a follow-up ticket to work on enabling them: https://issues.redhat.com/browse/ROX-17875

**Review by fredrb — APPROVED** [review]

**Comment by gavin-stackrox** [comment]
@vikin91 can you remove the OCP sensor integration tests from openshift/release also? They are currently set to run_if_changed which will cause 3 OCP clusters to get spun up if anyone modifies that (large) set of files on a PR even though the test won't run. Just removing the `run_if_changed` would also work. Then they would need to be explicitly requested via a PR comment to run.

**Pull request merged**
