### PR TITLE
chore: bump go 1.21.9

### PR DESCRIPTION
**Pull request by tommartensen**
## Description

A detailed explanation of the changes in your PR.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

TODO(replace-me)  
Use this space to explain **how you validated** that **your change functions exactly how you expect it**.
Feel free to attach JSON snippets, curl commands, screenshots, etc. Apply a simple benchmark: would the information you
provided convince any reviewer or any external reader that you did enough to validate your change.

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by vikin91** [comment]
We need the go.mod change with the toolchain here as well

**Comment by vikin91** [comment]
...and maybe `go mod tidy` run with 1.21.9.
Possibly some other changes to the libs will be necessary (e.g. slices vs sliceutils).

**Comment by vikin91** [comment]
> /go/src/github.com/stackrox/stackrox/go.mod:5: unknown directive: toolchain


something is wrong here with the go version. Are you sure OSCI is running 1.21?

**Comment by vikin91** [comment]
I will run `GOTOOLCHAIN=go1.21.9 make proto-generated-srcs && make go-generated-srcs` committing it asap

**Comment by tommartensen** [comment]
> Possibly some other changes to the libs will be necessary (e.g. slices vs sliceutils).

I looked at https://github.com/stackrox/stackrox/pull/10305 to determine the required changes, added all the `go mod tidy` updates and the CGOCHECKS changes.

**Comment by tommartensen** [comment]
> something is wrong here with the go version. Are you sure OSCI is running 1.21?

It's not running 1.21 yet, because the image mirroring is still not approved.

**Comment by tommartensen** [comment]
> I will run GOTOOLCHAIN=go1.21.9 make proto-generated-srcs && make go-generated-srcs committing it asap

That is a no-op, I ran it and no changes were required.

On the other hand, I applied https://github.com/stackrox/stackrox/pull/10375 to this branch.

**Comment by vikin91** [comment]
You are much quicker than me @tommartensen 😄 Let's see if CI is happy now

**Comment by tommartensen** [comment]
@vikin91 these failures are because we still haven't merged the OSCI changes :( 

https://github.com/openshift/release/pull/51515 is still unmerged / unapproved by DPTP.

**Comment by vikin91** [comment]
> @vikin91 these failures are because we still haven't merged the OSCI changes :(
> 
> [openshift/release#51515](https://github.com/openshift/release/pull/51515) is still unmerged / unapproved by DPTP.

I saw some other PR merged and got confused. You are right, this one is still open. What can we do to push things a bit?

**Comment by tommartensen** [comment]
> I saw some other PR merged and got confused. You are right, this one is still open. What can we do to push things a bit?

We have already pinged the helpdesk again last night, but it looks like the responsible engineer is OOO: https://redhat-internal.slack.com/archives/CBN38N3MW/p1714684748680149?thread_ts=1714635969.631919&cid=CBN38N3MW.

**Review by vikin91 — APPROVED** [review]

**Pull request merged**
