### PR TITLE
chore(e2e): Unskip openshift in compliance tests

### PR DESCRIPTION
**Pull request by pedrottimark**
## Description

Minimize differences in test coverage between gke and ocp.

## Checklist
- [x] Investigated and inspected CI test results
- [x] Edited integration tests

## Testing Performed

### CODE REVIEW

**Comment by pedrottimark** [comment]
First successful run above

/test gke-ui-e2e-tests
/test ocp-4-10-ui-e2e-tests
/test ocp-4-13-ui-e2e-tests

**Comment by pedrottimark** [comment]
Second successful run above

/test gke-ui-e2e-tests
/test ocp-4-10-ui-e2e-tests
/test ocp-4-13-ui-e2e-tests

**Comment by pedrottimark** [comment]
Third successful run, although retry for ocp-4-13-ui-e2e-tests

No failures were related to unskip test files.

**Review by vjwilson — APPROVED** [review]

**Pull request merged**
