### PR TITLE
validate duration settings

### PR DESCRIPTION
**Pull request by RTann**
## Description

* Panic upon registering duration setting with invalid default value.
* Only allow for users to set durations > 0. Otherwise, they do not make much sense.

## Checklist
- [x] Investigated and inspected CI test results
- ~[ ] Unit test and regression tests added~
- ~[ ] Evaluated and added CHANGELOG entry if required~
- ~[ ] Determined and documented upgrade steps~
- ~[ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI

### CODE REVIEW

**Review by misberner — CHANGES_REQUESTED** [review]
Don't we ever use `0` to indicate "never"? I think I found this at least for the notification debounce setting, possibly others as well.

**Review by misberner — CHANGES_REQUESTED** [review]
See other PR, we use a default of 0 for the alert notification debounce setting to indicate no debounce

**Comment by RTann** [comment]
> See other PR, we use a default of 0 for the alert notification debounce setting to indicate no debounce

@misberner which other PR?

**Comment by RTann** [comment]
> See other PR, we use a default of 0 for the alert notification debounce setting to indicate no debounce

I do see we use 0 for `ROX_ALERT_RENOTIF_DEBOUNCE_DURATION` and `ROX_RECORDER_DURATION` (which I don't think is used anymore?). That being said, allowing 0 makes sense, but I do feel there are times where 0 should not be allowed. I wonder if I should add an option to allow/disallow 0. What do you think?

**Comment by RTann** [comment]
PR to remove `ROX_RECORDER_DURATION` https://github.com/stackrox/stackrox/pull/3559

**Comment by misberner** [comment]
> @misberner which other PR?

I got two separate email threads because you renamed the PR, so I just assumed it was a different PR :) was on my phone

**Comment by misberner** [comment]
> I wonder if I should add an option to allow/disallow 0. What do you think?

Hmm, personally I would think that disallowing `0` durations should happen at the level of the logic that consumes the duration setting. But I guess you could make the case that a `0` duration that is not intercepted can be very dangerous when it leads to code running in a loop with no delay when there should be a delay between iterations, and thus consuming insane amounts of CPU. Therefore, yeah, I think it makes sense to prescribe that a `0` duration has to be allowed explicitly.

**Review by misberner — APPROVED** [review]

**Pull request merged**
