### PR TITLE
ROX-26295: Enable ROX_MICROSOFT_SENTINEL feature flag by default

### PR DESCRIPTION
**Pull request by SimonBaeumer**
### Description

Enable Microsoft Sentinel feature flag by default.

### CODE REVIEW

**Review by stehessel — COMMENTED** [review]
I'm sure the change is fine, but for completeness: What testing has been done to ensure correct functionality of the new notifier? I don't see it enabled on staging.demo.stackrox.com for example.

**Review by vjwilson — APPROVED** [review]
/lgtm

**Comment by SimonBaeumer** [comment]
> I'm sure the change is fine, but for completeness: What testing has been done to ensure correct functionality of the new notifier? I don't see it enabled on staging.demo.stackrox.com for example.

Thanks for asking @stehessel. The change was tested locally and on an instance provisioned by @vjwilson. It was reviewed by UI team and me. Now the documentation is written and a last pass is done. 
These changes are limited in scope, it adds a form and a notifier without impacting other components in StackRox, so the testing is relatively simple.

**Pull request merged**
