### PR TITLE
ROX-12274: Update Golang to 1.17.12

### PR DESCRIPTION
**Pull request by rukletsov**
Addendum to https://github.com/stackrox/stackrox/pull/2762.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

## Testing Performed

CI run.

### CODE REVIEW

**Comment by connorgorman** [comment]
@gavin-stackrox How do we bump the base CI image? I've run into this too

**Comment by RTann** [comment]
You'll need to update this line and the SHA as well https://github.com/stackrox/rox-ci-image/blob/master/images/stackrox-build.Dockerfile#L39

Once done, we'll need to bump the CI image in this repo (a PR should automatically be made via CI in the rox-ci-image repo)

**Comment by rukletsov** [comment]
> @gavin-stackrox How do we bump the base CI image? I've run into this too

@connorgorman I've found [this](https://github.com/stackrox/stackrox/blob/917c69412556b2d647c21be1bb2f2b33cf200ed8/.openshift-ci/Dockerfile.build_root#L13) but 😱 this is not for Friday evening. Hopefully I'll get us a new version of `stackrox-test` [soon](https://github.com/stackrox/rox-ci-image/pull/163).

**Comment by RTann** [comment]
Also, I think 1.17.13 is the latest 1.17.x version. Why not update to that instead? Is it not available downstream?

**Comment by rukletsov** [comment]
> Also, I think 1.17.13 is the latest 1.17.x version. Why not update to that instead? Is it not available downstream?

because potential FIPS compatibility, see [ROX-12274](https://issues.redhat.com/browse/ROX-12274).

**Comment by gavin-stackrox** [comment]
I would make the changes in the auto-created by rox-ci-image stackrox/stackrox PR i.e. https://github.com/stackrox/stackrox/pull/2762.
And follow the steps outlined in .openshift-ci/Dockerfile.build_root to test the update in CI.
(note: we will probably get rid of .openshift-ci/Dockerfile.build_root soon to improve CI performance, so this process will need to be documented)

**Comment by rukletsov** [comment]
https://github.com/stackrox/stackrox/pull/2762

**Pull request closed without merging**
