### PR TITLE
Dashrews/revert metadata service change that breaks old sensors

### PR DESCRIPTION
**Pull request by dashrews78**
## Description

This reverts #4195, #4218, and #4250 that were part of the updates to update the data returned with the `/metadata` endpoint to inform the caller if central could communicate with the database.  This caused compatibility issues as old sensors could not process the new field.  Which is why #4250 was needed.  This change reverts all the associate changes so we can ensure master is in a good state with compatability while we look for a less impactful solution to ROX-13963 and ROX-13964

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

TODO(replace-me)
Use this space to explain how you tested your PR, or, if you didn't test it, why
you did not do so. Valid reasons include, for example, "CI is sufficient",
"No testable changes". Feel free to attach JSON snippets, curl commands,
screenshots.

In addition to reviewing your code, reviewers **must** also review your testing
instructions and make sure they are sufficient.

### CODE REVIEW

**Review by dvail — APPROVED** [review]
LGTM on the UI side. We'll still want the banner for whatever the eventual solution is but we can pull that code from the initial commit when needed.

**Review by msugakov — APPROVED** [review]
Assuming reverts were done exclusively via `git revert` and there were no manual changes on top.

**Comment by dashrews78** [comment]
> Assuming reverts were done exclusively via `git revert` and there were no manual changes on top.

@msugakov only exception was I had to generate `central/graphql/resolvers/generated.go` as the flag got added to that in some other PR after my original one.

**Review by fredrb — APPROVED** [review]

**Pull request merged**
