### PR TITLE
upgrade-test: use helm for install and upgrade

### PR DESCRIPTION
**Pull request by gavin-stackrox**
## Description

The upgrade test is [failing](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-upgrade-tests/1544783120299986944) because:
- It deploys the latest scanner with an earlier rox.
- This is due to persisted latest scanner envs in `setup_deployment_env()`.
- The test in general does not care about scanner upgrade and so this might have been fine.
- But the earlier version of the UpgradeTest inherits from a BaseSpec that does a scanImage().
- And the latest scanner is not starting due to an incompatibility with the earlier configuration yaml.

This PR:
- removes the persistent scanner version env settings
- uses helm for the earlier rox deploy
- and uses helm for the upgrade so that scanner (and presumably other components) follow a supported upgrade path.

## Checklist
- [x] Investigated and inspected CI test results

## Testing Performed

CI is sufficient.

/test openshift-4-qa-e2e-tests

### CODE REVIEW

**Comment by RTann** [comment]
@gavin-stackrox we will need to add `scanner` and `scanner-db` `2.17.4` to quay. Let me do that now and then you should rerun CI

**Review by RTann — APPROVED** [review]
LGTM but I also want to confirm with either @connorgorman or @viswajithiii that switching this to Helm does not change the validity of the testing environment

**Comment by RTann** [comment]
Actually, I think the purpose of these tests is to ensure Central still works properly upon upgrade/downgrade, and the way we upgrade does not matter, so this should be good to go

**Review by connorgorman — APPROVED** [review]

**Review by viswajithiii — APPROVED** [review]

**Pull request merged**
