### PR TITLE
chore: Replace `.tar.gz.` with `.pb.gz` for pprof files

### PR DESCRIPTION
**Pull request by rukletsov**
## Description

To avoid confusion, give the pprof files a better extension.

### Here I tell how I validated my change

CI run

### CODE REVIEW

**Comment by JoukoVirtanen** [comment]
Here is how I tested this PR

```
git checkout alexr/use-pb-gz

./deploy/k8s/deploy-local.sh

kubectl -n stackrox port-forward deploy/central 8000:8443 &

export ROX_API_TOKEN=<rox_api_token>

./scale/profiler/pprof.sh scratch/central_heap_pr localhost:8000

cd scratch/central_heap_pr

gunzip heap_2023-10-31-16-55-28.pb.gz

go tool pprof ../../bin/linux_arm64/roxctl heap_2023-10-31-16-55-28.pb

svg
```

Check the other output as well.

**Comment by JoukoVirtanen** [comment]
Testing the secured cluster
```
./scripts/secured-cluster-diagnostics.sh

cd /tmp/k8s-service-logs/stackrox/metrics/

unzip sensor-c7d56d79d-v8lf8-heap.pb.gz

go tool pprof ~/go/src/github.com/stackrox/stackrox/bin/linux_arm64/roxctl sensor-c7d56d79d-v8lf8-heap.pb

svg
```

**Review by JoukoVirtanen — APPROVED** [review]
LGTM pending CI.

**Review by ivan-degtiarenko — APPROVED** [review]
LGTM assuming failing CI is unrelated

**Pull request merged**
