### PR TITLE
chore: mark not generated files as not generated

### PR DESCRIPTION
**Pull request by janisz**
## Description

Migration files are not generated anymore, they used to be generated or copied from a generated files but they are not generated anymore. Let's remove this false comments as it skips linters and reviews. 

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

make style

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by janisz** [comment]
Current dependencies on/for this PR:
* **#10177** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/10177?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/10177?utm_source=stack-comment).

**Comment by theencee** [comment]
Newer migrations _could_ be autogenerated though. Especially if you follow the [README](https://github.com/stackrox/stackrox/blob/master/migrator/README.md#writing-postgres-migration-tests). Especially if they were generated by `bootstrap_migration`

**Comment by dashrews78** [comment]
So the files from `m_188` to `m_199` are generated by either the bootstrap or the instructions from the `README` to build the schema or converters.  Do we really want to remove the generated tag from those since those files are still in fact generated?

**Comment by janisz** [comment]
@dashrews78 Good point. On one hand it's true they are generated but we are not able to generate them again as schema can change. If we want to keep them marked as generated then we should keep proto files for that migration and then generate them. Currently we have a situation when a file was generated and then any changes to it are not while it's still marked as generated skipping review and lint.

**Comment by dashrews78** [comment]
> @dashrews78 Good point. On one hand it's true they are generated but we are not able to generate them again as schema can change. If we want to keep them marked as generated then we should keep proto files for that migration and then generate them. Currently we have a situation when a file was generated and then any changes to it are not while it's still marked as generated skipping review and lint.

Yeah i understand the trickiness.  For the files we cannot re-generate such as these, would it make sense to change the tag to say something like `Originally generated by`?  The only issue is if we change our style or linting rules we may have to update those to keep them in compliance.

**Pull request closed without merging**
