### PR TITLE
feat(helm): add dbAffinity to scanner-db component

### PR DESCRIPTION
**Pull request by luciamota**
## Description

This merge requests adds support for changing affinities for scanner db component.
Current values were defined as default values for all components.

Feel free to remove this section if it is overkill for your PR, and the title of your PR is sufficiently descriptive.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

TODO(replace-me)  
Use this space to explain **how you validated** that **your change functions exactly how you expect it**.
Feel free to attach JSON snippets, curl commands, screenshots, etc. Apply a simple benchmark: would the information you
provided convince any reviewer or any external reader that you did enough to validate your change.

It is acceptable to assume trust and keep this section light, e.g. as a bullet-point list.

It is acceptable to skip testing in cases when CI is sufficient, or it's a markdown or code comment change only.  
It is also acceptable to skip testing for changes that are too taxing to test before merging. In such case you are
responsible for the change after it gets merged which includes reverting, fixing, etc. Make sure you validate the change
ASAP after it gets merged or explain in PR when the validation will be performed.  
Explain here why you skipped testing in case you did so.

Have you created automated tests for your change? Explain here which validation activities you did manually and why so.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by ludydoo** [comment]
Hello @luciamota, thank you for your contribution! The PR is marked as a draft. Is this ready for review?

**Comment by luciamota** [comment]
> Hello @luciamota, thank you for your contribution! The PR is marked as a draft. Is this ready for review?

Hello! Yes it is 😄 was just double checking the tests. Removed the Draft.

**Comment by mclasmeier** [comment]
Hi @luciamota, thank you for your contribution. Could you please rebase your PR from master?
Also, recently we have integrated Scanner V4, which will replace StackRox Scanner (the one which is affected by your change) in a future release. This change should also be applied to the Scanner V4. Would be you be interested in updating your PR to also make the affinities for Scanner V4 configurable?

Moritz

**Comment by luciamota** [comment]
Hi [mclasmeier](https://github.com/mclasmeier), It is rebased 😄 About the scanner v4, the affinities are already configurable (added here: https://github.com/stackrox/stackrox/pull/9943 )

**Pull request closed without merging**
