### PR TITLE
fix(bug): Update alert when image changes

### LINKED ISSUE #6995: Image version reported by StackRox does not always match what is deployed
Image version reported by StackRox does not always match what is deployed, after the image has updated. Image version reported in UX does not always match image version reported in API, for the same alert i.d.

StackRox has generated a finding and shows the image tag as `us.gcr.io/tcr/cvd-trn:1ad0d4ed267ac382ff1b440570c7b9ca059efeac` however the actual image running is correctly shown in GKE as the newer tagged image `us.gcr.io/tcr/cvd-trn:3dd962e809561ecb73705497b6ba627c106fb467` -- this image version was the result of a code rebuild but did not actually address the findings. The expecation is that StackRox should update the original alert i.d. with the latest tag 3dd, or close out the original alert i.d. and create a new alert for that deployment with the new image i.d., but it has done neither in this case and just remains stagnant showing the old version as if it is still deployed.

New images are released and the deployment is updated via `kubectl` set image commands, generally following the pattern:

```
kubectl rollout pause "deployment/$DEPLOYMENT" --namespace "$NAMESPACE"

 # The deadline is the K8s value for the deadline a deployment must succeed, this value is our main timeout value
deadline="$(kubectl get deployment $DEPLOYMENT --namespace $NAMESPACE -o jsonpath='{.spec.progressDeadlineSeconds}')"

kubectl set image "deployment/$DEPLOYMENT" "$CONTAINER_NAME=$IMAGE:$IMAGE_TAG" --namespace "$NAMESPACE" 
kubectl set image "deployment/$DEPLOYMENT" "$INIT_CONTAINER_NAME=$IMAGE:$IMAGE_TAG" --namespace "$NAMESPACE"

 log "$(bold "Waiting up to $deadline seconds for rollout to succeed, until $(date -d "+$deadline seconds"). This value is your deployment's progressDeadlineSeconds value (Progress deadline value in the GCP K8s console's details page for your deployment).")"
  kubectl rollout resume "deployment/$DEPLOYMENT" --namespace "$NAMESPACE" >&2
```

(this is an automated process within our CI/CD system). 

This process has not changed on our end in several years, and we have had our pipelines set up and StackRox and issues have been consistently updating as expected until now.

StackRox API and UX both still show the old image tag, despite the new deployment successfully have been updated in GKE and GKE shows the new image tag everywhere for both the main container and init container versions.

```
"containers": [
            {
                "image": {
                    "id": "sha256:f66b8d9ef6f51008b92304ee0e5cfcd1c29cc5ee513b973be3cf76a9ff498b9e",
                    "name": {
                        "registry": "us.gcr.io",
                        "remote": "tcr/workflows-cvd-trn",
                        "tag": "1ad0d4ed267ac382ff1b440570c7b9ca059efeac",
                        "fullName": "us.gcr.io/tcr/cvd-trn:1ad0d4ed267ac382ff1b440570c7b9ca059efeac"
                    },
                    "notPullable": false,
                    "isClusterLocal": false
                },
                "name": "main"
            }
        ],
```

and it is still listed as ACTIVE state:
```
    "processViolation": null,
    "enforcement": null,
    "time": "2023-06-17T07:47:01.076485872Z",
    "firstOccurred": "2023-03-06T20:21:55.016633955Z",
    "resolvedAt": null,
    "state": "ACTIVE",
    "snoozeTill": null
```

The image version reported in the UX matches what the API returns.

Restarting sensors has fixed the issue so the correct versions are seen, but the problem reoccurs days later. 

I am also seeing examples where the UX has the currently deployed image tag listed correctly, but the API for the same alert i.d. returns an old image tag.

This example with this issue was originally generated via StackRox 3.74.0, and it was subsequently upgraded to 4.0.0, and the kubectl set image commands were ran a few weeks after that under 4.0.0.

### PR DESCRIPTION
**Pull request by connorgorman**
## Description

This may fix #6995, though it is confusing why the image would ever have been updated in the alert as we were ignoring the deployment object in our hashing. This will just ignore annotations and labels which can change more frequently and for arbitrary. It's debatable if we should also ignore labels, but annotations seems reasonable.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI and will run a manual upgrade test

### CODE REVIEW

**Comment by md2119** [comment]
> though it is confusing why the image would ever have been updated in the alert as we were ignoring the deployment object in our hashing.

Could it be that we are changing the object that the pointer is pointing at after alert object is created in sensor?

**Review by theencee — APPROVED** [review]

**Comment by mclasmeier** [comment]
Just looking here while doing OSS triaging. Should we merge this as an attempt to fix https://github.com/stackrox/stackrox/issues/6995? Are there any additional findings/updates? Thanks!

**Comment by Maddosaurus** [comment]
@connorgorman Any updates on this PR? Could we merge it to see if it fixes #6995 and #6737?

**Comment by danekantner** [comment]
Also just to clarify -- the examples I have are now often showing the CVE still in the alert in the UX and API even though the new image (that the API shows) has fixed that issue. It's almost as if it's supposed to be rolling out an old alert and replacing with a new and isn't, because by definition of stackrox' internal rules it is set to reuse that alert for even a new image.

**Pull request merged**
