### PR TITLE
chore(test): 4 0 upgrade test cherry picks

### PR DESCRIPTION
**Pull request by dashrews78**
## Description
Pulls a couple of upgrade tests fixes that should resolve upgrade test failures on the 4.0 release.

## Checklist
- [ ] Investigated and inspected CI test results
~- [ ] Unit test and regression tests added~
~- [ ] Evaluated and added CHANGELOG entry if required~
~- [ ] Determined and documented upgrade steps~
~- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs]~(https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

CI

### CODE REVIEW

**Review by gavin-stackrox — APPROVED** [review]
CI looks pretty bad but I don't think that is due to your cherry-picks.

**Comment by dashrews78** [comment]
> CI looks pretty bad but I don't think that is due to your cherry-picks.

yeah my plan is to try and slowly work my way through those too as I believe most of those to have been fixed elsewhere.

**Pull request merged**
