### PR TITLE
ROX-18084: Use Compliance Operator package

### PR DESCRIPTION
**Pull request by rhmdnd**
## Description

Central and sensor both use Compliance Operator CRDs to watch for
compliance changes on secured clusters and ship them off to central.
However, this dependency was managed manually by copying the CRDs into
the stackrox package. This was a workaround due to some dependency
issues when stackrox initially integrated with the Compliance Operator
that prevented stackrox from tracking the Compliance Operator as a
formal dependency using go modules. This has been fixed recently in:

https://github.com/stackrox/stackrox/pull/6757

This commit updates the Compliance Operator usage within stackrox to use
the go package, instead of the copy/pasted source. This allows us to
treat the Compliance Operator like any other dependency, and avoid
maintaining duplicated code between stackrox and the Compliance
Operator.

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [x] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

## Testing Performed

In the process of testing with existing Compliance Operator tests - which should continue to work even though we're using a different dependency for the CRDs.

https://github.com/stackrox/stackrox/blob/master/tests/compliance_operator_test.go

### CODE REVIEW

**Comment by rhmdnd** [comment]
Some failures were the result of merge conflicts - resolved locally and rebased on master.

**Comment by rhmdnd** [comment]
Looks like the Compliance Operator was already added as a formal dependency in https://github.com/stackrox/stackrox/commit/48c541509a5768f58af62030c1b53bb9bcb6ec27#diff-2112119165755d65a04c17cdb671fc5fc2c79141ba4f79193b76ae9f61c0227d

I can rebase this to cleanup the copied code.

**Comment by rhmdnd** [comment]
Looking through the compliance tests and found:

```
 ComplianceTest > Verify checks based on Policies STANDARD_OUT
    21:07:55 | INFO  | ComplianceTest            | Starting testcase
    21:07:55 | INFO  | Services                  | Updated lifecycleStage of 'Fixable Severity at least Important' to [BUILD, DEPLOY]
    21:08:06 | INFO  | Services                  | Updated enforcement of 'Fixable Severity at least Important' to [FAIL_BUILD_ENFORCEMENT, SCALE_TO_ZERO_ENFORCEMENT]
    21:08:16 | INFO  | Services                  | Updated enforcement of 'Privileged Container' to [SCALE_TO_ZERO_ENFORCEMENT]
    21:08:27 | INFO  | Services                  | Updated enforcement of '90-Day Image Age' to [FAIL_BUILD_ENFORCEMENT, SCALE_TO_ZERO_ENFORCEMENT]
    21:08:37 | INFO  | Services                  | Updated enforcement of 'Latest tag' to [FAIL_BUILD_ENFORCEMENT, SCALE_TO_ZERO_ENFORCEMENT]
    21:08:48 | INFO  | Services                  | Updated enforcement of 'Ubuntu Package Manager Execution' to [KILL_POD_ENFORCEMENT]
    21:08:58 | INFO  | Services                  | Updated enforcement of 'Environment Variable Contains Secret' to [SCALE_TO_ZERO_ENFORCEMENT]
    21:08:58 | ERROR | PolicyService             | error creating new policy
    io.grpc.StatusRuntimeException: INVALID_ARGUMENT: policy invalid error: error validating lifecycle stage error: policy configuration is invalid for deploy time: policy validation error: validation of section "" error: policy criteria "Environment Variable" has invalid value[0]=".*SECRET.*=.*" must match regex "((?m)^(?i:(UNSET|RAW|UNKNOWN|^)=([^=]*)=.*)|((SECRET_KEY|CONFIG_MAP_KEY|FIELD|RESOURCE_FIELD)=([^=]*)=$)$)": invalid arguments
    	at io.stackrox.proto.api.v1.PolicyServiceGrpc$PolicyServiceBlockingStub.postPolicy(PolicyServiceGrpc.java:1144) [3 skipped]
    	at services.PolicyService.createNewPolicy(PolicyService.groovy:29) [1 skipped]
    	at ComplianceTest.$spock_feature_1_12(ComplianceTest.groovy:910) [1 skipped]
    	at util.OnFailureInterceptor.intercept(OnFailure.groovy:72) [9 skipped]
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151) [8 skipped]
    	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
    	at util.OnFailureInterceptor.intercept(OnFailure.groovy:72) [6 skipped]
    	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) [4 skipped]
     [4 skipped]
    21:08:58 | DEBUG | ComplianceManagementService | triggered NIST_800_190 compliance run
    21:08:58 | DEBUG | ComplianceManagementService | waiting for the run to finish...
    21:09:00 | DEBUG | ComplianceManagementService | Compliance run took 2.139s
    21:09:01 | DEBUG | ComplianceManagementService | triggered NIST_SP_800_53_Rev_4 compliance run
    21:09:01 | DEBUG | ComplianceManagementService | waiting for the run to finish...
    21:09:03 | DEBUG | ComplianceManagementService | Compliance run took 2.141s
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_800_190:4_1_1
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_800_190:4_1_2
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_800_190:4_1_4
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_800_190:4_2_2
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_SP_800_53_Rev_4:CM_2
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_SP_800_53_Rev_4:CM_3
    21:09:03 | INFO  | ComplianceTest            | Validating deployment control NIST_SP_800_53_Rev_4:IR_4_(5)
    21:09:13 | INFO  | Services                  | Updated enforcement of 'Fixable Severity at least Important' to [FAIL_BUILD_ENFORCEMENT]
    21:09:23 | INFO  | Services                  | Updated enforcement of 'Privileged Container' to have no enforcement actions
    21:09:34 | INFO  | Services                  | Updated enforcement of '90-Day Image Age' to have no enforcement actions
    21:09:44 | INFO  | Services                  | Updated enforcement of 'Latest tag' to have no enforcement actions
    21:09:54 | INFO  | Services                  | Updated enforcement of 'Ubuntu Package Manager Execution' to have no enforcement actions
    21:10:05 | INFO  | Services                  | Updated enforcement of 'Environment Variable Contains Secret' to have no enforcement actions
    21:10:05 | INFO  | Services                  | Updated lifecycleStage of 'Fixable CVSS >= 7' to [DEPLOY]
    21:10:05 | INFO  | ComplianceTest            | Ending testcase 
```

**Review by md2119 — APPROVED** [review]

**Comment by rhmdnd** [comment]
Both the `ocp-4-10-qa-e2e-tests` and `ocp-4-10-sensor-integration-tests` failed provision a cluster.

**Comment by rhmdnd** [comment]
Does this need a change log entry? From my understanding this is an internal change, but wondering if this still requires a change log regardless.

**Pull request merged**
