### PR TITLE
ROX-23540: Add Central cap to display Internal Entities in the NWG 

### PR DESCRIPTION
**Pull request by vikin91**
## Description

Central has now a capability to mark that it is able to display the 'Internal Entities' node on the network graph. If this cap is missing, Sensor would return all internal entities as external entities (as those are supported by older centrals). 

## Checklist
- [x] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

I manually deployed various combinations of Central and Sensor and looked at the Network Graph for the `stackrox` namespace. Here are the results:

#### (1) Reproducing the bug: Central 4.3.6, Sensor 4.4.0

Result: ❌  Network Graph does not load

central-4 3 6-sensor-4 4 0-nwg-does-not-load

#### (2) Fixing the bug: Central 4.3.6, Sensor this PR

Result: ✅ Network Graph works, all unknown flows are treated as external (default behavior for versions 4.3 and older)

central-4 3 6-sensor-this-PR

#### (3) Checking backwards compat of this patch: Central: this PR, Sensor 4.4.0

Result: All good, internal entities are visible. Adding Central capability first in this PR, does not prevent 4.4.0 Sensor from sending flows of type 5 (internal).

central-this-PR-sensor-4 4 0-internal-OK

#### (4) Checking deeper backwards compat of this patch: Central: this PR, Sensor 4.3.6

Result: ✅ Sensor sends only flows of type 4 (external) as type 5 (internal) was not implemented in 4.3. 

central-this-PR-sensor-4 3 6-only-external

#### (5) Checking new installs: Central this PR, Sensor this PR

Result: ✅ internal entities are visible. Sensor recognizes Central's capability and sends flows of type 5 (internal).

central-this-PR-sensor-this-PR-internal-OK

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and

 you are satisfied with it.

### CODE REVIEW

**Review by lvalerom — APPROVED** [review]
LGTM.

I'm a little bit confused with test (3) `Central: this PR, Sensor 4.4.0` You said `Sensor recognizes Central's capability and sends flows of type 5` but my understanding is that this works because Central in this PR understand internal entities but Sensor is unaware of the capability. In other words Sensor 4.4.0 will always send the internal entities and so it happens that central in this PR understand them, right?

**Comment by vikin91** [comment]
> LGTM.
> 
> I'm a little bit confused with test (3) `Central: this PR, Sensor 4.4.0` You said `Sensor recognizes Central's capability and sends flows of type 5` but my understanding is that this works because Central in this PR understand internal entities but Sensor is unaware of the capability. In other words Sensor 4.4.0 will always send the internal entities and so it happens that central in this PR understand them, right?

You are right, the description is confusing. It should rather say: "Adding Central capability first in this PR, does not prevent Sensor from sending flows of type 5." I will edit the description.

**Pull request merged**
