### PR TITLE
ROX-16935: Make PolicyConfigurationTest multi-arch compliant

### PR DESCRIPTION
**Pull request by pratham-m**
This PR intends to fix failures on P/Z with `PolicyConfigurationTest`. Changes in the test would make it multi-arch compliant.
Changes are verified manually using `./gradlew test --tests=TestName`

This PR intends to fix [ROX-16935](https://issues.redhat.com/browse/ROX-16935)

### CODE REVIEW

**Comment by pratham-m** [comment]
@gavin-stackrox  @robbycochran kindly review this PR

**Review by gavin-stackrox — APPROVED** [review]
LGTM, tests are :white_check_mark:

**Comment by pratham-m** [comment]
thanks @gavin-stackrox. 
merging since all tests are passing.

**Pull request merged**
