### PR TITLE
fix(ui): Show formatted time in Vuln Def widget

### PR DESCRIPTION
**Pull request by vjwilson**
## Description

Bringing displayed time into alignment with rest of time display in app

## Checklist
- [ ] Investigated and inspected CI test results

## Testing Performed

Before
Screen Shot 2023-06-08 at 4 21 24 PM

After
Screen Shot 2023-06-08 at 4 24 09 PM

### CODE REVIEW

**Comment by pedrottimark** [comment]
@vjwilson ISO 8601 time format is same format as log files so people for failure (or success). How many decimal digits precision in the fractions of a second is worth follow up with log files in case there is any rounding or truncation there.

Formatted time means a mental and time zone conversion to UTC as a prerequisite to search.

**Comment by vjwilson** [comment]
@pedrottimark 

> 4\. Absolute date of an event within product or in customer environment: ISO 8601 UTC primary, classic format secondary.

If I understand correctly, case 4 would apply here. We could show the UTC by default, and the classic format in a tooltip. Or is there a different style we are already using?

I found in an actual Central log that we are using 6 digits to the right of the decimal in timestamps, so we should trim (round?) the displayed UTC to that.

cc: @mansursyed

**Comment by pedrottimark** [comment]
Yes, thank you for verifying the precision in central log. I was in too much of a hurry at the time.

**Comment by 0x656b694d** [comment]
I guess this PR is not about in which format to show the time, but to align this case with others. It confuses me (i.e. drives me crazy) all the time when I see 01/02/2023, as I always have to figure out where is the month.

**Review by 0x656b694d — APPROVED** [review]

**Pull request closed without merging**
