### PR TITLE
chore: remove cloud credentials feature flag

### PR DESCRIPTION
**Pull request by stehessel**
### Description

Remove the cloud credentials feature flag and turn it on permanently.

### User-facing documentation

(*must be* 2 items and both *must be* checked)

- [x] CHANGELOG is updated
- [ ] CHANGELOG update is not needed
- [ ] Documentation PR is created and linked above
- [x] Documentation is not needed

### Testing

- [x] inspected CI results

#### Automated testing

(*must be* at least 1 item and all items *must be* checked)

- [ ] added unit tests
- [ ] added e2e tests
- [ ] added regression tests
- [ ] added compatibility tests
- [ ] modified existing tests
- [x] contributed **no automated tests**
  

#### How I validated my change

change me!

### CODE REVIEW

**Review by dvail — APPROVED** [review]
Approving for the UI side, changes look good. 👍

**Review by pedrottimark — APPROVED** [review]
Super, thank you!

**Pull request merged**
