### PR TITLE
ROX-20714: Add regression unit test for the ClusterIP issue

### PR DESCRIPTION
**Pull request by vikin91**
## Description

This PR adds unit test for `clusterentities.Store`. The tests are simple, but they highlight the problem of intentionally dropping all past IPs for a container when an update is applied in non-incremental mode.

A change of IP address for a Service in a cluster leads to a non-incremental change to the `clusterentities.Store`. This causes that all past IPs of the container are forgotten and if any connection is reported by Collector to those past IPs, the egde in the Network Graph would point to "External Entities" (although the entity is/was not external).

## Checklist
- [x] Investigated and inspected CI test results
- [x] Unit test and regression tests added

### N/A
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

It is a unit test, so I validated it by running it.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by vikin91** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8626** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/8626?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #8648** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/8648?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/8626?utm_source=stack-comment).

**Comment by Maddosaurus** [comment]
The tests are looking good structure-wise, I have trouble understanding the `incremental` concept in the code, though.
When we fix this behaviour, it would make no difference whether the `incremental` flag is set or not. Does this make the flag obsolete? Do we know why it was there in the first place?

**Comment by vikin91** [comment]
Let me explain what incremental is doing. In the context of this PR, we can add multiple IP addresses (endpoints) to a container. Calling `entityStore.Apply()` with `incremental=true` will add IP address to a set of IP addresses for that container - having N endpoints for a container and calling `Apply` with `incremental=true` would result in N+1 endpoints for that container.

Calling the same `Apply` with `incremental=false` causes all existing endpoints for a container to be deleted before adding a new endpoint - having N endpoints for a container and calling `Apply` with `incremental=false` would result in having 1 endpoint for that container.

**Comment by Maddosaurus** [comment]
Thanks for the explanation!
With that understanding, a follow up question that will only be relevant for the implementation, not this test:
Do we need to change the returned format of IPs? Right now, all *currently known* endpoints are returned. with `incremental=false`, we overwrite them as of today. If we change the logic to retain old IPs like you defined in your test [here](https://github.com/stackrox/stackrox/pull/8626/files#diff-88971c6789d190c167361854897680b2db9ad16299a935e6a1669d1e4dc807f9R105), the caller cannot distinguish between currently active and historical endpoint IPs, correct?

(Nit: If that is the only functionality this flag changes, I would be in favor of renaming it to something more intuitive, e.g. `append` in a future refactor)

**Comment by vikin91** [comment]
> Do we need to change the returned format of IPs? Right now, all currently known endpoints are returned. with incremental=false, we overwrite them as of today. If we change the logic to retain old IPs like you defined in your test [here](https://github.com/stackrox/stackrox/pull/8626/files#diff-88971c6789d190c167361854897680b2db9ad16299a935e6a1669d1e4dc807f9R105), the caller cannot distinguish between currently active and historical endpoint IPs, correct?

Yes, this is correct. I still don't know if the return format should change. I see both options (changing and not changing) as possible.
- Adding ability to tell if the connection is historical or not - this would be required only if we add a new type of graph-edge to the UI. Otherwise this information is not necessary.
- Returning all IPs without info which is current which is past. There are actually 2 options to implement that: 1) Returning a modified structure that would mark each endpoint as "historical", 2) Keep `LookupByEndpoint` as it is (and return all IPs mixed) but add another method to return only the current ones (or only the historical ones).

> (Nit: If that is the only functionality this flag changes, I would be in favor of renaming it to something more intuitive, e.g. append in a future refactor)

This is a good idea and we may use it. Or split the `Apply` call into two `Add` & `Replace`

**Review by Maddosaurus — APPROVED** [review]

**Review by fredrb — APPROVED** [review]

**Pull request merged**
