### PR TITLE
fix(scanv4): Sec cluster tweaks for same namespace deploy

### PR DESCRIPTION
**Pull request by dcaravel**
## Description

Adjusts the secured cluster helm chart so that the DB components are not created when installing into the same namespace as central services. This was causing an error preventing install.

Also adjusts the conditions in sensor's helm yaml so that the scanner v4 environment variables are created for single cluster deployments.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] ~Unit test and regression tests added~
- [ ] ~Evaluated and added CHANGELOG entry if required~
- [ ] ~Determined and documented upgrade steps~
- [ ] ~Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))~

#### Disabling Scanner V4 DB in Sec Cluster

On infra cluster, installed central services helm chart with Scanner V4 enabled. Then installed the secured cluster services chart with scanner V4 enabled.

Before this change encountered error:

```
...
Release "stackrox-secured-cluster-services" does not exist. Installing it now.
Error: Unable to continue with install: NetworkPolicy "scanner-v4-db" in namespace "stackrox" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "stackrox-secured-cluster-services": current value is "stackrox-central-services"
```

After the change:
```
...
Release "stackrox-secured-cluster-services" does not exist. Installing it now.
NAME: stackrox-secured-cluster-services
LAST DEPLOYED: Tue Jan  9 16:03:35 2024
NAMESPACE: stackrox
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
StackRox Secured Cluster Services 4.3.x-661-gbdfb7c38a7-dirty has been installed.


Secured Cluster Configuration Summary:

  Name:                                        remote
  Kubernetes Namespace:                        stackrox
  Helm Release Name:                           stackrox-secured-cluster-services
  Central Endpoint:                            34.23.124.180:443
  OpenShift Cluster:                           4 
  Admission Control Webhooks deployed:         
  Admission Control Creates/Updates enforced:  false
  Scanner v4 Installation Method:              indexer-only

Please take note of the following:

- Based on API server properties, we have inferred that you are deploying into an OpenShift 4.x
  cluster. Set the `env.openshift` property explicitly to 3 or 4 to override the auto-sensed value.
- PodSecurityPolicies are disabled, since your environment does not support them according to API
  server properties.
- Detected central running in the same namespace. Not deploying scanner from this chart and
  configuring sensor to use existing scanner instance, if any.
- Detected central running in the same namespace. Not deploying scanner-v4-indexer from this chart
  and configuring sensor to use existing scanner-v4-indexer instance, if any.

During installation, the following warnings were encountered:

- WARNING: You have specified an explicit main image (tag). This will prevent the main image from being
  updated correctly when upgrading to a newer version of this chart.
- WARNING: You have specified an explicit collector image tag. This will prevent the collector image from
  being updated correctly when upgrading to a newer version of this chart.

IMPORTANT: You have deployed into an OpenShift-enabled cluster. If you see that your pods
           are not scheduling, run

             oc annotate namespace/stackrox --overwrite openshift.io/node-selector=""
Thank you for using StackRox!
```

#### Set Scanner V4 env vars when deploying to same namespace as Central

Verified that the meta-templating was working as expected by setting feature `ROX_SCANNER_V4_SUPPORT` (unchangeable feature) to `false` in `pkg/features/list.go`, rebuilding roxctl, and examining the output of `sensor.yaml` to confirm it does not contain the Scanner V4 'stuff':

```
$ make cli_darwin-arm64
...

$ ./bin/darwin_arm64/roxctl helm output secured-cluster-services --image-defaults=development_build --debug-path=./image --debug --remove
...

$ cat ./stackrox-secured-cluster-services-chart/templates/sensor.yaml | grep "localImageScanning" -A 12
        {{- if ._rox.sensor.localImageScanning.enabled }}
        - name: ROX_SCANNER_GRPC_ENDPOINT
          value: {{ printf "scanner.%s.svc:8443" .Release.Namespace }}
        - name: ROX_LOCAL_IMAGE_SCANNING_ENABLED
          value: "true"
        {{- end }}
        - name: ROX_HELM_CLUSTER_CONFIG_FP
          value: {{ quote ._rox._configFP }}
        {{- if ._rox.monitoring.openshift.enabled }}
        - name: ROX_ENABLE_SECURE_METRICS
          value: "true"
        {{- end }}
        {{- include "srox.envVars" (list . "deployment" "sensor" "sensor") | nindent 8 }}

$ cat ./stackrox-secured-cluster-services-chart/templates/sensor.yaml | grep -iE "scannerv4|scanner_v4"
```
Notice the Scanner V4 conditions are not present.

Setting feature `ROX_SCANNER_V4_SUPPORT` to `true` and repeating yields desired result:

```
$ make cli_darwin-arm64
...

$ ./bin/darwin_arm64/roxctl helm output secured-cluster-services --image-defaults=development_build --debug-path=./image --debug --remove
...

$ cat ./stackrox-secured-cluster-services-chart/templates/sensor.yaml | grep "localImageScanning" -A 14
        {{- if ._rox.sensor.localImageScanning.enabled }}
        - name: ROX_SCANNER_GRPC_ENDPOINT
          value: {{ printf "scanner.%s.svc:8443" .Release.Namespace }}
        - name: ROX_LOCAL_IMAGE_SCANNING_ENABLED
          value: "true"
        {{- end }}
        - name: ROX_HELM_CLUSTER_CONFIG_FP
          value: {{ quote ._rox._configFP }}
        {{- if ._rox._scannerV4Enabled }}
        - name: ROX_SCANNER_V4_GRPC_ENDPOINT
          value: {{ printf "scanner-v4-indexer.%s.svc:8443" .Release.Namespace }}
        - name: ROX_SCANNER_V4
          value: "true"
        {{- end }}
        {{- if ._rox.monitoring.openshift.enabled }}

$ cat ./stackrox-secured-cluster-services-chart/templates/sensor.yaml | grep -iE "scannerv4|scanner_v4"
        
        {{- if ._rox._scannerV4Enabled }}
        - name: ROX_SCANNER_V4_GRPC_ENDPOINT
        - name: ROX_SCANNER_V4
```

Also tested deploying the on a single cluster and multi-cluster to verify that the env vars were set appropriately.

Pods from single cluster deployment:

```
$ k get pods
NAME                                  READY   STATUS    RESTARTS       AGE
admission-control-7ddf65b49f-hqlgl    1/1     Running   0              34s
admission-control-7ddf65b49f-kfl2x    1/1     Running   0              34s
admission-control-7ddf65b49f-qj747    1/1     Running   0              33s
central-6bd6bf8b4f-25p9q              1/1     Running   0              95s
central-db-ffc9b5d55-twqh9            1/1     Running   0              2m7s
collector-4jjpq                       3/3     Running   0              34s
collector-6bwwr                       3/3     Running   0              34s
collector-bcl95                       3/3     Running   0              34s
collector-rkvdz                       3/3     Running   0              34s
collector-tlgfp                       3/3     Running   0              34s
scanner-86dd47fd4c-b2n9z              1/1     Running   0              2m7s
scanner-db-757b9cd574-8jnqx           1/1     Running   0              2m7s
scanner-v4-db-7d9cc7d787-6tb6m        1/1     Running   0              2m7s
scanner-v4-indexer-5468bd9c89-wr4k7   1/1     Running   2 (115s ago)   2m7s
scanner-v4-matcher-6f8464768c-25pwm   1/1     Running   2 (115s ago)   2m7s
sensor-b586bc7c4-gx7pq                1/1     Running   0              34s
```

On a single cluster deployment with `scannerV4.disable: false`

```
$ k get deploy sensor -o yaml | yq '.spec.template.spec.containers[].env' | grep "SCANNER_V4" -A1
- name: ROX_SCANNER_V4_GRPC_ENDPOINT
  value: scanner-v4-indexer.stackrox.svc:8443
- name: ROX_SCANNER_V4
  value: "true"
```

On a single cluster deployment with `scannerV4.disable: true`

```
$ k get deploy sensor -o yaml | yq '.spec.template.spec.containers[].env' | grep "SCANNER_V4" -A1
<empty>
```

Dedicated cluster deploy with `scannerV4.disable: false`

```
$ k get deploy sensor -o yaml | yq '.spec.template.spec.containers[].env' | grep "SCANNER_V4" -A1
- name: ROX_SCANNER_V4_GRPC_ENDPOINT
  value: scanner-v4-indexer.stackrox.svc:8443
- name: ROX_SCANNER_V4
  value: "true"
```

Dedicated cluster deploy with `scannerv4.disable: true`

```
$ k get deploy sensor -o yaml | yq '.spec.template.spec.containers[].env' | grep "SCANNER_V4" -A1
<empty>
```

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by dcaravel** [comment]
Hrm, this is not enough, the various sensor env vars for Scanner V4 are not set if indexer is disabled, which would be the case when installing in same namespace as Central.  May need some other variable to track if scanner V4 is 'enabled' but the individual components are not.

**Comment by mclasmeier** [comment]
I agree with all your findings and conclusions @dcaravel.

**Comment by dcaravel** [comment]
@mclasmeier @RTann - Updated the condition in the sensor deploy to account for single cluster deploys.  Noticed when testing deploying to a dedicated secured cluster the `scanner-v4-*-tls` secrets are not created - however sensor logs indicate that they were being created (see below) - the secrets not being created is unrelated to this change as far as I can tell - but something that needs attention.

```
kubernetes/localscanner: 2024/01/10 17:29:40.583165 cert_refresher.go:109: Warn: local scanner certificates not found (this is expected on a new deployment), will refresh certificates immediately: 5 errors occurred:
	* secrets "scanner-v4-matcher-tls" not found
	* secrets "scanner-v4-db-tls" not found
	* secrets "scanner-tls" not found
	* secrets "scanner-db-tls" not found
	* secrets "scanner-v4-indexer-tls" not found
```

```
$ k get secret
NAME                                                      TYPE                             DATA   AGE
admission-control-tls                                     Opaque                           3      3m5s
collector-tls                                             Opaque                           3      3m3s
helm-cluster-config                                       Opaque                           1      2m53s
helm-effective-cluster-name                               Opaque                           1      3m1s
scanner-db-password                                       Opaque                           1      3m
scanner-db-tls                                            Opaque                           3      2m44s
scanner-tls                                               Opaque                           3      2m45s
scanner-v4-db-password                                    Opaque                           1      2m58s
secured-cluster-services-collector                        kubernetes.io/dockerconfigjson   1      2m56s
secured-cluster-services-main                             kubernetes.io/dockerconfigjson   1      2m55s
sensor-tls                                                Opaque                           3      2m53s
service-ca                                                Opaque                           1      2m53s
sh.helm.release.v1.stackrox-secured-cluster-services.v1   helm.sh/release.v1               1      3m6s
```

**Review by RTann — APPROVED** [review]

**Comment by RTann** [comment]
> Updated the condition in the sensor deploy to account for single cluster deploys. Noticed when testing deploying to a dedicated secured cluster the scanner-v4-*-tls secrets are not created - however sensor logs indicate that they were being created (see below) - the secrets not being created is unrelated to this change as far as I can tell - but something that needs attention.

Let's make a ticket for this. That being said, since we see the same errors for Scanner v2, it's probably just a noisy log rather than a real error. Let me know if you think otherwise

**Review by mclasmeier — COMMENTED** [review]
As depicted in my version of the PR I would suggest to move the code from image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl doing the lookup for central to the common scanner v4 init code, but it doesn't necessarily have to be part of this fix.

**Comment by dcaravel** [comment]
> Update: Actually I'm confused. The logs say it cannot find Scanner TLS, yet it exists. Also Sensor should not care about the matcher

The `k get secrets` was ran after that log entry appeared in Sensor - so at that point Sensor would have / should have created all the missing secrets, the applicable scanner-v4 secrets should be in that output but aren't.

**Comment by dcaravel** [comment]
> As depicted in my version of the PR I would suggest to move the code from image/templates/helm/stackrox-secured-cluster/templates/_init.tpl.htpl doing the lookup for central to the common scanner v4 init code, but it doesn't necessarily have to be part of this fix.

Unless you beat me to it, I can make this update - have to update the PR to address conflicts as well.

**Comment by mclasmeier** [comment]
> > Update: Actually I'm confused. The logs say it cannot find Scanner TLS, yet it exists.
> 
> The `k get secrets` was ran after that log entry appeared in Sensor - so at that point Sensor would have / should have created all the missing secrets, the applicable scanner-v4 secrets should be in that output but aren't.
> 
> > Also Sensor should not care about the matcher
> 
> Good catch. @mclasmeier could you look into that?

Yes, but probably not today.

**Review by mclasmeier — APPROVED** [review]

**Pull request merged**
