### PR TITLE
chore(usage): rename product usage to administration usage

### PR DESCRIPTION
**Pull request by dhaus67**
## Description

This PR renames the product usage feature to administration usage.

The decision was made to align the naming of the feature closer to the `Administration Events` feature.

Since the feature itself is in tech preview, renaming this without the usual deprecation cycle is OK.

At the current time, the changes do **not** contain a migration, since only the search category changed and it seems as if things related to the search category are handled in-memory. Depending on whether this assumption holds true, the PR may be extended to also do a postgres migration.

## Checklist
- [ ] Investigated and inspected CI test results
- [ ] Unit test and regression tests added
- [ ] Evaluated and added CHANGELOG entry if required
- [ ] Determined and documented upgrade steps
- [ ] Documented user facing changes (create PR based on [openshift/openshift-docs](https://github.com/openshift/openshift-docs) and merge into [rhacs-docs](https://github.com/openshift/openshift-docs/tree/rhacs-docs))

If any of these don't apply, please comment below.

### Here I tell how I validated my change

- see CI passing.

### Reminder for reviewers

In addition to reviewing code here, reviewers **must** also review testing and request further testing in case the
performed one does not seem sufficient. As a reviewer, you must not approve the change until you understand the
performed testing and you are satisfied with it.

### CODE REVIEW

**Comment by dhaus67** [comment]
Current dependencies on/for this PR:
* master
  * **PR #8022** <a href="https://app.graphite.dev/github/pr/stackrox/stackrox/8022" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/stackrox/stackrox/8022?utm_source=stack-comment).

**Review by 0x656b694d — APPROVED** [review]
Not sure what 'The page shows the collected administration usage data' means, but well, it is aligned.

**Review by vjwilson — APPROVED** [review]

**Pull request merged**
